### PR TITLE
fix(web): blank locale cause blank timeline to render

### LINKED ISSUE #17270: v1.131.1: RangeError: Incorrect locale information provided
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I have two instances where I just upgraded the docker install to 1.131.1 and both log the above in the browser console.

Image

### The OS that Immich Server is running on

docker

### Version of Immich Server

1.131.1

### Version of Immich Mobile App

unrelated and still working

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
didn't change
```

### Your .env content

```Shell
didn't change
```

### Reproduction steps

1. Upgrade

### Relevant log output

```shell
None except for the browser console
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alextran1502**
Package change in #17093 treats blank value differently or correctly, causing the timeline not to render anything if the user has a locale key with no value. 

Fixes #17270

### CODE REVIEW

File: web/src/lib/stores/assets-store.svelte.ts [hunk 1]
```diff
@@ -267,7 +267,7 @@ export class AssetBucket {
 
     const year = utcDate.get('year');
     const month = utcDate.get('month');
-    const bucketDateFormatted = utcDate.toJSDate().toLocaleString(get(locale), {
+    const bucketDateFormatted = utcDate.toJSDate().toLocaleString(get(locale) || 'en-US', {
```
Comment (benmccann) [inline web/src/lib/stores/assets-store.svelte.ts:270]: Do you need to default the language to `en-US` everywhere that you get the locale and not just here? If so, it's probably better to do it inside the store so that you can do it in a single place and it applies everywhere and you don't have to update all the individual locations. The cleanest way to do that would probably be to refactor it from a store to a Svelte 5 class

Comment (jrasm91) [reply web/src/lib/stores/assets-store.svelte.ts:270]: I agree this should probably be done where the store is created

Comment (alextran1502) [reply web/src/lib/stores/assets-store.svelte.ts]: Done

**Review by danieldietzler — APPROVED** [review]
