### PR TITLE
fix(web): keep video volume

### LINKED ISSUE #2885: [BUG] video player loses the set volume on the next video
### The bug

When I'm playing a video on the Web, and then use mouse click or arrow keys to go to the next one, it loses the audio volume slider's position. I believe it should persist.

### The OS that Immich Server is running on

Kubernetes (k3s)

### Version of Immich Server

v1.62.1

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. Choose any video
2. Set it's volume to something else than 100%
3. Go to the next video
4. See that it has not kept the slider posiition.
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by faupau03**
save video volume in asset-interaction.store.ts, fixes #2885
google saves the video volume in localstorage, which i think would be the better implementation?

`yt-player-volume:"{"data":"{\"volume\":37,\"muted\":false}","expiration":1689945428802,"creation":1687353428802}"`

### CODE REVIEW

File: web/src/lib/components/asset-viewer/video-viewer.svelte [hunk 1]
```diff
@@ -30,6 +39,7 @@
 		class="h-full object-contain"
 		on:canplay={handleCanPlay}
 		on:ended={() => dispatch('onVideoEnded')}
+		bind:volume
```
Comment (jrasm91) [inline web/src/lib/components/asset-viewer/video-viewer.svelte:42]: You can bind to the store directly by using $videoViewerVolume

**Review by jrasm91 — COMMENTED** [review]
We have some stores that write to local storage maybe you could look at one of those

**Review by jrasm91 — APPROVED** [review]
