### PR TITLE
fix(web): default search to context

### LINKED ISSUE #17112: v.1.130.0-1. Search criteria by filename on default instead of context
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After update to 1.130.0-1 default criteria search is by filename.

Image

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

1.130.1

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

1. Click on searchbox
2. Try to serach by context,
3. No match.
4. Click on extra criteria,
5. Now search by context works.
...

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alextran1502**
Fixes #17112

### CODE REVIEW

File: web/src/lib/components/shared-components/search-bar/search-bar.svelte [hunk 1]
```diff
@@ -164,8 +164,7 @@
   };
 
   function getSearchType(): 'smart' | 'metadata' | 'description' {
-    const t = localStorage.getItem('searchQueryType');
-    return t === 'smart' || t === 'description' ? t : 'metadata';
+    return (localStorage.getItem('searchQueryType') as 'smart' | 'metadata' | 'description') || 'smart';
```
Comment (mertalev) [inline web/src/lib/components/shared-components/search-bar/search-bar.svelte:167]: The type hint is a lie in this case right? I'd prefer if you made it a switch statement with a default case.

Comment (mertalev) [reply web/src/lib/components/shared-components/search-bar/search-bar.svelte:167]: Or you could just return `t` as is if it's any of the three conditions, else `smart`.

Comment (mertalev) [reply web/src/lib/components/shared-components/search-bar/search-bar.svelte:167]: Or you could just return `t` as is if it's any of the three conditions, else `smart`.

Comment (alextran1502) [reply web/src/lib/components/shared-components/search-bar/search-bar.svelte]: Done

**Review by mertalev — APPROVED** [review]
