### PR TITLE
fix(web): let slideshow videos play (#19601)

### LINKED ISSUE #19601: Slideshow applies picture time as well to videos
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When series of pictures and videos is shown as slideshow the maximimum display time for pictures is applied as well to videos. E.g. if display time is set to 5 seconds and a video stream is 30 seconds, the slideshow stops the video after 5 seconds and moves on with next picture or video. For videos the duration of the video should overrule the maximum pictdisplaytime.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

V1.135.3

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

1. Compile Album Containing Images and Videos
2. Start Slideshow
3.
...

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by keanucz**
## Description

I and many others have been experiencing an issue with the slideshow feature (#19601) where the picture interval time is forcefully applied to video files thus preventing them from fully playing to completion.

This PR adds the `AssetType` prop to the `SlideshowBar` component, prevents the spacebar shortcut from playing/pausing the slideshow when a video is playing, and also prevents the ProgressBar component from rendering if a video is being played (which ensures videos are not prematurely cut off).

There may be a more sophisciated and elegant way to get the progress bar component to work & sync up with the video, but I wanted to author as simple of a fix as possible, so I'll leave that up to someone else to implement if they wish. (Personally I think the UI looks cleaner without the progress bar for a video).

Fixes #19601.

## How Has This Been Tested?

I manually tested this on my own Immich server's photo library using my local web UI changes by using a) the Slideshow feature and also b) checking the default asset viewer to make sure no functionality was disrupted.

In slideshow mode I did the following:
1. Start a slideshow on any picture/video
2. Wait for video to fully finish & autoplay onto next photo/video

I also double checked that the spacebar shortcut wouldn't play/pause the slideshow when on a video, and I can confirm that the spacebar play/pause shortcut only affects the native HTML5 video elements when playing a video. 

<details><summary><h2>Screenshots (if appropriate)</h2></summary>

</details>

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation if applicable
- [x] I have no unrelated changes in the PR.
- [x] I have confirmed that any new dependencies are strictly necessary.
- [x] I have written tests for new code (if applicable)
- [x] I have followed naming conventions/patterns in the surrounding code
- [x] All code in `src/services/` uses repositories implementations for database calls, filesystem operations, etc.
- [x] All code in `src/repositories/` is pretty basic/simple and does not have any immich specific logic (that belongs in `src/services/`)

## Please describe to which degree, if any, an LLM was used in creating this pull request.

I used GPT-5.2 Codex to help me generate a starting point for my patch. All code has been manually audited, reviewed and tested by myself before pushing.

### CODE REVIEW

**Review by alextran1502 — APPROVED** [review]
LGTM

File: web/src/lib/components/asset-viewer/slideshow-bar.svelte [hunk 1]
```diff
@@ -35,6 +38,7 @@
   let showControls = $state(true);
   let timer: NodeJS.Timeout;
   let isOverControls = $state(false);
+  let isVideoSlide = $derived(assetType === AssetTypeEnum.Video);
```
Comment (danieldietzler) [inline web/src/lib/components/asset-viewer/slideshow-bar.svelte]:
```suggestion
  const isVideoSlide = $derived(assetType === AssetTypeEnum.Video);
```

**Review by danieldietzler — APPROVED** [review]
