### PR TITLE
fix(server): don't hardcode database name in migration

### LINKED ISSUE #19374: Immich-server fix for #19363 seems to staticly look for a database "immich"
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

The in the title mentioned fix for #19363 seems to doen't use the .env DB_DATABASE_NAME. Instead it just searches for an database named "immich". The Container CrashLoops.

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v.1.135.2

### Version of Immich Mobile App

v1.135.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: immich
  name: server
  labels:
    serviceName: immich
    serviceType: server
spec:
  replicas: 1
  selector:
    matchLabels:
      serviceName: immich
      serviceType: server
  template:
    metadata:
      labels:
        serviceName: immich
        serviceType: server
    spec:
      containers:
        - name: api
          image: ghcr.io/immich-app/immich-server:v1.135.2

          ports:
            - name: api-http
              containerPort: 2283
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /server/ping
              port: api-http
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /server/ping
              port: api-http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3

          volumeMounts:
            - name: library
              mountPath: /usr/src/app/upload
              subPath: files

          env:
            #Common
            - name: TZ
              value: Europe/Berlin

            #Database
            - name: DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: immich-configmap
                  key: database__host
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: immich-configmap
                  key: database__user
            - name: DB_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: immich-configmap
                  key: database__name
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secret
                  key: database__password

            #Service URLs
            - name: REDIS_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: immich-configmap
                  key: redis__host
            - name: IMMICH_MACHINE_LEARNING_URL
              valueFrom:
                configMapKeyRef:
                  name: immich-configmap
                  key: immich__machine_learning_url

  volumeClaimTemplates:
    - metadata:
        name: library
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: zfs
        resources:
          requests:
            storage: 100Gi
```

### Your .env content

```Shell
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: immich
  name: immich-configmap
data:
  # Database
  database__host: service-database-psql
  database__user: immich-database-user
  database__name: immich-database
```

### Reproduction steps

1. Use a database with another name than "immich". For Example: "immich-database"
2. Provide that via ENV "DB_DATABASE_NAME"
3.  Update from v.1.135.2 to 1.135.3

### Relevant log output

```shell
`Query failed : {
  durationMs: 1.0328210000006948,
  error: PostgresError: database "immich" does not exist
      at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
      at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
      at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {
    severity_local: 'ERROR',
    severity: 'ERROR',
    code: '3D000',
    file: 'dbcommands.c',
    line: '3089',
    routine: 'get_database_oid'
  },
  sql: 'alter database immich reset all;',
  params: []
}`
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dotlambda**
## Description

Fixes https://github.com/immich-app/immich/issues/19374

## How Has This Been Tested?
No errors on NixOS, where the database name is immich though.

<details><summary><h2>Screenshots (if appropriate)</h2></summary>

</details>

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if applicable
- [ ] I have no unrelated changes in the PR.
- [ ] I have confirmed that any new dependencies are strictly necessary.
- [ ] I have written tests for new code (if applicable)
- [ ] I have followed naming conventions/patterns in the surrounding code
- [ ] All code in `src/services/` uses repositories implementations for database calls, filesystem operations, etc.
- [ ] All code in `src/repositories/` is pretty basic/simple and does not have any immich specific logic (that belongs in `src/services/`)

cc @mertalev

### CODE REVIEW

**Review by mertalev — APPROVED** [review]

File: server/src/schema/migrations/1750323941566-UnsetPrewarmDimParameter.ts [hunk 1]
```diff
@@ -7,8 +7,8 @@ export async function up(qb: Kysely<any>): Promise<void> {
     return;
   }
 
-  await sql`alter database immich reset all;`.execute(qb);
   const { db, guc } = res.rows[0];
+  await sql`alter database "${db}" reset all;`.execute(qb);
```
Comment (mertalev) [inline server/src/schema/migrations/1750323941566-UnsetPrewarmDimParameter.ts]:
```suggestion
  await sql.raw(`alter database "${db}" reset all;`).execute(qb);
```
