### PR TITLE
fix(server): use exiftool decoded values and unify metadata extraction

### LINKED ISSUE #2786: [BUG] Videos appearing in the wrong place on the timeline
### The bug

I don't have timezone or GPS information for some of my media. Such photos were showing up with the wrong time (https://github.com/immich-app/immich/issues/2000), but this was fixed by https://github.com/immich-app/immich/pull/2003. However, this fix does not work for videos. I think this is because:
- `exiftool-vendored` is currently not used for videos, as stated in this comment: https://github.com/immich-app/immich/pull/1894#discussion_r1120178039
- `exiftool-vendored` extracts `DateTimeOriginal` of videos without timezone and GPS information differently : https://photostructure.github.io/exiftool-vendored.js/variables/defaultVideosToUTC.html 

Here is an example:
The correct time for `VID_20230606_163919.mp4` is `16:39:19`. I have attached the output of `exiftool` below to show that there is no reference to  timezone or coordinates anywhere in its metadata. Immich thinks this video was taken at `6:39 PM GMT+02:00`, as shown in the screenshot below.
Photos - Immich
Instead of appearing next to the photos it was taken with, it appears at a later time on the timeline. Note that photos without timezone or GPS information were showing the same behavior until I set `TZ` in `.env` as suggested by https://github.com/immich-app/immich/pull/2003.

Here is the full output of `exiftool` for `VID_20230606_163919.mp4`:
```bash
ExifTool Version Number         : 12.57
File Name                       : VID_20230606_163919.mp4
Directory                       : .
File Size                       : 171 MB
File Modification Date/Time     : 2023:06:13 23:18:28+02:00
File Access Date/Time           : 2023:06:13 23:18:18+02:00
File Inode Change Date/Time     : 2023:06:13 23:18:33+02:00
File Permissions                : -rw-r--r--
File Type                       : MP4
File Type Extension             : mp4
MIME Type                       : video/mp4
Major Brand                     : MP4 v2 [ISO 14496-14]
Minor Version                   : 0.0.0
Compatible Brands               : isom, mp42
Movie Header Version            : 0
Time Scale                      : 10000
Duration                        : 11.38 s
Preferred Rate                  : 1
Preferred Volume                : 100.00%
Preview Time                    : 0 s
Preview Duration                : 0 s
Poster Time                     : 0 s
Selection Time                  : 0 s
Selection Duration              : 0 s
Current Time                    : 0 s
Next Track ID                   : 3
Android Version                 : 11
Android Capture Fps             : 60
Track Header Version            : 0
Track Create Date               : 2023:06:06 14:39:31
Track Modify Date               : 2023:06:06 14:39:31
Track ID                        : 1
Track Duration                  : 11.38 s
Track Layer                     : 0
Track Volume                    : 0.00%
Image Width                     : 3840
Image Height                    : 2160
Graphics Mode                   : srcCopy
Op Color                        : 0 0 0
Compressor ID                   : avc1
Source Image Width              : 3840
Source Image Height             : 2160
X Resolution                    : 72
Y Resolution                    : 72
Bit Depth                       : 24
Pixel Aspect Ratio              : 65536:65536
Color Profiles                  : nclx
Color Primaries                 : BT.470 System B, G (historical)
Transfer Characteristics        : BT.709
Matrix Coefficients             : BT.601
Video Frame Rate                : 56.869
Matrix Structure                : 1 0 0 0 1 0 0 0 1
Media Header Version            : 0
Media Create Date               : 2023:06:06 14:39:31
Media Modify Date               : 2023:06:06 14:39:31
Media Time Scale                : 48000
Media Duration                  : 11.37 s
Handler Type                    : Audio Track
Handler Description             : SoundHandle
Balance                         : 0
Audio Format                    : mp4a
Audio Channels                  : 2
Audio Bits Per Sample           : 16
Audio Sample Rate               : 48000
XMP Toolkit                     : Image::ExifTool 12.16
Date/Time Original              : 2023:06:06 16:39:19
Create Date                     : 2023:06:06 16:39:19
Modify Date                     : 2023:06:06 16:39:19
Media Data Size                 : 170712406
Media Data Offset               : 408313
Image Size                      : 3840x2160
Megapixels                      : 8.3
Avg Bitrate                     : 120 Mbps
Rotation                        : 90
```

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

v1.61.0

### Version of Immich Mobile App

1.61.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

# NOTE: The following four database variables support Docker secrets by adding a *_FILE suffix to the variable name
# See the docker-compose documentation on secrets for additional details: https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=#####
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# REDIS_URL will be used to pass custom options to ioredis.
# Example for Sentinel
# {"sentinels":[{"host":"redis-sentinel-node-0","port":26379},{"host":"redis-sentinel-node-1","port":26379},{"host":"redis-sentinel-node-2","port":26379}],"name":"redis-sentinel"}
# REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJyZWRpcy1zZW50aW5lbDEiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtc2VudGluZWwyIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6Im15bWFzdGVyIn0=

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/media/Seagate/Immich


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=####
# TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { 'host': 'typesense-1.example.net', 'port': '443', 'protocol': 'https' },
#      { 'host': 'typesense-2.example.net', 'port': '443', 'protocol': 'https' },
#      { 'host': 'typesense-3.example.net', 'port': '443', 'protocol': 'https' },
#  ]
# TYPESENSE_URL=ha://WwogICAgeyAnaG9zdCc6ICd0eXBlc2Vuc2UtMS5leGFtcGxlLm5ldCcsICdwb3J0JzogJzQ0MycsICdwcm90b2NvbCc6ICdodHRwcycgfSwKICAgIHsgJ2hvc3QnOiAndHlwZXNlbnNlLTIuZXhhbXBsZS5uZXQnLCAncG9ydCc6ICc0NDMnLCAncHJvdG9jb2wnOiAnaHR0cHMnIH0sCiAgICB7ICdob3N0JzogJ3R5cGVzZW5zZS0zLmV4YW1wbGUubmV0JywgJ3BvcnQnOiAnNDQzJywgJ3Byb3RvY29sJzogJ2h0dHBzJyB9LApd

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001

###################################################################################
# Immich Version - Optional
#
# This allows all immich docker images to be pinned to a specific version. By default,
# the version is "release" but could be a specific version, like "v1.59.0".
###################################################################################

#IMMICH_VERSION=

####USER DEFINED####
# fixes issue #2000
TZ=Europe/Amsterdam
```

### Reproduction steps

```bash
1. Upload an mp4 video without any timezone information (verify using exiftool)
2. Wait for "Extract Metadata" job to finish
3. Select the photo in the app/web interface and inspect the time by clicking the ⓘ (Info) button.
4. Check the relative position of the video with respect to photos taken before or after it.
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by uhthomas**
There was a lot of unnecessary stuff happening which exiftool should have already taken care of. It's been replaced with the values provided by the exiftool package and the code is much cleaner as a result. Further, exiftool can be used to extract metadata from videos which greatly simplifies things.

Fixes: #2786, #2859, #2953, #1705, #3923, #3888, #3875, #3817

### CODE REVIEW

**Comment by uhthomas** [comment]
I've tested this and it works quite well, though I did notice that video files are missing their timezone. I've asked about this on their forum.

https://exiftool.org/forum/index.php?topic=14946.0

File: server/src/microservices/processors/metadata-extraction.processor.ts [hunk 1]
```diff
@@ -178,165 +108,101 @@ export class MetadataExtractionProcessor {
...
+
+    const tags = { ...mediaTags, ...sidecarTags };
+
+    const exifDate = (dt: ExifDateTime | string | undefined) => dt instanceof ExifDateTime ? dt?.toDate() : null;
+    const zone = (dt: ExifDateTime | string | undefined) => dt instanceof ExifDateTime ? dt.zone : null;
+
+    const parseFocalLength = (focalLength: string | undefined) => focalLength ? parseInt(focalLength.split(' ')[0]) : null;
+
+    return [<ExifEntity>{
+      // altitude: tags.GPSAltitude ?? null,
```
Comment (uhthomas) [inline server/src/microservices/processors/metadata-extraction.processor.ts:186]: should we add the altitude?

File: server/src/microservices/processors/metadata-extraction.processor.ts [hunk 2]
```diff
@@ -93,81 +83,21 @@ export class MetadataExtractionProcessor {
...
-      return this.handleVideoMetadataExtraction(asset);
-    } else {
-      return this.handlePhotoMetadataExtraction(asset);
+    switch (asset.type) {
+      case AssetType.VIDEO:
+        return await this.handleVideoMetadataExtraction(asset);
+      case AssetType.IMAGE:
+        return await this.handleImageMetadataExtraction(asset);
     }
+    return false;
```
Comment (uhthomas) [inline server/src/microservices/processors/metadata-extraction.processor.ts:92]: maybe this?

```suggestion
    return true;
```

File: server/src/microservices/processors/metadata-extraction.processor.ts [hunk 3]
```diff
@@ -178,165 +110,110 @@ export class MetadataExtractionProcessor {
...
+    const zone = (dt: ExifDateTime | string | undefined) => (dt instanceof ExifDateTime ? dt.zone : null);
+
+    const parseFocalLength = (focalLength: string | undefined) =>
+      focalLength ? parseInt(focalLength.split(' ')[0]) : null;
+
+    const validate = <T>(value: T): T | null => typeof value === 'string' ? null : value ?? null;
+
+    return [
+      <ExifEntity>{
+        // altitude: tags.GPSAltitude ?? null,
```
Comment (uhthomas) [inline server/src/microservices/processors/metadata-extraction.processor.ts:196]: question still remains: altitude?

**Comment by uhthomas** [comment]
> I've tested this and it works quite well, though I did notice that video files are missing their time zone. I've asked about this on their forum.
> 
> https://exiftool.org/forum/index.php?topic=14946.0

Interestingly, `OriginalCreateDateTime` does actually return the timezone correctly. I'd like to avoid using this tag though as the package reports it as 0 starts, extremely uncommon and does not even provide an example...

**Comment by evanphilip** [comment]
> I've tested this and it works quite well, though I did notice that video files are missing their time zone. I've asked about this on their forum.
> 
> https://exiftool.org/forum/index.php?topic=14946.0

Perhaps this will fix https://github.com/immich-app/immich/issues/2786

File: server/src/microservices/processors/metadata-extraction.processor.ts [hunk 4]
```diff
@@ -178,165 +110,110 @@ export class MetadataExtractionProcessor {
...
+      : null;
+
+    const stats = fs.statSync(asset.originalPath);
+
+    const tags = { ...mediaTags, ...sidecarTags };
+
+    const exifDate = (dt: ExifDateTime | string | undefined) => (dt instanceof ExifDateTime ? dt?.toDate() : null);
+    const zone = (dt: ExifDateTime | string | undefined) => (dt instanceof ExifDateTime ? dt.zone : null);
+
+    const parseFocalLength = (focalLength: string | undefined) =>
```
Comment (uhthomas) [inline server/src/microservices/processors/metadata-extraction.processor.ts:189]: this can be avoided with the `numericTags` arg.

File: server/src/microservices/processors/metadata-extraction.processor.ts [hunk 5]
```diff
@@ -178,165 +110,110 @@ export class MetadataExtractionProcessor {
...
+        fps: validate(tags.VideoFrameRate),
+        iso: validate(tags.ISO),
+        latitude: validate(tags.GPSLatitude),
+        lensModel: tags.LensModel ?? null,
+        longitude: validate(tags.GPSLongitude),
+        make: tags.Make ?? null,
+        model: tags.Model ?? null,
+        modifyDate: exifDate(tags.ModifyDate) ?? asset.fileModifiedAt,
+        orientation: validate(tags.Orientation)?.toString() ?? null,
+        timeZone: zone(tags.OriginalCreateDateTime),
```
Comment (uhthomas) [inline server/src/microservices/processors/metadata-extraction.processor.ts:214]: no need for this, just use https://github.com/photostructure/exiftool-vendored.js/blob/6408b855b80fe322a8dda3f1c4807f1cc1333844/src/Tags.ts#L4570

**Comment by uhthomas** [comment]
> > I've tested this and it works quite well, though I did notice that video files are missing their time zone. I've asked about this on their forum.
> > https://exiftool.org/forum/index.php?topic=14946.0
> 
> Perhaps this will fix #2786

I believe it will.

File: server/src/microservices/processors/metadata-extraction.processor.ts (hunk 3 above)
Comment (jrasm91) [reply server/src/microservices/processors/metadata-extraction.processor.ts:204]: I assume we could add it. We would need a new column for it and then decide how/when to show the data in the UI?

File: server/src/microservices/processors/metadata-extraction.processor.ts [hunk 6]
```diff
@@ -178,165 +111,117 @@ export class MetadataExtractionProcessor {
...
+    return exifData;
+  }
+
+  private async exifData(asset: AssetEntity): Promise<[ExifEntity, ImmichTags]> {
+    const readTaskOptions = {
+      defaultVideosToUTC: false,
+      useMWG: true,
+      numericTags: ['Duration', 'FocalLength'],
+      includeImageDataMD5: false,
+      geoTz: (lat: number, lon: number): string => geotz.find(lat, lon)[0],
```
Comment (uhthomas) [inline server/src/microservices/processors/metadata-extraction.processor.ts:176]: This package is recommended for use by the `exiftool-vendored` authors as it's more accurate, though "larger" and slower than the default. We've discussed this and concluded we'd prefer the accuracy as the performance impact should be negligible.

File: server/src/microservices/processors/metadata-extraction.processor.ts [hunk 7]
```diff
@@ -178,165 +111,117 @@ export class MetadataExtractionProcessor {
...
+        fps: validate(tags.VideoFrameRate),
+        iso: validate(tags.ISO),
+        latitude: validate(tags.GPSLatitude),
+        lensModel: tags.LensModel ?? null,
+        longitude: validate(tags.GPSLongitude),
+        make: tags.Make ?? null,
+        model: tags.Model ?? null,
+        modifyDate: exifDate(tags.ModifyDate) ?? asset.fileModifiedAt,
+        orientation: validate(tags.Orientation)?.toString() ?? null,
+        timeZone: tags.tz,
```
Comment (uhthomas) [inline server/src/microservices/processors/metadata-extraction.processor.ts:222]: This is probably fine, though it would be good to check.

File: server/src/microservices/processors/metadata-extraction.processor.ts [hunk 8]
```diff
@@ -178,165 +111,117 @@ export class MetadataExtractionProcessor {
...
+        focalLength: validate(tags.FocalLength),
+        fps: validate(tags.VideoFrameRate),
+        iso: validate(tags.ISO),
+        latitude: validate(tags.GPSLatitude),
+        lensModel: tags.LensModel ?? null,
+        longitude: validate(tags.GPSLongitude),
+        make: tags.Make ?? null,
+        model: tags.Model ?? null,
+        modifyDate: exifDate(tags.ModifyDate) ?? asset.fileModifiedAt,
+        orientation: validate(tags.Orientation)?.toString() ?? null,
```
Comment (uhthomas) [inline server/src/microservices/processors/metadata-extraction.processor.ts:221]: This is fine for images, but videos are using degrees. There will need to be some sort of migration at some point. I believe clients look for both enums and degrees which makes things easier, but records in the db will still need to be corrected.

This also shouldn't be a string really.

**Comment by alextran1502** [comment]
Can you help fix the server test? Thank you

File: server/src/microservices/processors/metadata-extraction.processor.ts (hunk 3 above)
Comment (jrasm91) [reply server/src/microservices/processors/metadata-extraction.processor.ts:207]: Let's make this a separate PR after this has been merged.

**Comment by alex-phillips** [comment]
This issue (https://github.com/immich-app/immich/issues/3287)  should be discussed before merging in the changes in this PR that removes the `getExifProperty` function and assuming exiftool returns all valid data without us doing any sort of checking.

**Comment by uhthomas** [comment]
> This issue (#3287) should be discussed before merging in the changes in this PR that removes the `getExifProperty` function and assuming exiftool returns all valid data without us doing any sort of checking.

It would be good to investigate and I hope this PR can solve this, but it should not be a blocker given the current implementation doesn't catch this either.

**Comment by alex-phillips** [comment]
> > This issue (#3287) should be discussed before merging in the changes in this PR that removes the `getExifProperty` function and assuming exiftool returns all valid data without us doing any sort of checking.
> 
> It would be good to investigate and I hope this PR can solve this, but it should not be a blocker given the current implementation doesn't catch this either.

That's true. And this does quite a bit more. The primary logic for the tag values is still centralized into a single function call, so any specific handling that may be done in the future should still be fairly contained.

**Comment by aeozyalcin** [comment]
Hey all, any updates on this PR?

**Review by jrasm91 — APPROVED** [review]
- I have done a decent amount of testing around video files and their time stamps and time zones.
- I have also tested live photos, and verify those still work correctly.
- I have uploaded a 3d photo and verify projection type is correctly set and the viewer shows it in a photo sphere
- I have tested orientation numbers 1-8 and verified the web uses the right aspect ratio for the justified layout.
- I have _NOT_ tested rotated videos

File: server/src/microservices/processors/metadata-extraction.processor.ts (hunk 8 above)
Comment (jrasm91) [reply server/src/microservices/processors/metadata-extraction.processor.ts:307]: Yes, I am OK dealing with this one in the future. It looks like you usually will have values of 1-8 and we should convert the "degrees" variants to probably use that standard in the future.

**Comment by jrasm91** [comment]
> > > This issue (#3287) should be discussed before merging in the changes in this PR that removes the `getExifProperty` function and assuming exiftool returns all valid data without us doing any sort of checking.
> > 
> > 
> > It would be good to investigate and I hope this PR can solve this, but it should not be a blocker given the current implementation doesn't catch this either.
> 
> That's true. And this does quite a bit more. The primary logic for the tag values is still centralized into a single function call, so any specific handling that may be done in the future should still be fairly contained.

This PR does streamline a few things, especially video exif parsing. I think that it is OK to merge it and incorporate groups afterwards. You are probably right in that we'll end up with another version of `getExifValue()`, but that should be easy enough to add back.

File: web/src/lib/utils/asset-utils.ts
Comment (uhthomas) [inline web/src/lib/utils/asset-utils.ts:1]: @jrasm91 Intentional?

Comment (jrasm91) [reply web/src/lib/utils/asset-utils.ts:1]: Yes. 5 is 6 but mirrored and 7 is the same as 8 but mirrored. In both situations they are rotated 90/270 and the aspect ratio needs to be swapped (height and width get flipped).
