### PR TITLE
fix(web+mobile): consistent filename handling

### LINKED ISSUE #2372: [BUG] Can't upload media started with a dot (iOS app)
### The bug

When doing a backup with the Immich iOS app, an error occurs when uploading a video started with a dot.
What these files have in common is that they all come from Instagram, have some sort of filter and are vertical. 
They all start with a dot, which I think is most likely the reason for the error. 
They are from <=2018. 

In my case videos such as:
- `.segmented-62BD76D7-2B49-4638-8BD8-E8BCB33B6FB6.mp4`
- `.filtered-DFACE8B3-9599-4F0F-84CE-ACAC4CBB21E2.mp4`
- `.recorded-257490504876.mp4`
- `.reversed-34908874-8115-4923-B1A7-DAE70DDEA3A8.mp4`

### The OS that Immich Server is running on

Debian GNU/Linux 11 (bullseye) [Raspberry Pi 4]

### Version of Immich Server

v1.54.1

### Version of Immich Mobile App

v1.54.0 build.94

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# REDIS_URL will be used to pass custom options to ioredis.
# Example for Sentinel
# {"sentinels":[{"host":"redis-sentinel-node-0","port":26379},{"host":"redis-sentinel-node-1","port":26379},{"host":"redis-sentinel-node-2","port":26379}],"name":"redis-sentinel"}
# REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJyZWRpcy1zZW50aW5lbDEiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtc2VudGluZWwyIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6Im15bWFzdGVyIn0=

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/mnt/nas/Immich/immich-app/immich-data


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=some-random-text
# TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { 'host': 'typesense-1.example.net', 'port': '443', 'protocol': 'https' },
#      { 'host': 'typesense-2.example.net', 'port': '443', 'protocol': 'https' },
#      { 'host': 'typesense-3.example.net', 'port': '443', 'protocol': 'https' },
#  ]
# TYPESENSE_URL=ha://WwogICAgeyAnaG9zdCc6ICd0eXBlc2Vuc2UtMS5leGFtcGxlLm5ldCcsICdwb3J0JzogJzQ0MycsICdwcm90b2NvbCc6ICdodHRwcycgfSwKICAgIHsgJ2hvc3QnOiAndHlwZXNlbnNlLTIuZXhhbXBsZS5uZXQnLCAncG9ydCc6ICc0NDMnLCAncHJvdG9jb2wnOiAnaHR0cHMnIH0sCiAgICB7ICdob3N0JzogJ3R5cGVzZW5zZS0zLmV4YW1wbGUubmV0JywgJ3BvcnQnOiAnNDQzJywgJ3Byb3RvY29sJzogJ2h0dHBzJyB9LApd

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001
```

### Reproduction steps

```bash
1. Start a backup from the iOS app.
```

### Additional information

_No response_

### LINKED ISSUE #2530: [BUG] Inconsistent filename during upload
### The bug

The original name of uploaded files is altered when it contains sub-extensions and the behavior is inconsistent between mobile and web clients.

For example, I tried uploading a motion photo with the following name: `PXL_20221217_204631955.MP.jpg`

**Observed behavior**

1. Mobile client (Android):
  - filename on server storage: `PXL_20221217_204631955.jpg` [x]
  - filename on UI: `PXL_20221217_204631955.jpg` [x]
  
Mobile

2. Web client (Firefox)
  - filename on server storage: `PXL_20221217_204631955.MP.jpg` [✓]
  - filename on UI: `PXL_20221217_204631955.MP.MP` [x]
  
Web

**Expected behavior**
  - filename on server storage: `PXL_20221217_204631955.MP.jpg`
  - filename on UI: `PXL_20221217_204631955.MP.jpg`

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.57.1

### Version of Immich Mobile App

v1.57.0

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    networks:
      - internal_network
      - nginx_network
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    networks:
      - internal_network
    depends_on:
      - redis
      - database
      - typesense
    restart: always

#  immich-machine-learning:
#    container_name: immich_machine_learning
#    image: ghcr.io/immich-app/immich-machine-learning:release
#    volumes:
#      - ${UPLOAD_LOCATION}:/usr/src/app/upload
#      - model-cache:/cache
#    env_file:
#      - .env
#    networks:
#      - internal_network
#    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    networks:
      - internal_network
      - nginx_network
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    networks:
      - internal_network
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    networks:
      - internal_network
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal_network
    restart: always

#  immich-proxy:
#    container_name: immich_proxy
#    image: ghcr.io/immich-app/immich-proxy:release
#    environment:
#      # Make sure these values get passed through from the env file
#      - IMMICH_SERVER_URL
#      - IMMICH_WEB_URL
#    ports:
#      - 2283:8080
#    logging:
#      driver: none
#    depends_on:
#      - immich-server
#    restart: always

networks:
  internal_network:
  nginx_network:

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=<removed>
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/data/immich
TYPESENSE_API_KEY=<removed>
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
```

### Reproduction steps

```bash
1. Upload a file with one or more sub-extension with mobile client
2. Upload a file with one or more sub-extension with web client
3. Check the name of the files on server storage and on media detail panel
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michelheusschen**
This PR fixes #2530 where the problem is clearly explained, so please check this issue for details.
1. Resolved by sending the unaltered filename to the server, consistent with how [web uploads](https://github.com/immich-app/immich/blob/ecc894ac828a169ee89bff63ea53a688dd3c987c/web/src/lib/utils/file-uploader.ts#L103) are done
2. Created a utility function for getting the filename, which uses the existing `getFilenameExtension` function. Also added unit tests to both

On mobile I was unable to test live photos. The code is almost the same as regular assets but I would like for someone to validate that live photo uploads still work.

Should also fix #2372, but needs validation from someone on iOS

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]

**Comment by alextran1502** [comment]
I think there is a mismatch in the scenario where the user modified the `filename` in the storage template. The mobile app is using the `originalPath` to extract the file name. While the web is using the `originalFileName`. From the bug report, it looks like the user would expect the name on the app matches the name at the storage location. 

I think we should not do that and instead stick with `originalFileName` because there will be cases where we have `duplicatename+1.extension`

What do you think?

**Comment by jrasm91** [comment]
I think it makes sense to show the `originalFilename`, in general. I think separately we can discuss somehow displaying `originalPath`, which is the actual location on disk. They are almost two different features. It is nice to seem the name of the file that was uploaded, but also sometimes it is nice to see exactly where it is stored on disk to go access it directly.

File: web/src/lib/utils/asset-utils.ts [hunk 1]
```diff
@@ -103,8 +103,17 @@ export async function bulkDownload(
...
+	const lastIndex = Math.max(0, filename.lastIndexOf('.'));
+	const startIndex = (lastIndex || Infinity) + 1;
+	return filename.slice(startIndex).toLowerCase();
+}
+
+/**
+ * Returns the filename of an asset including file extension
+ */
+export function getAssetFilename(asset: AssetResponseDto): string {
+	const fileExtension = getFilenameExtension(asset.originalPath);
```
Comment (jrasm91) [inline web/src/lib/utils/asset-utils.ts:115]: Should we consider storing the full filename + extension during upload in `asset.originalFileName`? It seems quite annoying to have to constantly grab it from `originalPath`.

Comment (michelheusschen) [reply web/src/lib/utils/asset-utils.ts:115]: Clients already send filename + extension, but the server only keeps the filename. Storing both in `originalFileName` makes sense, though changing it might give some trouble on mobile

**Comment by michelheusschen** [comment]
This should also fix file uploads starting with a dot on iOS, however I can't verify that because those files on Android are hidden

**Comment by tod31** [comment]
I have several (motion) photos from a Pixel device which were imported before this fix. As mentioned in #2530 the filenames have unfortunately lost the ".MP." part. Is there a way to recover the original filenames or do I have to reimport the photos into immich?
