### PR TITLE
fix: missing deletedAt and isVisible columns on mobile

### LINKED ISSUE #23288: Difference in the number of photos assigned to a person between the web and the mobile app
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hi everyone,

I’ve noticed a discrepancy between the web interface and the mobile app in the number of photos assigned to a person through face recognition.

On the web server, for a specific person, I see 3964 photos assigned, while in the mobile app it shows 3980.
The difference seems to come from older assignments that I manually removed a while ago (because they were incorrect), but the mobile app still shows them as if they were never deleted.

I’ve already tried the following steps:

Deleted the local database file (.sql).

Logged out of the mobile app.

Logged back in and let it fully synchronize.

However, the photo count is still inconsistent.

Has anyone else experienced this?
Is there a way to force the mobile app to completely refresh or re-sync face assignments from the server?

Thanks in advance 🙏

### The OS that Immich Server is running on

 24.04.3 LTS

### Version of Immich Server

v.2.1.0

### Version of Immich Mobile App

2.1.0 build.3022

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Device make and model

samsung M31 android 12

### Your docker-compose.yml content

```YAML
version: "3.8"
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
      - /mnt/immich-data/Fotos:/external-photos:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /docker/immich/model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: redis:6.2
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    volumes:
      - /docker/immich/redis:/data

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    networks:
      default:
        aliases:
          - database
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/immich-data
DB_DATA_LOCATION=/docker/immich/postgres
IMMICH_VERSION=release
DB_PASSWORD=12345678
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Wait for the automatic face scan to complete.
2. Edit one of the assigned faces, removing it because it does not belong to that person.
3. Check the number of photos linked to that person in the web interface.
4. Check the number of photos linked to the same person in the mobile app.
5. Notice that there is a discrepancy in the photo count between web and app.
.

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bwees**
## Description

Fixes #23288

### CODE REVIEW

File: mobile/lib/infrastructure/repositories/sync_api.repository.dart
Comment (shenlong-tanwen) [inline mobile/lib/infrastructure/repositories/sync_api.repository.dart]:
```suggestion
          SyncRequestType.assetFacesV1,
          SyncRequestType.assetFacesV2,
```

File: mobile/lib/infrastructure/repositories/sync_api.repository.dart [hunk 1]
```diff
@@ -64,7 +66,8 @@ class SyncApiRepository {
           SyncRequestType.partnerStacksV1,
           SyncRequestType.userMetadataV1,
           SyncRequestType.peopleV1,
-          SyncRequestType.assetFacesV1,
+          if (serverVersion < const SemVer(major: 2, minor: 6, patch: 0)) SyncRequestType.assetFacesV1,
+          if (serverVersion >= const SemVer(major: 2, minor: 6, patch: 0)) SyncRequestType.assetFacesV2,
```
Comment (bwees) [inline mobile/lib/infrastructure/repositories/sync_api.repository.dart:70]:
```suggestion
          if (serverVersion < const SemVer(major: 2, minor: 5, patch: 6)) SyncRequestType.assetFacesV1,
          if (serverVersion >= const SemVer(major: 2, minor: 5, patch: 6)) SyncRequestType.assetFacesV2,
```

Comment (bwees) [reply mobile/lib/infrastructure/repositories/sync_api.repository.dart:70]: If you need to test use this ^^

**Review by jrasm91 — APPROVED** [review]

**Review by shenlong-tanwen — APPROVED** [review]
