### PR TITLE
fix(server): failed to get albums with archived assets

### LINKED ISSUE #14681: Mobile app can't sync album that is currently being appended to.
### The bug

Using to mobile app, it fails to sync album details while assets are currently being upload to the server. 

The log gives a message from `SyncService`:

    Failed to add album from server: assetCount 34299 != asset array length 34298 for album <album name>

Is this a timing/consistency issue that is easily fixable, or a fundamentally difficult problem? 

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v1.122.2

### Version of Immich Mobile App

v1.122.2 build.170

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Default
```

### Your .env content

```Shell
Default
```

### Reproduction steps

1. On server, start a large upload to a new album. 
2. On mobile, try to view the new album (refresh album view). It does not appear. 
3. Inspect logs (mobile). 

### Relevant log output

```shell
Failed to add album from server: assetCount 34299 != asset array length 34298 for album <album name>
```

### Additional information

_No response_

### LINKED ISSUE #15607: Immich Albums not showing up in android app
### The bug

I just upgraded to v1.125.1, both server and android app. After the upgrade, several albums were no longer showing up on android.

All allbums still show up in web interface. I tried reinstalling the android app, clearing storage/cache, and downgrading to several older versions, with the same results.

### The OS that Immich Server is running on

Linux archlinux 6.9.2-arch1-1

### Version of Immich Server

v1.125.1

### Version of Immich Mobile App

v1.125.1 build 2177

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
DB_DATA_LOCATION=./postgres
IMMICH_VERSION=release
DB_PASSWORD=***redacted***
DB_USERNAME=***redacted***
DB_DATABASE_NAME=immich
```

### Reproduction steps

Not sure how to duplicate, some albums show up and others don't. Don't know why.

### Relevant log output

```shell
2025-01-24 10:12:18.186689 | WARNING  | SyncService          | Failed to add album from server: assetCount 326 != asset array length 0 for album Christus Vincit |
2025-01-24 10:12:18.068061 | WARNING  | SyncService          | Failed to add album from server: assetCount 20 != asset array length 0 for album Server's Manual |
2025-01-24 10:12:18.007423 | WARNING  | SyncService          | Failed to add album from server: assetCount 7 != asset array length 0 for album Tin left at Flower |
2025-01-24 10:12:17.932197 | WARNING  | SyncService          | Failed to add album from server: assetCount 1546 != asset array length 17 for album 0 Paperwork |
2025-01-24 10:12:17.789913 | WARNING  | SyncService          | Failed to add album from server: assetCount 66 != asset array length 22 for album Mass |
2025-01-24 10:12:17.735032 | WARNING  | SyncService          | Failed to add album from server: assetCount 767 != asset array length 1 for album 0 Paperwork Old |
2025-01-24 10:12:17.668609 | WARNING  | SyncService          | Failed to add album from server: assetCount 6 != asset array length 0 for album wire transfers |
2025-01-24 10:12:17.599146 | WARNING  | SyncService          | Failed to add album from server: assetCount 32 != asset array length 31 for album Flower - 13 April 2021 |
2025-01-24 10:12:17.449595 | WARNING  | SyncService          | Failed to add album from server: assetCount 50 != asset array length 0 for album Fr M |
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alextran1502**
Fixes #15607
Fixes #14681

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]

File: server/src/repositories/album.repository.ts [hunk 1]
```diff
@@ -63,7 +63,6 @@ const withAssets = (eb: ExpressionBuilder<DB, 'albums'>) => {
         .innerJoin('albums_assets_assets', 'albums_assets_assets.assetsId', 'assets.id')
         .whereRef('albums_assets_assets.albumsId', '=', 'albums.id')
         .where('assets.deletedAt', 'is', null)
-        .where('assets.isArchived', '=', false)
```
Comment (mertalev) [inline server/src/repositories/album.repository.ts:66]: Is this correct? Don't you want to exclude archived assets from the album view?
