### PR TITLE
fix(mobile): hide asset description text field if user is not owner

### LINKED ISSUE #7546: Images in a shared album show the “add description” option
### The bug

In shared albums, at least on mobile, the `add description…` dialog is not interactable with for pictures that were added by another user. 

Solution: either allow all users to edit descriptions, or change the tooltip to “cannot edit description of a shared photo” for images that are not owned by the current user. 

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.97.0

### Version of Immich Mobile App

v1.97.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/a
```

### Your .env content

```Shell
N/a
```

### Reproduction steps

```bash
1. Make a shared album
2. Ask someone else to add a picture
3. Try to add a description
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gaganyadav80**
* If user is not the owner and asset has no description then hide the text field

## Description

Fixes #7546 

## How Has This Been Tested?

- [x] When user is owner, the description text field is enabled and loads any existing content in the field.
- [x] When user is NOT the owner and asset already has description then field it is visible but disabled.
- [x] When user is neither owner nor the asset has description then field is hidden

### CODE REVIEW

File: mobile/lib/widgets/asset_viewer/description_input.dart [hunk 1]
```diff
@@ -34,17 +34,24 @@ class DescriptionInput extends HookConsumerWidget {
     final owner = ref.watch(currentUserProvider);
     final hasError = useState(false);
     final assetWithExif = ref.watch(assetDetailProvider(asset));
+    final assetHasDescription = useState(false);
+    final isAssetOwnedByUser = fastHash(owner?.id ?? '') == asset.ownerId;
```
Comment (alextran1502) [inline mobile/lib/widgets/asset_viewer/description_input.dart:38]:
```suggestion
    final isOwner = fastHash(owner?.id ?? '') == asset.ownerId;
```

File: mobile/lib/widgets/asset_viewer/description_input.dart [hunk 2]
```diff
@@ -34,17 +34,24 @@ class DescriptionInput extends HookConsumerWidget {
     final owner = ref.watch(currentUserProvider);
     final hasError = useState(false);
     final assetWithExif = ref.watch(assetDetailProvider(asset));
+    final assetHasDescription = useState(false);
```
Comment (alextran1502) [inline mobile/lib/widgets/asset_viewer/description_input.dart:37]:
```suggestion
    final hasDescription = useState(false);
```

File: mobile/lib/widgets/asset_viewer/description_input.dart [hunk 3]
```diff
@@ -34,17 +34,24 @@ class DescriptionInput extends HookConsumerWidget {
...
+        assetService.getDescription(asset).then((value) {
+          controller.text = value;
+          assetHasDescription.value = value.isNotEmpty;
+        });
         return null;
       },
       [assetWithExif.value],
     );
 
+    if (!isAssetOwnedByUser && !assetHasDescription.value) {
```
Comment (alextran1502) [inline mobile/lib/widgets/asset_viewer/description_input.dart:51]: You still need to change these variable names 😄

Comment (gaganyadav80) [reply mobile/lib/widgets/asset_viewer/description_input.dart]: Really sorry about the lousiness. 😅

**Review by alextran1502 — APPROVED** [review]
