### PR TITLE
fix: image download complete notification shows an extra {file_name} template tag

### LINKED ISSUE #25690: Image download complete notification shows an extra `{file_name}` template tag
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

While I was downloading an image from my Immich app v2.5.2 (Android), I noticed the notification text has an extra `{file_name}` template tag. (It looks weird but cool.)

Image

Image

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v2.5.2

### Version of Immich Mobile App

v2.5.2 build 3033

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Device make and model

Pixel 7a, Android 16

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    user: "1000:1200"
    group_add:
      - 993
      - 44
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - /serverdata/file-sharing/PhotosBackup:/usr/src/app/external/qthang
      - /mnt/immich-storagebox:/mnt/immich-storagebox
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml
      service: vaapi # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    env_file:
      - .env
    depends_on:
      - immich-redis
    restart: unless-stopped
    networks:
      - default
      - frontend
      - backend

  immich-redis:
    container_name: immich-redis
    image: valkey/valkey:8-alpine
    restart: always
    networks:
      - backend
      - default

  immich-machine-learning:
    container_name: immich-machine-learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:release
    #extends: # uncomment this section for hardware acceleration - see https://docs.immich.app/features/ml-hardware-acceleration
    #  file: hwaccel.ml.yml
    #  service: cuda # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    restart: always
    networks:
      - default
    healthcheck:
      disable: false

networks:
  frontend:
    external: true
  backend:
    external: true
  default:

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/serverdata/media/media/images/
# The location where your database files are stored               DB_DATA_LOCATION=/var/lib/postgres/data

# The Immich version to use. You can pin this to a specific version like "v1.71.0"                                                  IMMICH_VERSION=release

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Asia/Ho_Chi_Minh

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<REDACTED>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=immich
DB_DATABASE_NAME=immich
DB_HOSTNAME=postgresql-database

REDIS_HOSTNAME=immich-redis
REDIS_PORT=6379

LOG_LEVEL=info

# DB_SKIP_MIGRATIONS=true

# IMMICH_TRUSTED_PROXIES="172.19.0.0/16, 172.20.0.0/16"
```

### Reproduction steps

1. Launch the Immich app and download any image you want
2. Open the system notification screen (mine is dragging down from the top of the page)
3. The bugged notification should be there.

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by romoisverycool**
## Description

Caused by #24547
Fixes #25690

## How Has This Been Tested?

I have not tested this, but looking at the code it looks good

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if applicable
- [ ] I have no unrelated changes in the PR.
- [ ] I have confirmed that any new dependencies are strictly necessary.
- [ ] I have written tests for new code (if applicable)
- I have followed naming conventions/patterns in the surrounding code
- [ ] All code in `src/services/` uses repositories implementations for database calls, filesystem operations, etc.
- [ ] All code in `src/repositories/` is pretty basic/simple and does not have any immich specific logic (that belongs in `src/services/`)

## Please describe to which degree, if any, an LLM was used in creating this pull request.

I used a AI to make sure the args were correct.

### CODE REVIEW

File: mobile/lib/utils/bootstrap.dart [hunk 1]
```diff
@@ -27,17 +27,19 @@ import 'package:isar/isar.dart';
...
+    complete: TaskNotification('download_finished'.t(), FileName),
     progressBar: true,
   );
 
   FileDownloader().configureNotificationForGroup(
     kDownloadGroupVideo,
-    running: TaskNotification('downloading_media'.t(), '${'file_name'.t()}: {filename}'),
-    complete: TaskNotification('download_finished'.t(), '${'file_name'.t()}: {filename}'),
+    running: TaskNotification('downloading_media'.t(), FileName),
+    complete: TaskNotification('download_finished'.t(), FileName),
```
Comment (shenlong-tanwen) [inline mobile/lib/utils/bootstrap.dart]:
```suggestion
  final filename = 'file_name'.t(args: {'file_name': '{filename}'});
  
FileDownloader().configureNotificationForGroup(
kDownloadGroupImage,
    running: TaskNotification('downloading_media'.t(), fileName),
    complete: TaskNotification('download_finished'.t(), fileName),
progressBar: true,
);

FileDownloader().configureNotificationForGroup(
kDownloadGroupVideo,
    running: TaskNotification('downloading_media'.t(), fileName),
    complete: TaskNotification('download_finished'.t(), fileName),
```

**Review by shenlong-tanwen — APPROVED** [review]
Thanks

**Comment by romoisverycool** [comment]
This is my first commit. Thank you!
