### PR TITLE
fix(server): memory lane assets order

### LINKED ISSUE #15881: Memories - all pictures are in random/wrong order
### The bug

Both on the app and on iOS app, the memories' pictures are in the wrong order. When you click on the button to go to your timeline for that day, photos display in the correct order.
This wasn't happening before.

### The OS that Immich Server is running on

Debian 11

### Version of Immich Server

v1.125.7

### Version of Immich Mobile App

v1.125.3 build.191

### Platform with the issue

- [ ] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
.
```

### Your .env content

```Shell
.
```

### Reproduction steps

Look at memories.

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alextran1502**
Fixes #15881

### CODE REVIEW

File: server/src/repositories/asset.repository.ts [hunk 1]
```diff
@@ -121,6 +121,7 @@ export class AssetRepository implements IAssetRepository {
                   ),
                 )
                 .where('assets.deletedAt', 'is', null)
+                .orderBy('assets.localDateTime', 'desc')
```
Comment (mertalev) [inline server/src/repositories/asset.repository.ts:124]: It should use the double "at time zone" syntax since it can't use the index unless you specify that.

Comment (alextran1502) [reply server/src/repositories/asset.repository.ts:124]: Good to know, thanks!

Comment (mertalev) [reply server/src/repositories/asset.repository.ts]: Oh, that is actually only for the `dare_trunc` index. I'm not sure if there's an index just on `localDateTime`.

**Review by jrasm91 — APPROVED** [review]

**Comment by kikendo** [comment]
This is still not working properly, please re-open #15881
