### PR TITLE
fix(web): search people

### LINKED ISSUE #8951: "Search people" not working with non-english queries
### The bug

When filtering a list of "People" on `https://BASE_URL/people` web page, only special character queries or queries with English characters show results. Queries in a different language or with language-specific characters return no results.

### The OS that Immich Server is running on

TrueNAS SCALE

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

irrelevant

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
TrueCharts Kubernetes template in https://github.com/truecharts/charts/tree/master/charts/stable/immich
```

### Your .env content

```Shell
🤷‍♂️
```

### Reproduction steps

```bash
1. Name some person "Alex Влад Bülow" (english, cyrillic, german)
2. Search for english letter "A" – found a match
3. Search for cyrillic letter "В" – no matches
4. Search for german umlaut "ü" - no matches
```

### Relevant log output

_No response_

### Additional information

Same steps attempted on the "Merge people" screen work just fine.

### PR DESCRIPTION
**Pull request by martabal**
Potential fix for #8951.
Show people searched with the `searchPerson` API instead of relying on people returned by the `getAllPeople` API.

## Screenshots

image

### CODE REVIEW

File: web/src/routes/(user)/people/+page.svelte [hunk 1]
```diff
@@ -439,10 +439,10 @@
     {/if}
   </svelte:fragment>
 
-  {#if countVisiblePeople > 0}
+  {#if countVisiblePeople > 0 && (!searchName || (searchName && searchedPeopleLocal.length > 0))}
```
Comment (danieldietzler) [inline web/src/routes/(user)/people/+page.svelte:442]:
```suggestion
  {#if countVisiblePeople > 0 && (!searchName || searchedPeopleLocal.length > 0)}
```
If we specify the condition `searchName` as `x` and `searchedPeopleLocal.length > 0` as `y`, what you have there is `!x || (x && y)`. This however you can factor out to `(!x || x) && (!x || y)`. `!x || x` is tautological, so you can throw that term away resulting in the suggestion :)

File: web/src/routes/(user)/people/+page.svelte [hunk 2]
```diff
@@ -451,14 +451,31 @@
...
+        {/each}
+      {/if}
     </div>
   {:else}
     <div class="flex min-h-[calc(66vh_-_11rem)] w-full place-content-center items-center dark:text-white">
       <div class="flex flex-col content-center items-center text-center">
         <Icon path={mdiAccountOff} size="3.5em" />
-        <p class="mt-5 text-3xl font-medium">No people</p>
+        <p class="mt-5 text-3xl font-medium">
+          No people {#if searchName}
```
Comment (danieldietzler) [inline web/src/routes/(user)/people/+page.svelte:475]: I would prefer if the if starts in the next line

**Review by danieldietzler — COMMENTED** [review]
Haven't tested it out yet but the code looks good so far

File: web/src/routes/(user)/people/+page.svelte (hunk 1 above)
Comment (martabal) [reply web/src/routes/(user)/people/+page.svelte]: That's what I call a great optimization :smile:

File: web/src/routes/(user)/people/+page.svelte (hunk 2 above)
Comment (martabal) [reply web/src/routes/(user)/people/+page.svelte:475]: Yeah I was worried about the space between `people` and `with`

Comment (danieldietzler) [reply web/src/routes/(user)/people/+page.svelte]: Oh then don't use an if but a ternary in the same line? Something like `No people{searchName ? ' with name ${searchName}' : ''}` (there should be backticks ofc since it's a template string)

**Comment by danieldietzler** [comment]
Any idea why I'm losing focus whenever I type a single character?

https://github.com/immich-app/immich/assets/36593685/3d6865f7-fa02-4071-aa39-64bb72b2dbfa

**Comment by alextran1502** [comment]
> Any idea why I'm losing focus whenever I type a single character?
> 
>  Screen.Recording.2024-04-22.at.20.44.23.mov

It was fixed on `main` we probably need to pull main into this PR

**Comment by danieldietzler** [comment]
That was it, thank you Alex! However it still loses focus when the search field becomes empty. Is that intentional?

**Review by danieldietzler — APPROVED** [review]
LGTM
