### PR TITLE
fix(mobile): incorrect date range

### LINKED ISSUE #4579: [BUG] mobile: album date range is wrong
### The bug

All albums with assets taken within multiple days show wrong date range.

|mobile|web|
|--|--|
|obrazek|obrazek|

### The OS that Immich Server is running on

Fedora 38

### Version of Immich Server

v.1.82.1

### Version of Immich Mobile App

1.82.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
not relevant
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alextran1502**
image

### CODE REVIEW

File: mobile/lib/modules/album/views/album_viewer_page.dart [hunk 1]
```diff
@@ -164,27 +164,31 @@ class AlbumViewerPage extends HookConsumerWidget {
...
-      final DateTime startDate = album.assets.first.fileCreatedAt;
-      final DateTime endDate = album.assets.last.fileCreatedAt; //Need default.
-      final String startDateText = (startDate.year == endDate.year
-              ? DateFormat.MMMd()
-              : DateFormat.yMMMd())
-          .format(startDate);
-      final String endDateText = DateFormat.yMMMd().format(endDate);
+      final DateTime? startDate = album.startDate;
+      final DateTime? endDate = album.endDate;
+      if (startDate != null && endDate != null) {
```
Comment (jrasm91) [inline mobile/lib/modules/album/views/album_viewer_page.dart:169]: if you changed it to this you could de-indent everything else btw.
```
if(startDate == null || endDate == null) {
  return const SizedBox();
}
```

**Review by jrasm91 — APPROVED** [review]
