### PR TITLE
fix(server): support import paths with special chars

### LINKED ISSUE #14588: Can't crawl libraries with import paths containing quote symbols
### The bug

Hi there!

First, thank you for creating Immich! It has been fantastic to use, and I appreciate all the hard work you’ve put into it.

**The Issue**
I noticed that some of my images are missing from my library. Upon further inspection, it seems that files in import paths containing apostrophes (like /path/to/John's Photos) aren’t being indexed. These files don’t show up in the library even though the paths are valid and accessible.

I create this little example to check if my suspicion was correct:
sc_immich
Both folders contain similar images, however, only the images from "/bilder/Test/" are added to my library.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.122.1

### Version of Immich Mobile App

-

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /srv/XXXXX/XXXX/Bilder:/bilder
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
DB_DATA_LOCATION=./postgres
IMMICH_VERSION=release
DB_PASSWORD=XXXX
DB_USERNAME=XXXX
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Add an external library
2. Add an import path containing an apostrophe
3. Try to index the external library

### Relevant log output

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by etnoy**
Fixes #14588

It was not possible to have an import path with apostrope, double quote, asterisk and so on. Now it works.

Also adds support for several other special characters, except for backslash which seems like a special category of difficult

### CODE REVIEW

**Review by alextran1502 — APPROVED** [review]

File: server/src/repositories/storage.repository.ts [hunk 1]
```diff
@@ -214,7 +214,7 @@ export class StorageRepository implements IStorageRepository {
   }
 
   private asGlob(pathToCrawl: string): string {
```
Comment (alextran1502) [inline server/src/repositories/storage.repository.ts:216]: why is there a square bracket?

Comment (etnoy) [reply server/src/repositories/storage.repository.ts:216]: Around the special characters? Turns out, that's how you escape double quotes, single quotes and asterisks when using a dynamic glob pattern. A literal " is written as ["]

File: server/src/repositories/storage.repository.ts [hunk 2]
```diff
@@ -214,7 +214,7 @@ export class StorageRepository implements IStorageRepository {
...
-    const escapedPath = escapePath(pathToCrawl);
+    const escapedPath = escapePath(pathToCrawl).replaceAll('"', '["]').replaceAll("'", "[']").replaceAll('`', '[`]');
```
Comment (danieldietzler) [inline server/src/repositories/storage.repository.ts:217]: It's so freaking annoying that there isn't just a library `escapePath` function that does it all...

**Review by danieldietzler — APPROVED** [review]

**Review by mertalev — APPROVED** [review]

File: server/src/repositories/storage.repository.ts (hunk 2 above)
Comment (etnoy) [reply server/src/repositories/storage.repository.ts:217]: We uncover all kinds of bugs in libraries, I should probably file this as an issue with fast-glob. Likely we are the first ones to even notice
