### PR TITLE
fix(server): handle NaN in metadata extraction

### LINKED ISSUE #4195: [BUG] Error when viewing map on web
### The bug

When I click on the Map in the web, it shows 3 circles, containing about 3,000 photos total. However, I have about 70,000 photos in my library, most of which were taken on cell phones and therefore have latitude/longitude coordinates. Additionally, after a few moments, the map appears to become unresponsive and clicking any button or link has no affect.

To investigate, I opened the console in developer tools and found the following error.

index.8e9d6492.js:4 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'lat')
    at Object.project (index.8e9d6492.js:4:14552)
    at Object.latLngToPoint (index.8e9d6492.js:4:13160)
    at e.project (index.8e9d6492.js:4:38053)
    at e._addLayer (index.8e9d6492.js:4:165524)
    at e.<anonymous> (index.8e9d6492.js:4:155265)
    at e.addLayers (index.8e9d6492.js:4:155706)
    at As.k.$$.update (index.8e9d6492.js:4:187620)
    at It (boolean_attributes.1a147532.js:4:1732)
    at Gt (boolean_attributes.1a147532.js:4:1463)

Immich Error

### The OS that Immich Server is running on

Ubuntu 20.04.6 LTS

### Version of Immich Server

1.79.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/media/Documents/Pictures:/mnt/media/Pictures/External:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/media/Documents/Pictures:/mnt/media/Pictures/External:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d>
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/enviro>

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/media/Pictures/Backup

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Navigate to Immich.
2. Click on Map.
3. Error will immediately appear in the dev console.
```

### Additional information

This is a new instance of Immich that I recently spun up to use the External Libraries feature. All of these photos have been loaded using that tool.

### PR DESCRIPTION
**Pull request by djak250**
Fix #4195 
Fallback to null in event of invalid number.

### CODE REVIEW

File: server/src/infra/migrations/1695660378655-fixGPSNullIslandRedux.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import { MigrationInterface, QueryRunner } from 'typeorm';
+
+export class FixGPSNullIslandRedux1695660378655 implements MigrationInterface {
+  public async up(queryRunner: QueryRunner): Promise<void> {
+    await queryRunner.query(
+      `UPDATE "exif" SET latitude = NULL, longitude = NULL WHERE latitude = 'NaN' AND longitude = 'NaN';`,
```
Comment (jrasm91) [inline server/src/infra/migrations/1695660378655-fixGPSNullIslandRedux.ts:6]: Can you just copy `1685731372040-RemoveInvalidCoordinates.ts`?

**Comment by djak250** [comment]
A more direct fix for #4195 than the one in #4217

File: server/src/microservices/processors/metadata-extraction.processor.ts [hunk 2]
```diff
@@ -44,9 +44,21 @@ interface ImmichTags extends Tags {
...
 
+const exifDate = (dt: ExifDateTime | string | undefined) => (dt instanceof ExifDateTime ? dt?.toDate() : null);
+const validate = <T>(value: T): NonNullable<T> | null => {
+  if (typeof value === 'string' && value === '') {
+    return null;
+  }
+  if (typeof value === 'number' && isNaN(value)) {
+    return null;
+  }
+  return value ?? null;
```
Comment (jrasm91) [inline server/src/microservices/processors/metadata-extraction.processor.ts:60]: If the value is a string, it means it failed to parse it as a number, so any string should return null.
If the value is a number, we should probably check `isNaN` and `isFinite`.

File: server/src/microservices/processors/metadata-extraction.processor.ts [hunk 3]
```diff
@@ -293,7 +304,7 @@ export class MetadataExtractionProcessor {
         exposureTime: tags.ExposureTime ?? null,
         fileSizeInByte: stats.size,
         fNumber: validate(tags.FNumber),
-        focalLength: validate(tags.FocalLength),
+        focalLength: validate(tags.FocalLength as unknown as number | undefined), // Exiftool Tags type fails to incorporated `numericTags`.
```
Comment (jrasm91) [inline server/src/microservices/processors/metadata-extraction.processor.ts:307]: Maybe we can instead modify `ImmichTags` to handle this.

File: server/src/infra/migrations/1695660378655-fixGPSNullIslandRedux.ts (hunk 1 above)
Comment (djak250) [reply server/src/infra/migrations/1695660378655-fixGPSNullIslandRedux.ts:6]: Yeah. I just didn't see it, because the one I copied is more recent.

File: server/src/microservices/processors/metadata-extraction.processor.ts (hunk 3 above)
Comment (djak250) [reply server/src/microservices/processors/metadata-extraction.processor.ts:307]: I went down that path, but since `ImmichTags` is passed in to the `exifTool.read` generic, `ImmichTags` has to extend `Tags`. Changing `FocalLength` to `string` makes it an invalid extension. It would be nice if ExifTools were able to extend their own `Tags` type based on `numericTags`, but I can see how that would be extremely difficult to accomplish.

File: server/src/microservices/processors/metadata-extraction.processor.ts (hunk 2 above)
Comment (djak250) [reply server/src/microservices/processors/metadata-extraction.processor.ts:60]: I was curious about that. I think I changed this early on in the solution, since `tags.FocalLength` was still reporting as `string`.

File: server/src/microservices/processors/metadata-extraction.processor.ts (hunk 3 above)
Comment (jrasm91) [reply server/src/microservices/processors/metadata-extraction.processor.ts:307]: Right, but those tags are generated to begin with and not even 100% accurate. I'd be more inclined to cast to unknown/any there and get the rights tags back for everything else.

Comment (jrasm91) [reply server/src/microservices/processors/metadata-extraction.processor.ts:307]: We can, for example extend `Omit<Tags, 'FocalLength'>` and then cast `read(...) as ImmichTags` or similar.

Comment (djak250) [reply server/src/microservices/processors/metadata-extraction.processor.ts:308]: You'd have to cast both calls to `read` for the variables `mediaTags` (:280-283), `sidecarTags` (:285-289), as well as casting `tags` back to Tags for the call to `firstDateTime` on line :301. 

But I'm not sure I understand your concern about the change above. The cast is passed into a function that will immediately confirm the cast is accurate. Further, this type is not exported, so the area of impact is limited to this single file.

Comment (jrasm91) [reply server/src/microservices/processors/metadata-extraction.processor.ts:308]: The main thought was to just have accurate typing. `Tags` is inaccurate when you calls `validate` and it would be nice if it was.

Comment (djak250) [reply server/src/microservices/processors/metadata-extraction.processor.ts]: I'll make that change. But I'm going to create an issue with exiftool-vendored, regarding `numericTags`

**Review by jrasm91 — APPROVED** [review]
Looks pretty good!

**Comment by v3DJG6GL** [comment]
Would this fix errors like e.g. this one?
image

**Comment by alextran1502** [comment]
Hello, can you help with resolving the merge conflict

**Comment by djak250** [comment]
Sorry for missing the merge conflicts. Got tied up with work the past two days.... Must not have been too difficult a conflict though.
