### PR TITLE
fix(mobile): asset description is not shown on the sheet when opened for the first time

### LINKED ISSUE #8042: bug(mobile): asset description is not shown
### The bug

Asset description is not shown when (i) button is clicked. Info panel has to be closed and opened again to show description.

https://github.com/immich-app/immich/assets/15554561/81dc7fab-a725-4376-ae0a-1e1fcc0673c3

### The OS that Immich Server is running on

Fedora 39

### Version of Immich Server

v1.98.2

### Version of Immich Mobile App

v1.98.2

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. add description to an asset on web or mobile and kill the app then
2. view asset on mobile
3. click (i) button
4. no description is shown
5. close info panel
6. open it again and see description
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by RanKKI**
fixed #8042

There is no need to use `assetDescriptionProvider` to load remote/local description as it has been read in `ExifBottomSheet.exifInfo`.

### CODE REVIEW

File: mobile/lib/widgets/asset_viewer/description_input.dart [hunk 1]
```diff
@@ -25,25 +28,25 @@ class DescriptionInput extends HookConsumerWidget {
     final focusNode = useFocusNode();
     final isFocus = useState(false);
     final isTextEmpty = useState(controller.text.isEmpty);
-    final descriptionProvider =
-        ref.watch(assetDescriptionProvider(asset).notifier);
-    final description = ref.watch(assetDescriptionProvider(asset));
+    final descriptionService = ref.watch(assetDescriptionServiceProvider);
```
Comment (alextran1502) [inline mobile/lib/widgets/asset_viewer/description_input.dart:31]:
```suggestion
    final descriptionProvider = ref.watch(assetDescriptionServiceProvider);
```

**Review by alextran1502 — APPROVED** [review]
