### PR TITLE
fix(web): svelte regression - cancel video preview fetch when bind:this is cleared early

### LINKED ISSUE #27585: Firefox stops loading images and web app fails while scrolling
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

See behavior here [https://youtu.be/az1G45ZkZBc](https://youtu.be/az1G45ZkZBc)
This is only on firefox. Chromium based browsers are fine.

Seems like the web app just stops being dynamic or loading when you're scrolling. I saw some other issues online (#21284) but there's no discussion/details around any of these so it's impossible to know if I'm experiencing a design limitation or a bug.

The only thing I'm not doing that's default is running a storage template and ML container is on a different machine.

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v2.6.3

### Version of Immich Mobile App

v2.6.3

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Device make and model

Windows 11x64 Firefox

### Your docker-compose.yml content

```YAML
immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi
    volumes:
      - ${UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9@sha256:3eeb09785cd61ec8e3be35f8804c8892080f3ca21934d628abc24ee4ed1698f6
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    healthcheck:
      disable: false
```

### Your .env content

```Shell
UPLOAD_LOCATION=/home/docker/immich/library
DB_DATA_LOCATION=/home/docker/immich/postgres
TZ=America/New_York
IMMICH_VERSION=v2.6.3
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
IMMICH_MACHINE_LEARNING_URL=http://10.<redacted>:3003
```

### Reproduction steps

1. Upload Library
2. Scroll with Firefox
3. See images not load

### Relevant log output

```shell
The only error I get is when I reload the page, I get a red box quickly that says "Failed to load assets"
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by midzelis**
## Description

This was actually a regression from #27109 which updated svelte. Svelte [5.53.9](https://github.com/sveltejs/svelte/pull/17885) had "fix: better bind:this cleanup timing". This svelte change  clears bind:this references earlier in the unmount sequence — before sibling $effects observing the same gating state get to read them. 

The fix is to capture the video element BEFORE it is cleaned up by svelte, so that we can remove the src attribute (which firefox uses to stop a video from playing - chrome was unaffected) 

Fixes #27585

### CODE REVIEW

**Review by alextran1502 — APPROVED** [review]
Thanks Min

File: web/src/lib/components/assets/thumbnail/video-thumbnail.svelte [hunk 1]
```diff
@@ -36,14 +36,18 @@
...
-      if (player) {
-        // Cancel video buffering.
-        player.src = '';
-      }
+      return;
+    }
+    if (!player) {
+      return;
     }
+    const video = player;
```
Comment (danieldietzler) [inline web/src/lib/components/assets/thumbnail/video-thumbnail.svelte:45]: What's the point of this? It's a reference anyways, so both should be completely identical and if one gets cleaned up, the other is gone/points to nowhere too. What am I missing?

Comment (midzelis) [reply web/src/lib/components/assets/thumbnail/video-thumbnail.svelte:45]: It's used in a closure used in the effect destroy. The player variable is managed by bind:this (undefined before mount and after destroy) the effect now runs after the bind:this is cleared. So the effect saves a reference so you can clean up the 'video' (src) after 'player' has already been cleared.

Comment (danieldietzler) [reply web/src/lib/components/assets/thumbnail/video-thumbnail.svelte:45]: Oh I get it, thanks

**Review by danieldietzler — APPROVED** [review]
