### PR TITLE
fix: prevent an offline asset from being used as a person feature photo

### LINKED ISSUE #13055: Wrong success messages when changing featured photo of non existing picture
### The bug

This is a secondary error.    
In the external (!) library, photos were moved. They are still in the index of immich. If you display the picture and try to zoom in the correct message is shown
```Asset Offline
This external library asset is no longer found on disk and has been moved to trash. If the file was moved within the library, check your timeline for the new corresponding asset. To restore this asset, please ensure that the file path below can be accessed by Immich and scan the library.
```

Now the described bug:

* Select a person (localhost:2283/people/{uuid})
* select featured photo
* Now select such a non existing picture. 
* The success (!) message is displayed: `Info: Feature photo updated`
* But the photo is (of course) the old one.

So the underlying error is not displayed to the end-user

Thanks for that great software!!

### The OS that Immich Server is running on

Windows Docker

### Version of Immich Server

V1.116.2

### Version of Immich Mobile App

--

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc #cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - mein-share:/mnt/nas
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4_container
      restart: always
      ports:
        - "8888:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
        PGADMIN_DEFAULT_PASSWORD: strong-password
      volumes:
        - pgadmin-data:/var/lib/pgadmin

volumes:
  model-cache:
  pgadmin-data:
  mein-share:
    driver_opts:
      type: cifs
      o: username=xxx,password=xxx,vers=1.0
      device: //192.xxx.xxx.xxx/photo
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
NVIDIA_VISIBLE_DEVICES=all
```

### Reproduction steps

1. move pictures in external file share
2. immich web: go to a person
3. select featured photo
4. select a moved/deleted photo
5. the success message is displayed  `Info: Feature photo updated`
6. (of course) the old picture is displayed

### Relevant log output

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jrasm91**
Fixes #13055

Throw an error when trying to update a feature photo to an asset that is offline.

### CODE REVIEW

File: server/src/repositories/person.repository.ts [hunk 1]
```diff
@@ -481,7 +475,12 @@ export class PersonRepository {
     return this.db
       .selectFrom('asset_face')
       .selectAll('asset_face')
-      .select(withAsset)
+      .select((eb) =>
+        jsonObjectFrom(eb.selectFrom('asset').selectAll('asset').whereRef('asset.id', '=', 'asset_face.assetId')).as(
+          'asset',
+        ),
+      )
+      .$narrowType<{ asset: NotNull }>()
```
Comment (alextran1502) [inline server/src/repositories/person.repository.ts:483]: What is this `$narrowType`?

Comment (jrasm91) [reply server/src/repositories/person.repository.ts:483]: The default type is `Asset | undefined`, since it's just a select and it thinks it could be `null`. In reality, there is a foreign key to the asset table and it is impossible for it to ever be `null`. Kysely provides this `$narrowType()` method to _narrow the types_ in ways that cannot be easily inferred otherwise, like this.

TLDR; Kysely thinks it is nullable, it is not. This utility is the way to correct the type.

**Review by alextran1502 — APPROVED** [review]
