### PR TITLE
fix(web): logout and clear user store when using back button on the change password form

### LINKED ISSUE #6275: Login workflow authenticates incorrect user
### Pre-requisites
- admin account
- new user created as a partner to the admin (not sure that counts)

### Steps to reproduce
1. login with the new user
2. at the prompt to change the password for first connection, navigate back to the login page
3. login as the admin
Result: I am now logged in as the new user instead of the admin

### Environment
Immich v1.91.4 running on TrueNAS SCALE 22.10
Will try to reproduce with Immich 1.92

### The OS that Immich Server is running on

TrueNAS SCALE Cobia

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A using Helm Chart from TrueNAS
```

### Your .env content

```Shell
N/A using Helm Chart from TrueNAS. No personalized env.
```

### Reproduction steps

```bash
1. login with the new user
2. at the prompt to change the password for first connection, navigate back to the login page
3. login as the admin
Result: I am now logged in as the new user instead of the admin
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alextran1502**
Fixes #6275

### CODE REVIEW

**Review by danieldietzler — APPROVED** [review]

File: web/src/routes/auth/login/+page.svelte [hunk 1]
```diff
@@ -1,12 +1,21 @@
...
+  import { api } from '@api';
   import type { PageData } from './$types';
 
   export let data: PageData;
+
+  afterNavigate(async ({ from }) => {
+    if (from?.url.pathname === AppRoute.AUTH_CHANGE_PASSWORD) {
+      resetSavedUser();
+      await api.authenticationApi.logout();
+    }
```
Comment (danieldietzler) [inline web/src/routes/auth/login/+page.svelte:17]: TBF this should probably be done during the change password process, no? It feels a bit weird to handle it here

Comment (alextran1502) [reply web/src/routes/auth/login/+page.svelte:17]: It is here to handle the case where the user navigate back, using the back button on the browser before changing the password

Comment (danieldietzler) [reply web/src/routes/auth/login/+page.svelte:17]: Oh *before* changing the actual password... I see
