### PR TITLE
fix(mobile): cancel share download when dialog is dismissed

### LINKED ISSUE #22353: Cannot interrupt sharing
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When sharing an image or video that is not currently on the device you can get a (depending on the file size) quite long loading time. 

Current Behavior:
When i then try to interrupt this by swiping back (android), the loading screen vanishes an i can use my device but the app does not seem to stop the download process. Instead when the file has finished downloading the sharing dialog appears. When I started the sharing multiple times, and interrupted these sharing attempts with the android back gesture, the sharing dialog will also appear multiple times as soon as the file is downloaded.

Expected Behavior:
When interrupting the sharing process, the file download should be terminated. In addition there could be a button the hide the loading screen if one wishes to continue the download in the background.

Steps to reproduce:

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.143.1

### Version of Immich Mobile App

v1.143.0 build.3016

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Device make and model

Pixel 9 Pro

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

1. Select or open an Image or Video that is only saved on the server but not on the device itself
2. Click on the share button -> a loading screen appears
3. Use the android back button or swipe back gesture to close the loading screen
4. Wait until the download is secretly completed in the backgroud

### Relevant log output

```shell

```

### Additional information

Thanks for your great work!

### PR DESCRIPTION
**Pull request by cmdPromptCritical**
## Description

This PR fixes a bug where interrupting the share process (e.g., by pressing the Android back button or using the back gesture during the "Preparing" stage) would not stop the asset download. This caused the system share sheet to pop up unexpectedly later once the download finished, even if the user had moved on from that intent.

Changes made:
- Added a CancellationToken into the sharing flow to allow for explicit termination.
- Updated AssetMediaRepository.shareAssets to check the cancellation status within the download loop and before triggering the system share sheet.
- Immediate cleanup of temporary files if the operation is cancelled.
- updated ShareActionButton to prevent a "Bad state: Cannot use 'ref' after the widget was disposed" crash by checking context.mounted and the cancellation status before accessing the Provider reference.

Fixes #22353 

## How Has This Been Tested?

- [x] Test A (Cancellation): Initiated a share for a large remote video. Pressed the back button during the "Preparing" dialog. Verified that the dialog disappeared and the system share sheet did not appear later.
- [x] Test B (Normal Share): Initiated a share and waited for the download to complete. Verified that the system share sheet appeared correctly with the file.

<details><summary><h2>Screenshots (if appropriate)</h2></summary>

</details>

## Checklist:

-   [x]  I have performed a self-review of my own code
-   [x]  I have made corresponding changes to the documentation if applicable
-   [x]  I have no unrelated changes in the PR.
-   [x]  I have confirmed that any new dependencies are strictly necessary.
-   [ ]  I have written tests for new code (if applicable)
-   [x]  I have followed naming conventions/patterns in the surrounding code
-   [x] All code in `src/services/` uses repositories implementations for database calls, filesystem operations, etc.
-   [x] All code in `src/repositories/` is pretty basic/simple and does not have any immich specific logic (that belongs in `src/services/`)

## Please describe to which degree, if any, an LLM was used in creating this pull request.
- I used it to query the app structure and provide suggested solution strategies
- Used it to help debug error messages while implementing the solution

...

### CODE REVIEW

File: mobile/lib/repositories/asset_media.repository.dart [hunk 1]
```diff
@@ -102,11 +103,23 @@ class AssetMediaRepository {
...
     for (var asset in assets) {
+      if (cancelToken != null && cancelToken.isCancelled) {
+        // if cancelled, delete any temp files created so far
+        for (var file in tempFiles) {
+          try {
+            await file.delete();
+          } catch (e) {
+            _log.warning("Failed to delete temporary file: ${file.path}", e);
+          }
+        }
```
Comment (shenlong-tanwen) [inline mobile/lib/repositories/asset_media.repository.dart]: This logic is duplicated thrice in the same file. Can you refactor this? We can also probably not await them sequentially and clean them up in parallel

Comment (cmdPromptCritical) [reply mobile/lib/repositories/asset_media.repository.dart]: Let me know if the new commit is what you had in mind!

Comment (shenlong-tanwen) [reply mobile/lib/repositories/asset_media.repository.dart]: Yeah this looks good, Thanks!

File: mobile/lib/presentation/widgets/action_buttons/share_action_button.widget.dart [hunk 2]
```diff
@@ -41,16 +42,20 @@ class ShareActionButton extends ConsumerWidget {
       return;
     }
 
+    final cancelToken = CancellationToken();
```
Comment (shenlong-tanwen) [inline mobile/lib/presentation/widgets/action_buttons/share_action_button.widget.dart]: Can we use a `Completer` instead of a `CancellationToken`? A completer is standard dart and the [AbortableRequest](https://pub.dev/documentation/http/latest/http/AbortableRequest-class.html) from the sdk uses a completer for signalling cancellations as well

Comment (cmdPromptCritical) [reply mobile/lib/presentation/widgets/action_buttons/share_action_button.widget.dart]: Thanks for the context, refactored to use a Completer.

**Review by shenlong-tanwen — APPROVED** [review]
