### PR TITLE
fix(mobile): blurry memory photos

### LINKED ISSUE #6423: [BUG] Android app memories are showing in low resolution
### The bug

In latest android mobile app 1.92.0 is something wrong with memories, they are showing in low resolution (blurred):

IMG_20240116_114614

I downgraded an app to 1.91.4 and memories looks fine: 

IMG_20240116_114325

I also tried to upgrade to 1.92.0 again, tried clean install, the problem is back. 

### The OS that Immich Server is running on

Debian 11

### Version of Immich Server

1.92.1

### Version of Immich Mobile App

1.92.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
---
version: "3.8"
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /Disk2/Media/Photo:/Disk2/Media/Photo:ro
    env_file:
      - immich.env
    ports:
      - 2283:3001    
    depends_on:
      - redis
      - database
    restart: always
  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    #command: [ "start.sh", "microservices" ]    
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /Disk2/Media/Photo:/Disk2/Media/Photo:ro      
    env_file:
      - immich.env
    depends_on:
      - redis
      - database
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - immich.env
    restart: always
  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always
  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - immich.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
###################################################################################
  # Database
  ###################################################################################

  DB_HOSTNAME=immich_postgres
  DB_USERNAME=postgres
  DB_PASSWORD=<password>
  DB_DATABASE_NAME=immich

  # Optional Database settings:
  # DB_PORT=5432

  ###################################################################################
  # Redis
  ###################################################################################

  REDIS_HOSTNAME=immich_redis

  ###################################################################################
  # Upload File Location
  #
  # This is the location where uploaded files are stored.
  ###################################################################################

  UPLOAD_LOCATION=/Disk2/Config/immich/upload
```

### Reproduction steps

```bash
1. Upgrade to 1.92.0 android app
2. Open any of memories
```

### Additional information

Phone details: Android 11, MIUI 12.5.7

This is only app issue, don't see the problem with web version on phone, nor on computer.

### PR DESCRIPTION
**Pull request by alextran1502**
Fixes #6423

### CODE REVIEW

File: mobile/lib/shared/ui/immich_image.dart [hunk 1]
```diff
@@ -49,7 +49,7 @@ class ImmichImage extends StatelessWidget {
     final Asset asset = this.asset!;
     if (useLocal(asset)) {
       return Image(
-        image: localThumbnailProvider(asset),
+        image: localThumbnailProvider(asset, dimension: 2048),
```
Comment (martyfuhry) [inline mobile/lib/shared/ui/immich_image.dart:52]: This should probably fix it. I think I'll make it a point to create a new `localImageProvider` which doesn't need a dimension, and just uses the full asset. Because using the thumbnail provider to show the full image feels a bit dirty.

**Review by martyfuhry — COMMENTED** [review]
I'm testing this now on my wife's phone!

**Comment by martyfuhry** [comment]
I can confirm that this fixes the issue! Great work, Alex!

I can refactor this later to use a non-thumbnail image provider, or else you can do it in this PR. Just copy / paste the thumbnail image provider and use it in place. Don't specify a `thumbnailSize` and it'll use the full image, I think?

In any case, I'll approve this, so merge it or add my suggestion as you like!

**Comment by martyfuhry** [comment]
Huh, weird. I can't approve the PR.

**Review by shenlong-tanwen — APPROVED** [review]

**Comment by alextran1502** [comment]
@martyfuhry @shenlong-tanwen, My previous attempt caused a performance drop while browsing the timeline since it gets a large thumbnail size. So I refactored it to use the previous size 250px by default unless we pass in the `preferredLocalAssetSize` to modify that
