### PR TITLE
fix: tag clean up query and add tests

### LINKED ISSUE #19618: Tag cleanup not working
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I used this feature a lot but some versions ago it stopped working. Maybe I'm doing something work but I remember the job used to delete tags that are not being used by any media and it was wonderful since I'm experimenting with tags but not they stay even if they are not attached to any media. Even with a clean install it doesn't work. I'm missing something or does it just not work?

### The OS that Immich Server is running on

Docker composer

### Version of Immich Server

v1.135.3

### Version of Immich Mobile App

any

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
default
```

### Your .env content

```Shell
default
```

### Reproduction steps

1. Go to jobs
2. Create job
3. Clean up tags
4. Nothing happens

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MontejoJorge**
## Description

Add medium tests for the handleTagCleanup job, and updates the unworking query.

As @jrasm91 suggested in #19618 i added some tests for the tag cleanup job.

Fixes #19618

## How Has This Been Tested?

- [x] A single tag exists, not connected to any assets, and is deleted
- [x] A single tag exists, connected to one asset, and is not deleted
- [x] A hierarchical tag exists, and the parent is connected to an asset, and the child is deleted
- [x] A hierarchical tag exists, and only the child is connected to an asset, and nothing is deleted

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation if applicable
- [x] I have no unrelated changes in the PR.
- [x] I have confirmed that any new dependencies are strictly necessary.
- [x] I have written tests for new code (if applicable)
- [x] I have followed naming conventions/patterns in the surrounding code
- [x] All code in `src/services/` uses repositories implementations for database calls, filesystem operations, etc.
- [x] All code in `src/repositories/` is pretty basic/simple and does not have any immich specific logic (that belongs in `src/services/`)

## Please describe to which degree, if any, an LLM was used in creating this pull request.
None
...

### CODE REVIEW

File: server/src/repositories/tag.repository.ts [hunk 1]
```diff
@@ -163,21 +163,27 @@ export class TagRepository {
...
+        .where('id', 'not in', (eb) =>
+          eb
+            .selectFrom('tag as child')
+            .select('child.parentId')
+            .where('child.parentId', 'is not', null)
+            .where((eb2) =>
+              eb2.or([
+                eb2('child.id', 'in', (eb3) => eb3.selectFrom('tag_asset').select('tagsId')),
+                eb2('child.id', 'not in', (eb3) => eb3.selectFrom('tag_asset').select('tagsId')),
+              ]),
```
Comment (danieldietzler) [inline server/src/repositories/tag.repository.ts]:
```suggestion
            .where((eb) =>
              eb.or([
                eb('child.id', 'in', (eb) => eb.selectFrom('tag_asset').select('tagsId')),
                eb('child.id', 'not in', (eb) => eb.selectFrom('tag_asset').select('tagsId')),
              ]),
```

Scoping will do its job here

File: server/src/repositories/tag.repository.ts [hunk 2]
```diff
@@ -163,21 +163,27 @@ export class TagRepository {
   }
 
   async deleteEmptyTags() {
-    // TODO rewrite as a single statement
     await this.db.transaction().execute(async (tx) => {
```
Comment (danieldietzler) [inline server/src/repositories/tag.repository.ts]: You don't need the transaction anymore since this is now a single query

**Comment by danieldietzler** [comment]
@MontejoJorge you removed the LLM part from the PR description; why?

**Comment by danieldietzler** [comment]
Also, please rebase and fix failing tests. Thanks!

**Comment by MontejoJorge** [comment]
> @MontejoJorge you removed the LLM part from the PR description; why?

Because I didnt use, so i deleted it as i did with the screenshot part, i'll put it again.

File: server/src/repositories/tag.repository.ts (hunk 1 above)
Comment (MontejoJorge) [reply server/src/repositories/tag.repository.ts]: sure, I did it bc i think it would be easier to understand it

**Review by mertalev — APPROVED** [review]
