### PR TITLE
fix(web): file uploading error in album page

### LINKED ISSUE #387: [BUG] Uploading from album not always working
**Describe the bug**
When uploading new assets directly from an album, the pictures won't be added to the album if even a single one failed to upload (unsupported format, corrupted, ...).

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [X] I have read thoroughly the README setup and installation instructions.
- [X] I have included my `docker-compose` file.
- [X] I have included my redacted `.env` file.
- [X] I have included information on my machine, and environment.

**To Reproduce**
1. Create or open an album
2. Click add photos > Select from computer
3. Upload a bunch of photos including an unsupported or corrupted one
4. Notice the page not refreshing after the upload finished

**Expected behavior**
Whether or not some failed to upload, the others should be added to the album. A message popup mentioning some failure would be a nice addition.

**System**
- Server Version: `v1.19.0`

**Additional context**
Strictly web only issue

[docker-compose.txt](https://github.com/alextran1502/immich/files/9204124/docker-compose.txt)
[env.txt](https://github.com/alextran1502/immich/files/9204127/env.txt)

### PR DESCRIPTION
**Pull request by panoti**

### CODE REVIEW

File: web/src/lib/components/album-page/asset-selection.svelte [hunk 1]
```diff
@@ -44,12 +44,15 @@
 		if (uploadAssets.length == uploadAssetsCount) {
 			// Filter assets that are already in the album
 			const assetsToAdd = uploadAssets.filter(
-				(asset) => !assetsInAlbum.some((a) => a.id === asset)
+				(asset) => !!asset && !assetsInAlbum.some((a) => a.id === asset)
```
Comment (alextran1502) [inline web/src/lib/components/album-page/asset-selection.svelte:47]: Why do we have this change?

Comment (panoti) [reply web/src/lib/components/album-page/asset-selection.svelte:47]: if upload progress fail, null asset id will be return in this case, so we need filter null asset from list. If not return null, we can add the rest to album because of `if (uploadAssets.length == uploadAssetsCount)` line. I don't wanna change `if (uploadAssets.length == uploadAssetsCount)` so I decide to filter null.
