### PR TITLE
fix(web): broken asset urls if shared link has photos in name

### LINKED ISSUE #23526: Invalid URL in public photo album
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hi there,

I've been recently playing my Immich to publicly share photo albums. I noticed an annoying bug when publicly sharing photo albums:

Say I created a public link to my photo albums, https://my.immich.instance/s/my-awesome-album. The album link works. However, all individual image links are https://my.immich.instance/s/photos/5a361a20-ff48-4d72-9924-0ea85ab9f5e9 (which doesn't work) instead of https://my.immich.instance/s/my-awesome-album/5a361a20-ff48-4d72-9924-0ea85ab9f5e9 (the album name gets reset to 'photos' instead of the custom album name I specified).

For some reason, the issue doesn't occur when logged in.

### The OS that Immich Server is running on

Fedora 43

### Version of Immich Server

v2.2.1

### Version of Immich Mobile App

n/a

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Device make and model

_No response_

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://docs.immich.app/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://docs.immich.app/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://docs.immich.app/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=CENSORED

# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Create an album
2. Create a public share link with a custom name (eg. 'my-awesome-album')
3. Make sure you are not logged into Immich
4. Visit the public link
5. Click on any picture
6. Get 404'd because the picture link is invalid (URL points to '/s/photos/{GUID}' instead of '/s/my-awesome-album/{GUID}').

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by YarosMallorca**
## Description

Fixes #23526

## How Has This Been Tested?

- [x] Create an album
- [x] Share it with a custom URL which contains "photos" in the name
- [x] Click on any asset, it loads

## Please describe to which degree, if any, an LLM was used in creating this pull request.
AI was used to correct the Regex.

### CODE REVIEW

File: web/src/lib/utils/navigation.ts [hunk 1]
```diff
@@ -47,7 +47,7 @@ export function currentUrlReplaceAssetId(assetId: string) {
   // off / instead of a subpath, unlike every other asset-containing route.
   return isPhotosRoute($page.route.id)
     ? `${AppRoute.PHOTOS}/${assetId}${searchparams}`
-    : `${$page.url.pathname.replace(/(\/photos.*)$/, '')}/photos/${assetId}${searchparams}`;
+    : `${$page.url.pathname.replace(/\/photos\/[^/]+$/, '')}/photos/${assetId}${searchparams}`;
```
Comment (danieldietzler) [inline web/src/lib/utils/navigation.ts:50]: I am not sure if we want `[^/]+` or `.*`. Currently this only catches exactly one case though where there isn't a deeper path so it is probably fine

**Review by danieldietzler — APPROVED** [review]
