### PR TITLE
fix(web): cannot view image when metadata sharing is turned off for public sharing

### LINKED ISSUE #10130: bug(web): Viewer crashes when shared link metadata is off
### The bug

`Uncaught (in promise) TypeError: can't access property "lastIndexOf", e is undefined`

### The OS that Immich Server is running on

Fedora 39

### Version of Immich Server

v1.106.1

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. create individual share with metada turned off
2. access that shared link
3. click to photo
4. viewer crashes
```

### Relevant log output

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alextran1502**
Not the cleanest fix, open for suggestion

fix #10130

### CODE REVIEW

File: web/src/lib/utils/asset-utils.ts [hunk 1]
```diff
@@ -263,6 +263,11 @@ const supportedImageExtensions = new Set(['apng', 'avif', 'gif', 'jpg', 'jpeg',
  * Returns true if the asset is an image supported by web browsers, false otherwise
  */
 export function isWebCompatibleImage(asset: AssetResponseDto): boolean {
+  // originalPath is undefined when public shared link has metadata option turned off
+  if (asset.originalPath === undefined) {
```
Comment (jrasm91) [inline web/src/lib/utils/asset-utils.ts:267]:
```suggestion
  if (!asset.originalPath) {
```

**Review by jrasm91 — APPROVED** [review]

**Review by zackpollard — APPROVED** [review]
