### PR TITLE
fix: backup resume more reliable on app start up

### LINKED ISSUE #20822: [beta] upload does not begin after app startup on android
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After some app startups, the upload process does not being, despite new photos.
The photos are shown in the timeline, hashed and queued for upload, but the upload itself never starts.
The app looks like it is connected to the server im settings - network, but the version numbers don't appear. I guess this is what #20713 fixes, but I can't determine whether this issue is also fixed by that fix.

There is no error in the logs and restarting the app immediately starts and completes the upload, so I am not sure what is missing in the process.
This is all happening in my home wifi where the server is. 

### The OS that Immich Server is running on

PiOS / Debian

### Version of Immich Server

v1.137.3

### Version of Immich Mobile App

v1.137.2 3002

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
Irrelevant
```

### Your .env content

```Shell
Irrelevant
```

### Reproduction steps

1. Take photos on the go with no VPN/home connection 

2. Open app in home wifi

### Relevant log output

```shell
Nothing visible
```

### Additional information

Image
Image
Image
Image
Image
Image

### PR DESCRIPTION
**Pull request by alextran1502**
Fixes https://github.com/immich-app/immich/issues/20822

### CODE REVIEW

File: mobile/lib/utils/migration.dart [hunk 1]
```diff
@@ -223,11 +223,11 @@ class _DeviceAsset {
   const _DeviceAsset({required this.assetId, this.hash, this.dateTime});
 }
 
-Future<void> runNewSync(WidgetRef ref, {bool full = false}) async {
+Future<List<void>> runNewSync(WidgetRef ref, {bool full = false}) async {
   ref.read(backupProvider.notifier).cancelBackup();
```
Comment (shenlong-tanwen) [inline mobile/lib/utils/migration.dart:227]: `await` cancel as well

Comment (alextran1502) [reply mobile/lib/utils/migration.dart:227]: this method isn't an async one

image

**Review by shenlong-tanwen — APPROVED** [review]
