### PR TITLE
fix: oauth

### LINKED ISSUE #17958: OAuth Failing with Entra
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Reported in #17825 but that seems to have been closed. I have had Immich running with OAuth via Entra (Azure AD) for some time with no issues. Since v1.132.0 the login no longer works going into a loop. If I roll the docker image back to the last version before 1.132.0 it works again. The Entra Logs show a successful login so the request is reaching Entra and it is processing it as successful but it seems the Immich server is no longer happy with the response for some reason. 

People report having to change Authelia config to "token_endpoint_auth_method: 'client_secret_post since'" but if it is possible to achieve the same thing in Entra I have not been able to figure it out. 

Happy to assist in any way I can, try Entra changes etc. 

### The OS that Immich Server is running on

Unraid 7.1

### Version of Immich Server

v1.132.3

### Version of Immich Mobile App

v1.132.3 build.197

### Platform with the issue

- [ ] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
Running in Unraid not Docker Compose is if it is possible to get this I'm not sure how
```

### Your .env content

```Shell
Running in Unraid not Docker Compose is if it is possible to get this I'm not sure how
```

### Reproduction steps

1. Setup OAuth with Entra
2. Try to login 
3.
...

### Relevant log output

```shell
[Nest] 681  - 04/29/2025, 8:28:08 AM   DEBUG [Api:LoggingInterceptor~3dtrra0p] GET /api/server/features 200 2.88ms 172.70.91.236
[Nest] 681  - 04/29/2025, 8:28:08 AM   DEBUG [Api:LoggingInterceptor~exlm9pow] GET /api/server/config 200 3.35ms 172.70.91.236
[Nest] 681  - 04/29/2025, 8:28:09 AM   ERROR [Api:ErrorInterceptor~v7now5lj] Unknown error: ResponseBodyError: server responded with an error in the response body
ResponseBodyError: server responded with an error in the response body
    at checkOAuthBodyError (file:///app/immich/server/node_modules/oauth4webapi/build/index.js:865:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async processGenericAccessTokenResponse (file:///app/immich/server/node_modules/oauth4webapi/build/index.js:1141:5)
    at async processAuthorizationCodeOAuth2Response (file:///app/immich/server/node_modules/oauth4webapi/build/index.js:1373:20)
    at async authorizationCodeGrant (file:///app/immich/server/node_modules/openid-client/build/index.js:850:18)
    at async OAuthRepository.getProfile (/app/immich/server/dist/repositories/oauth.repository.js:52:28)
    at async AuthService.callback (/app/immich/server/dist/services/auth.service.js:137:25)
    at async OAuthController.finishOAuth (/app/immich/server/dist/controllers/oauth.controller.js:46:22)
[Nest] 681  - 04/29/2025, 8:28:09 AM   DEBUG [Api:LoggingInterceptor~v7now5lj] POST /api/oauth/callback 201 212.86ms 172.70.91.236
[Nest] 681  - 04/29/2025, 8:28:09 AM VERBOSE [Api:LoggingInterceptor~v7now5lj] {"url":"https://immich.dblabs.co.uk/auth/login?code=1.AQwAOrAk_lhdGk-IDTg6PYoo1S2zfiEnP_xNmMg5xLftJe3dAEYMAA.AgABBAIAAABVrSpeuWamRam2jAF1XRQEAwDs_wUA9P_zgPLr6mNvzqBNA0jO4_TOK5t7wdBvTBTU5ciuC9IfJPT5NP9yXxR9AU77jVM3zAgLtOpRVm8y40IqHrlGIwXlhOJ7VJjwj2oQ5WiZnYaqbbAUunH_HzRh54N53KMx3iZGrpI1I8F-l2PdVnwYbLjbSbHhSlAC6tEH-AwOp6Kt9kMaz3VGNDK4U16lyLCNRspHUQ1vL6dMnd67WzX60nRMJ0Qu9Os2Rx-kvbJfTKmejGu9rRec2VSjxUMuZpJiIcwTY44rpAlNHkcgUFS56cd522qI5l7NIeHDzrygRzYLxBiSXqQ211c4tl6JCKPW5wWQ5hsetncYxD3KzSNcN_bwXfRwfPMGGMyl7LE2XKC8vlj6k7BpTSxNnZSMQIXXlJ5EkjJaIiNfN9Jb8Qsf2jjtCFakaI43_VjYk6uh2De4lJM9TbYGWyEWlXwUNomw3sPpMDfCTKPascVmDY3ZIo4hao1cZyHbG3ca5BXiZpnIua5dBPAopJidrKg-dUAyB_uFlIIFPhq1jeUgWtU-OJr0Hj9W5F-YliL8tcAKPHTOd5lnaThZkeNWEZNkY4Uk6-AJHnK3mwXD1oXDCedGNI9hm-K-p7korOFF24UU5aZV4reaGeT75M5dXDEJhaTZom9hh8qpjBMhUnQaJhyNg9fvCCi6294R2-1tHinO499icE2KRTkwDyZaK2xGm7qXfIfhUWYfeBVsv4Coikyf3cegl3sdSxL4ziodhH8Z3HHYYCb1rS4anaEJswmy8efojVUqomSq9LI9_wN2RFbr4ATvJuwGBYiO9ZqSoGs7--gK_I6TaA22Hlt7UVdeNnJdz396YUHuOJfuYyhukqLMum2j5PWQClI_lfuvZXrtoqSB87s3bH9-8-ci2rdXceD1tkjyP8n19b-k4NOaKw-4tVN23HbbB5iMcZRvYOXdwmN0P5_32Qz3msCdU2m5tIxm3b5zsDsP43VIm8alI0mj0F1NNh0HTLnYOlHDp22QC0_3xlhKcCNKehI_SkwsM71ret51vmMc1i9S9ES1CzpVeNePDoJYnkPd7rR6yoiVD7fY_7vYGILKkyn4HWHGKJnmGe6BiW0lNdTAJSCdhFIActJenA8_YcRDH00Mf4sD0z87NrUl&state=J9TlSf8vBYH-keBZvDgeemceot0IjNSHW80vnQ33fhY&session_state=00417db9-9431-896b-a705-fc8428a72661"}
[Nest] 681  - 04/29/2025, 8:28:09 AM   DEBUG [Api:GlobalExceptionFilter~v7now5lj] HttpException(500): {"message":"Failed to finish oauth","error":"Internal Server Error","statusCode":500}
[Nest] 681  - 04/29/2025, 8:28:09 AM   DEBUG [Api:LoggingInterceptor~173hz6lb] POST /api/oauth/authorize 201 47.04ms 172.70.91.236
[Nest] 681  - 04/29/2025, 8:28:09 AM VERBOSE [Api:LoggingInterceptor~173hz6lb] {"redirectUri":"https://immich.dblabs.co.uk/auth/login"}
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by danieldietzler**
# Problem

Entra supports (and encourages) PKCE. It'll use PKCE iff `code_challenge` and `code_challenge_method` are provided during the authorization [1]. *However*, Entra does not have `code_challenge_methods_supported: ["S256"]` in its .well known openid configuration. 
Thus, `client.serverMetadata().supportsPKCE()`, which checks that field, returns false, assuming the provider does not support PKCE. We used to only check that when getting the profile (https://github.com/immich-app/immich/blob/main/server/src/repositories/oauth.repository.ts#L62) and considered that sufficient. Under the assumption that the OIDC provider wouldn't start a PKCE flow if it's not mentioned in the well known config, this holds. 
With Entra however we're now in a PKCE flow, but don't send the code verifier. That caused Entra to yell that the `code_verifier` is not valid. 

The solution is to never even offer a code challenge, if the provider does not explicitly state it supports that. In the case of Entra this isn't ideal, because PKCE *is* the preferred and more secure solution, but I honestly don't care if they're too incompetent to serve a correct openid-configuration.

Fixes #17958

[1] https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow#request-an-authorization-code

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]

File: server/src/repositories/oauth.repository.ts [hunk 1]
```diff
@@ -40,8 +40,8 @@ export class OAuthRepository {
       redirect_uri: redirectUrl,
       scope: config.scope,
       state,
-      code_challenge: codeChallenge,
-      code_challenge_method: 'S256',
+      code_challenge: client.serverMetadata().supportsPKCE() ? codeChallenge : '',
+      code_challenge_method: client.serverMetadata().supportsPKCE() ? 'S256' : '',
```
Comment (jrasm91) [inline server/src/repositories/oauth.repository.ts:44]: Is this correct? I would have guessed undefined would be used to omit the property

Comment (danieldietzler) [reply server/src/repositories/oauth.repository.ts:44]: Me too but it's typed as URL query params.
