### PR TITLE
fix(web): remove dependency on rxjs 

### LINKED ISSUE #3300: regression(web): mts files unsupported and uncaught error for unsupported file extensions
### The bug

Attempting to upload a `.mts` video via the web on v1.67.2 does nothing and shows errors in the console.

image

image

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.67.2

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by uhthomas**
The dependency on rxjs has been removed in favour of iterators as it's clearer and the nature of the workload is inherently non-reactive. The uncaught error when the list of files is empty has also been implicitly fixed by this change.

Fixes: https://github.com/immich-app/immich/issues/3300

### CODE REVIEW

File: web/src/lib/utils/file-uploader.ts [hunk 1]
```diff
@@ -122,7 +119,7 @@ async function fileUploader(
       progress: 0,
     });
 
-    const response = await axios.post(`/api/asset/upload`, formData, {
+    const response = await axios.post(`/ api / asset / upload`, formData, {
```
Comment (uhthomas) [inline web/src/lib/utils/file-uploader.ts:122]: wtf

**Review by jrasm91 — APPROVED** [review]
