### PR TITLE
fix(web): face selection box position resetting on browser resize

### LINKED ISSUE #22476: When resizing window while tagging people in a image the selection box moves
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

While tagging a person in a image and a resize happens the selection rectangle jumps to another position.

### The OS that Immich Server is running on

Truenas 25.4.2.1

### Version of Immich Server

v1.143.1

### Version of Immich Mobile App

v1.143.1 build.3017

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Device make and model

_No response_

### Your docker-compose.yml content

```YAML
Truenas apps default
```

### Your .env content

```Shell
Truenas apps default
```

### Reproduction steps

1. Open a image
2. Press "+" to tag a new person
3. Select face
4. Resize window (e.g press f11)

### Relevant log output

```shell

```

### Additional information

Tested in both firefox and ungoogled chromium.

### PR DESCRIPTION
**Pull request by Snowknight26**
## Description
Prevent the face selection box from changing positions when resizing the browser. It'll only reset when it's beyond the bounds of the visible area.

Fixes #22476

## How Has This Been Tested?

- [x] Moved the face selection box to a position within the image, resized the browser
- [x] Moved the face selection box to a position beyond the canvas, resized the browser

<details><summary><h2>Screenshots (if appropriate)</h2></summary>

</details>

## Checklist:

- [x] I have carefully read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if applicable
- [x] I have no unrelated changes in the PR.
- [ ] I have confirmed that any new dependencies are strictly necessary.
- [ ] I have written tests for new code (if applicable)
- [ ] I have followed naming conventions/patterns in the surrounding code
- [ ] All code in `src/services/` uses repositories implementations for database calls, filesystem operations, etc.
- [ ] All code in `src/repositories/` is pretty basic/simple and does not have any immich specific logic (that belongs in `src/services/`)

## Please describe to which degree, if any, an LLM was used in creating this pull request.

None

### CODE REVIEW

**Comment by midzelis** [comment]
Just as an aside, the face bounding boxes are affected and enhanced by #26636

**Comment by Snowknight26** [comment]
> Just as an aside, the face bounding boxes are affected and enhanced by #26636

Thanks! Looks like it'll be a fairly simple merge fix regardless of which PR is merged first.

**Comment by midzelis** [comment]
FYI - that particular change has been split out to a descendent PR: #26777 - and it adds additional functionality. The initial position (200,200) is only set once on initial open - but then, if the viewport resizes (or shrinks due to detail-pane opening) - it will proportionately scale the face bounding box and relative position.

File: web/src/lib/components/asset-viewer/face-editor/face-editor.svelte [hunk 1]
```diff
@@ -104,15 +114,21 @@
...
+    if (!isFaceRectIntersectingCanvas(faceRect, canvas)) {
+      setDefaultFaceRectanglePosition(faceRect);
+    }
   });
 
+  const isFaceRectIntersectingCanvas = (faceRect: Rect, canvas: Canvas) => {
+    const faceBox = faceRect.getBoundingRect();
+    return !(
+      0 > faceBox.left + faceBox.width ||
+      0 > faceBox.top + faceBox.height ||
```
Comment (danieldietzler) [inline web/src/lib/components/asset-viewer/face-editor/face-editor.svelte:132]: What are these cases?

Comment (Snowknight26) [reply web/src/lib/components/asset-viewer/face-editor/face-editor.svelte:132]: If the right edge of the face box (left + width) is left of the canvas.
If the bottom edge of the face box (top + height) is above the canvas.

Comment (danieldietzler) [reply web/src/lib/components/asset-viewer/face-editor/face-editor.svelte:132]: Right. How can that happen though?

Comment (Snowknight26) [reply web/src/lib/components/asset-viewer/face-editor/face-editor.svelte:132]: You can drag the face rectangle beyond the browser window bounds 😆

**Review by danieldietzler — APPROVED** [review]
