### PR TITLE
fix(mobile): handle readonly and offline assets

### LINKED ISSUE #6204: [BUG] Deleting a picture from an external library is possible from the Android App
### The bug

Assets from external library don't show a "trash" button when viewed via the web interface. This makes sense as it is not possible to delete them

However, when browsed via the android application, the trash button is enabled. Pressing it makes the picture disappear from both the android app and the web interface. A "soft" library re-scan makes the picture appear again on the web interface, however it does not on the android app. Doing a "Forced re-scan" is needed in order to have it back on the android app

### The OS that Immich Server is running on

Ubuntu 22.04.3 LTS

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4.build.116

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. have some picture from external library, note that it can't be deleted from web
2. browse this picture from android app, note it can be deleted
3. delete it, see how it dissapears from web as well
4. try soft and forced re-scan
...
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by shenlong-tanwen**
#### Changes made in the PR

- Refactored the filters on `Iterable<Asset>`  to an extension to make it accessible across the app
- Store the fields `isOffline` and `isReadOnly` for remote asssets
- Updated the actions across the app to disable the following based on the above two fields:
    -  Delete & Edit meta is not available for `isReadOnly` assets. This is because all readOnly assets are assumed to be in ro mounts and we'd have no way to write / modify files
    - Share & Download is not available for `isOffline` assets since we cannot access the underlying file

Fixes #6204

### CODE REVIEW

File: mobile/lib/modules/asset_viewer/views/gallery_viewer.dart [hunk 1]
```diff
@@ -332,6 +351,26 @@ class GalleryViewerPage extends HookConsumerWidget {
...
+        ImmichToast.show(
+          durationInSecond: 1,
+          context: context,
+          msg: 'asset_action_share_err_offline'.tr(),
+          gravity: ToastGravity.BOTTOM,
+        );
+        return;
+      }
+
+      ref.watch(imageViewerStateProvider.notifier).downloadAsset(
```
Comment (fyfrey) [inline mobile/lib/modules/asset_viewer/views/gallery_viewer.dart:368]: Sorry for the spam: use read instead of watch in callbacks?

File: mobile/lib/extensions/collection_extensions.dart [hunk 2]
```diff
@@ -39,3 +41,52 @@ extension IntListExtension on Iterable<int> {
     return list;
   }
 }
+
+extension AssetListExtension on Iterable<Asset> {
```
Comment (fyfrey) [inline mobile/lib/extensions/collection_extensions.dart:45]: Great idea!

**Review by fyfrey — COMMENTED** [review]
Good fix for those assets. I think this needs a DB migration (just truncate the tables like the other migrations) to add the new fields to asset with the proper values from the server. Otherwise, users need to perform a manual refresh

File: mobile/lib/modules/asset_viewer/views/gallery_viewer.dart (hunk 1 above)
Comment (shenlong-tanwen) [reply mobile/lib/modules/asset_viewer/views/gallery_viewer.dart:368]: Ah, not a problem 😄 Will update all such instances soon. Thank you!

**Comment by shenlong-tanwen** [comment]
> Good fix for those assets. I think this needs a DB migration (just truncate the tables like the other migrations) to add the new fields to asset with the proper values from the server. Otherwise, users need to perform a manual refresh

Ah, I'll keep in mind to migrate Isar moving forwards on new fields. I've updated the change-set with migration and also updated all the notifier watch calls to read :)

File: mobile/lib/extensions/collection_extensions.dart [hunk 3]
```diff
@@ -39,3 +41,52 @@ extension IntListExtension on Iterable<int> {
...
+  }) {
+    final bool onlyWritable = every((e) => !e.isReadOnly);
+    if (!onlyWritable) {
+      if (errorCallback != null) errorCallback();
+      return where((a) => !a.isReadOnly);
+    }
+    return this;
+  }
+
+  Iterable<Asset> liveOnly({
```
Comment (alextran1502) [inline mobile/lib/extensions/collection_extensions.dart:82]: I assume live here is LivePhotos?

File: mobile/lib/extensions/collection_extensions.dart [hunk 4]
```diff
@@ -39,3 +41,52 @@ extension IntListExtension on Iterable<int> {
...
+    final userId = owner.isarId;
+    final bool onlyOwned = every((e) => e.ownerId == userId);
+    if (!onlyOwned) {
+      if (errorCallback != null) errorCallback();
+      return where((a) => a.ownerId == userId);
+    }
+    return this;
+  }
+
+  Iterable<Asset> writableOnly({
```
Comment (alextran1502) [inline mobile/lib/extensions/collection_extensions.dart:71]: What does indicate that an asset is writeable only? Can we add some comments on these methods for documentation purposes?

Comment (shenlong-tanwen) [reply mobile/lib/extensions/collection_extensions.dart:76]: Done :)

File: mobile/lib/extensions/collection_extensions.dart (hunk 3 above)
Comment (shenlong-tanwen) [reply mobile/lib/extensions/collection_extensions.dart]: It was actually to filter out non offline files, so updated the method name to `nonOfflineOnly` to better indicate the same

**Review by alextran1502 — APPROVED** [review]
