### PR TITLE
fix: asset update race condition

### LINKED ISSUE #16747: [API] tagAssets doesn't tag all assets randomly
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

The API call tagAssets often tags not all assets given in the call.

 

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

I writing test cases for Immich-go, that wipes out the immich's tables, and upload a handful of images, with tag and album. 

May be 1 over 3 test3, immich misses to tag an asset.
The API call return show a success for all tagged assets

### Relevant log output

```shell
immich_server  | [95m[Nest] 17  - [39m03/09/2025, 1:17:28 PM [95m  DEBUG[39m [33m[Api:LoggingInterceptor~9bcb8x7p][39m [95mPUT /api/tags/bececdd5-bb46-4201-8551-a0300809c12c/assets 200 27.63ms ::ffff:172.18.0.1[39m
immich_server  | [96m[Nest] 17  - [39m03/09/2025, 1:17:28 PM [96mVERBOSE[39m [33m[Api:LoggingInterceptor~9bcb8x7p][39m [96m{"ids":["44891c00-8964-4882-a921-70c781d4a89a","bdfe3e04-9c24-4ada-8bac-69952f38a283","19182cda-f568-4c74-ade4-7b3a53a2a602","c9f9e3ce-3054-480b-85eb-f718e21401ea","807af51b-e29f-4db0-951c-904c57e8441d"]}[39m
```

### Additional information

Immich-go api trace:
```
025-03-09T14:17:28+01:00 QUERY 13 UpsertTags PUT http://localhost:2283/api/tags
   Content-Type [application/json]
   Accept [application/json]
   X-Api-Key redacted
-- body start --
{"tags":["tag/subtag"]}
-- body end --

2025-03-09T14:17:28+01:00 RESPONSE 13 UpsertTags PUT http://localhost:2283/api/tags
  Header:
     Date : Sun, 09 Mar 2025 13:17:28 GMT
     Connection : keep-alive
     Keep-Alive : timeout=5
     X-Powered-By : Express
     X-Immich-Cid : rtoee2rp
     Content-Type : application/json; charset=utf-8
     Content-Length : 212
     Etag : "d4-WX1a0e5OR3gUbCjRKZNhnbYtz24"
  Status: 200 OK
-- response body start --
[{"id":"bececdd5-bb46-4201-8551-a0300809c12c","parentId":"a4af078e-4993-4aef-b774-49dd3ee08cc2","name":"subtag","value":"tag/subtag","createdAt":"2025-03-09T13:17:28.192Z","updatedAt":"2025-03-09T13:17:28.192Z"}]
-- response body end --

2025-03-09T14:17:28+01:00 QUERY 14 TagAssets PUT http://localhost:2283/api/tags/bececdd5-bb46-4201-8551-a0300809c12c/assets
   X-Api-Key redacted
   Content-Type [application/json]
   Accept [application/json]
-- body start --
{"ids":["44891c00-8964-4882-a921-70c781d4a89a","bdfe3e04-9c24-4ada-8bac-69952f38a283","19182cda-f568-4c74-ade4-7b3a53a2a602","c9f9e3ce-3054-480b-85eb-f718e21401ea","807af51b-e29f-4db0-951c-904c57e8441d"]}
-- body end --

2025-03-09T14:17:28+01:00 RESPONSE 14 TagAssets PUT http://localhost:2283/api/tags/bececdd5-bb46-4201-8551-a0300809c12c/assets
  Header:
     Keep-Alive : timeout=5
     X-Powered-By : Express
     X-Immich-Cid : 9bcb8x7p
     Content-Type : application/json; charset=utf-8
     Content-Length : 306
     Etag : "132-Nm/wGpjeBvL9J1m/yBxBNA+kiHY"
     Date : Sun, 09 Mar 2025 13:17:28 GMT
     Connection : keep-alive
  Status: 200 OK
-- response body start --
[{"id":"44891c00-8964-4882-a921-70c781d4a89a","success":true},{"id":"bdfe3e04-9c24-4ada-8bac-69952f38a283","success":true},{"id":"19182cda-f568-4c74-ade4-7b3a53a2a602","success":true},{"id":"c9f9e3ce-3054-480b-85eb-f718e21401ea","success":true},{"id":"807af51b-e29f-4db0-951c-904c57e8441d","success":true}]
-- response body end --
```

The table tag_asset content:
```
"assetsId"	"tagsId"
"807af51b-e29f-4db0-951c-904c57e8441d"	"bececdd5-bb46-4201-8551-a0300809c12c"
"44891c00-8964-4882-a921-70c781d4a89a"	"bececdd5-bb46-4201-8551-a0300809c12c"
"bdfe3e04-9c24-4ada-8bac-69952f38a283"	"bececdd5-bb46-4201-8551-a0300809c12c"
"c9f9e3ce-3054-480b-85eb-f718e21401ea"	"bececdd5-bb46-4201-8551-a0300809c12c"
```

full logs attached

[log.log](https://github.com/user-attachments/files/19149904/log.log)

[immich-go_2025-03-09_14-17-27.trace.log](https://github.com/user-attachments/files/19149909/immich-go_2025-03-09_14-17-27.trace.log)

### PR DESCRIPTION
**Pull request by danieldietzler**
For quite some time there has been a race condition in the Immich code affecting asset updates. If assets were updated quickly after, or while, metadata extraction was running, the update could've been persisted to the database, but immediately reverted by the metadata extraction job. 
This particularly affected third party tools which might infer a time from the file name, read metadata from a Google Takeout, or similar. These tools may update the asset just after they uploaded it, reliably triggering this race condition. To make matters worse, the likelihood of triggering this race condition got larger with a full queue, i.e., during an initial ingest.

To work around this, 3rd party tools started to pause all queues during upload, later unpausing them in a particular order to ensure everything is written and safely stored. 

*Finally*, we managed to solve this race condition. Asset updates can now be sent to the server whenever. If the server returns with a positive response it is now guaranteed that the updates are safely stored and won't get overridden again, independent of whatever else is currently going on. 

---

This PR introduces a new `lockedProperties` column on the asset-exif table. It's an array of asset-exif column names which indicates the columns that have been edited in any way through Immich. These won't get overridden by another metadata extraction run. Furthermore, only columns in `lockedProperties` will get written back to the sidecar file.

Fixes #16747

### CODE REVIEW

File: server/src/repositories/asset.repository.ts [hunk 1]
```diff
@@ -117,59 +117,89 @@ interface GetByIdsRelations {
...
+    await this.db.transaction().execute(async (tx) => {
+      const { lockedProperties } = await tx
+        .selectFrom('asset_exif')
+        .select('asset_exif.lockedProperties')
+        .where('asset_exif.assetId', '=', exif.assetId)
+        .executeTakeFirstOrThrow();
+
+      const value = { ...exif, assetId: asUuid(exif.assetId) };
+      const getConflictRef = <T extends string>(columnName: T) =>
+        `${option === 'skip-locked' && lockedProperties?.includes(columnName as any) ? 'asset_exif.' : 'excluded.'}${columnName}` as const;
```
Comment (danieldietzler) [inline server/src/repositories/asset.repository.ts]: This is also a bit annoying. I think it might make things nicer to just split up the upsert into an insert, and an update. The update could then only update the columns we're interested in (filtering out locked columns if necessary)

File: server/src/repositories/asset.repository.ts [hunk 2]
```diff
@@ -117,49 +117,66 @@ interface GetByIdsRelations {
...
-            },
-            value,
+  async upsertExif(exif: Insertable<AssetExifTable>, option: 'update-locked' | 'skip-locked'): Promise<void> {
+    await this.db.transaction().execute(async (tx) => {
+      const lockedProperties = await tx
+        .selectFrom('asset_exif')
+        .select('asset_exif.lockedProperties')
+        .where('asset_exif.assetId', '=', exif.assetId)
+        .executeTakeFirst()
+        .then((result) => result?.lockedProperties);
```
Comment (danieldietzler) [inline server/src/repositories/asset.repository.ts]: Instead of having this inside a transaction, I'd love to do it all in one query. I couldn't figure out how to do that though, and I'm not even sure it's possible

File: server/src/repositories/asset.repository.ts (hunk 1 above)
Comment (jrasm91) [reply server/src/repositories/asset.repository.ts]: Why don't you just remove the locked properties from the `value`? If there are locked properties, you know an exif record already exists.

File: server/src/schema/tables/asset-exif.table.ts [hunk 3]
```diff
@@ -97,4 +99,7 @@ export class AssetExifTable {
 
   @UpdateIdColumn({ index: true })
   updateId!: Generated<string>;
+
+  @Column({ type: 'character varying', array: true, default: [] })
+  lockedProperties!: Array<LockableProperties> | null;
```
Comment (jrasm91) [inline server/src/schema/tables/asset-exif.table.ts]: This isn't a nullable field. You should just `Generated<LockableProperties[]>` though.

File: server/src/repositories/asset.repository.ts [hunk 4]
```diff
@@ -117,49 +117,66 @@ interface GetByIdsRelations {
...
-              iso: eb.ref('excluded.iso'),
-              exposureTime: eb.ref('excluded.exposureTime'),
-              profileDescription: eb.ref('excluded.profileDescription'),
-              colorspace: eb.ref('excluded.colorspace'),
-              bitsPerSample: eb.ref('excluded.bitsPerSample'),
-              rating: eb.ref('excluded.rating'),
-              fps: eb.ref('excluded.fps'),
-            },
-            value,
+  async upsertExif(exif: Insertable<AssetExifTable>, option: 'update-locked' | 'skip-locked'): Promise<void> {
```
Comment (jrasm91) [inline server/src/repositories/asset.repository.ts]: Can we change this interface to use an options object instead? I think something like `options: { lockedPropertyBehavior: 'skip' | 'update' }` would look better.

**Review by jrasm91 — COMMENTED** [review]
Looks really good!

File: server/src/schema/tables/asset-exif.table.ts (hunk 3 above)
Comment (mertalev) [reply server/src/schema/tables/asset-exif.table.ts]: Nullable would be better than an empty array. It's better for the query planner and takes less space (1 byte vs 20).

Comment (danieldietzler) [reply server/src/schema/tables/asset-exif.table.ts]: Empty array is much more convenient though. Do you think that's actually a difference that matters? It's like 1MB vs 20MB for 1 million exif rows. Idk if that makes the difference 😅

Comment (danieldietzler) [reply server/src/schema/tables/asset-exif.table.ts]: Alright I'll go with nullable

**Review by jrasm91 — APPROVED** [review]
Looks good. I think with some medium tests this is ready to merge.

File: server/src/repositories/asset.repository.ts [hunk 5]
```diff
@@ -113,51 +113,84 @@ interface GetByIdsRelations {
...
+  async upsertExif(
+    exif: Insertable<AssetExifTable>,
+    { lockedPropertiesBehavior }: { lockedPropertiesBehavior: 'none' | 'update' | 'skip' },
+  ): Promise<void> {
+    const values = {
+      ...exif,
+    };
+
+    if (lockedPropertiesBehavior !== 'none') {
+      delete values.lockedProperties;
```
Comment (mertalev) [inline server/src/repositories/asset.repository.ts]: Set it null instead.

File: server/src/repositories/asset.repository.ts [hunk 6]
```diff
@@ -113,51 +113,84 @@ interface GetByIdsRelations {
...
+    }
+
+    if (lockedPropertiesBehavior === 'update') {
+      values.lockedProperties = lockableProperties.filter((property) => Object.keys(exif).includes(property));
```
Comment (mertalev) [inline server/src/repositories/asset.repository.ts]: Use `property in exif` instead of `Object.keys(exif).include(property)`

File: server/src/repositories/asset.repository.ts [hunk 7]
```diff
@@ -113,51 +113,84 @@ interface GetByIdsRelations {
...
+                iso: ref('iso'),
+                exposureTime: ref('exposureTime'),
+                profileDescription: ref('profileDescription'),
+                colorspace: ref('colorspace'),
+                bitsPerSample: ref('bitsPerSample'),
+                rating: ref('rating'),
+                fps: ref('fps'),
+                lockedProperties:
+                  lockedPropertiesBehavior === 'update'
+                    ? distinctLocked(eb, values.lockedProperties ?? [])
```
Comment (mertalev) [inline server/src/repositories/asset.repository.ts]: If the type includes undefined, you can coalesce to null instead.

File: server/src/repositories/asset.repository.ts [hunk 8]
```diff
@@ -113,51 +113,84 @@ interface GetByIdsRelations {
...
-  async upsertExif(exif: Insertable<AssetExifTable>): Promise<void> {
-    const value = { ...exif, assetId: asUuid(exif.assetId) };
+  @GenerateSql({ params: [{ dateTimeOriginal: DummyValue.DATE }, { lockedPropertiesBehavior: 'update' }] })
+  async upsertExif(
+    exif: Insertable<AssetExifTable>,
+    { lockedPropertiesBehavior }: { lockedPropertiesBehavior: 'none' | 'update' | 'skip' },
+  ): Promise<void> {
+    const values = {
+      ...exif,
+    };
```
Comment (mertalev) [inline server/src/repositories/asset.repository.ts]: Depending on how/where upsertExif is used, it might be better to have the service decide how to handle lockedProperties and avoid the cloning and logic here. It's also a bit weird to pass one thing into upsertExif and have something else actually inserted based on other configuration.

File: server/src/services/asset.service.ts [hunk 9]
```diff
@@ -456,12 +426,25 @@ export class AssetService extends BaseService {
...
     const { id, description, dateTimeOriginal, latitude, longitude, rating } = dto;
     const writes = _.omitBy({ description, dateTimeOriginal, latitude, longitude, rating }, _.isUndefined);
     if (Object.keys(writes).length > 0) {
-      await this.assetRepository.upsertExif({ assetId: id, ...writes });
-      await this.jobRepository.queue({ name: JobName.SidecarWrite, data: { id, ...writes } });
+      await this.assetRepository.upsertExif(
+        {
+          assetId: id,
+          ...writes,
+        },
```
Comment (mertalev) [inline server/src/services/asset.service.ts]: Maybe it's better to have separate parameters for assetId and the other properties.

File: server/src/repositories/asset.repository.ts (hunk 5 above)
Comment (danieldietzler) [reply server/src/repositories/asset.repository.ts]: Wouldn't that have a different behavior? I don't want it to update the column at all if it's `skip`, whatever the user may pass in

File: server/src/repositories/asset.repository.ts (hunk 8 above)
Comment (danieldietzler) [reply server/src/repositories/asset.repository.ts]: I can see that. The idea of this is that the locked part is kind of transparent/implicit to the user without needing to calculate the same thing in multiple places. Like this we avoid some user forgetting to update the column accordingly, since it will always happen

File: server/src/services/asset.service.ts (hunk 9 above)
Comment (danieldietzler) [reply server/src/services/asset.service.ts]: Possibly. That seems unrelated to this PR though

File: server/src/repositories/asset.repository.ts (hunk 8 above)
Comment (mertalev) [reply server/src/repositories/asset.repository.ts]: Sure, but skip vs update vs none is confusing and I have to look at the source code to understand what it actually means. These are three different behaviors to clone and then modify the object from the caller. I think it'd be better if the caller just passes what it means to pass and the repository respects it.

File: server/src/repositories/asset.repository.ts (hunk 5 above)
Comment (mertalev) [reply server/src/repositories/asset.repository.ts]: I was looking at the `distinctLocked` case, but you're right that it changes the behavior for `skip`. I recently learned that `delete` is very bad for JIT so I try to avoid it - `= undefined` is better

File: server/src/services/asset.service.ts (hunk 9 above)
Comment (mertalev) [reply server/src/services/asset.service.ts]: True, I mentioned it since you're already changing the signature

File: server/src/repositories/asset.repository.ts (hunk 8 above)
Comment (danieldietzler) [reply server/src/repositories/asset.repository.ts]: I moved the `lockedProperties: lockableColumns.filter(...)` part out of the repository. I think everything else needs to happen inside the repository though, since it all needs to be in one query

Comment (mertalev) [reply server/src/repositories/asset.repository.ts]: Does `skip` need to exist? All it does is remove `lockedProperties` from the input, right?

Comment (danieldietzler) [reply server/src/repositories/asset.repository.ts]: It does not update columns in `lockedProperties` (the ref in l.146). If we moved this outside we'd have to fetch the lockedProperties somewhere else, which would mean it's not atomic anymore and there's still a theoretical race condition

File: server/src/utils/database.ts [hunk 10]
```diff
@@ -488,3 +489,8 @@ export function vectorIndexQuery({ vectorExtension, table, indexName, lists }: V
     }
   }
 }
+
+export const updateLockedColumns = <T extends Record<string, unknown>>(exif: T) => ({
+  ...exif,
+  lockedProperties: lockableProperties.filter((property) => property in exif),
+});
```
Comment (mertalev) [inline server/src/utils/database.ts]: Can you just assign instead of spreading? 😅 This object is never used after the upsert and it somehow gets spread at least 3 times by the time the update happens.

File: server/src/repositories/asset.repository.ts (hunk 8 above)
Comment (mertalev) [reply server/src/repositories/asset.repository.ts]: Oh, my mind went to "skip" as in "skip updating `lockedProperties`"

**Review by mertalev — APPROVED** [review]

File: server/src/services/metadata.service.ts [hunk 11]
```diff
@@ -393,22 +393,34 @@ export class MetadataService extends BaseService {
...
+      },
+      lockedProperties,
+    );
+
     const exif = _.omitBy(
       <Tags>{
         Description: description,
         ImageDescription: description,
-        DateTimeOriginal: dateTimeOriginal,
+        DateTimeOriginal: dateTimeOriginal == null ? undefined : String(dateTimeOriginal),
```
Comment (jrasm91) [inline server/src/services/metadata.service.ts]: should this be `===`?

**Review by jrasm91 — APPROVED** [review]

File: server/src/services/metadata.service.ts (hunk 11 above)
Comment (danieldietzler) [reply server/src/services/metadata.service.ts]: No, since I want this to apply for both `null` and `undefined`

Comment (jrasm91) [reply server/src/services/metadata.service.ts]: Then why not just use `dateTimeOriginal ? ...`

Comment (danieldietzler) [reply server/src/services/metadata.service.ts]: I wasn't sure if wanted to return `undefined` for an empty string

Comment (jrasm91) [reply server/src/services/metadata.service.ts]: I don't ever use `==`, personally. It's usually not what you want and even if you think you want it, it's normally not what the application code should do imo.

Comment (danieldietzler) [reply server/src/services/metadata.service.ts]: I can change it. I am not even sure these edge cases can even happen, or if it's just bad typing from exiftool-vendored
