### PR TITLE
fix(web): integrate zoom toggle button into panorama photo viewer

### LINKED ISSUE #13521: Panoramic image bug
### The bug

The zoom in button in the panoramic image has no effect and can be deleted when displaying the panoramic image.

image

The panoramic image is displayed as a flat image in the mobile app, and it is hoped that it can be displayed normally like the web.

### The OS that Immich Server is running on

Windows 11 Docker Desktop V4.34.3

### Version of Immich Server

V1.118.2

### Version of Immich Mobile App

V1.118.2

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
--
```

### Your .env content

```Shell
--
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by meesfrensel**
## Description
Zoom toggle button didn't actually do anything in sphere photo viewer since it didn't listen to changes or anything.

Zoom state 1 (default/unzoomed for normal images) corresponds to sphere viewer zoomlevel 50 (default, ~45 degrees fov?), 'zoomed in' is set to a somewhat arbitrary 83.3%, or two thirds of the way between 'unzoomed' and fully zoomed in. 75% didn't feel like enough zooming. Can be easily changed later on based on user feedback.

Fixes #13521

## How Has This Been Tested?
Just in the browser

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if applicable
- [x] I have no unrelated changes in the PR.
- [ ] I have confirmed that any new dependencies are strictly necessary.
- [ ] I have written tests for new code (if applicable)
- [x] I have followed naming conventions/patterns in the surrounding code
- [ ] All code in `src/services/` uses repositories implementations for database calls, filesystem operations, etc.
- [ ] All code in `src/repositories/` is pretty basic/simple and does not have any immich specific logic (that belongs in `src/services/`)

## Please describe to which degree, if any, an LLM was used in creating this pull request.
None

### CODE REVIEW

File: web/src/lib/components/asset-viewer/photo-sphere-viewer-adapter.svelte [hunk 1]
```diff
@@ -161,4 +191,5 @@
   });
 </script>
 
+<svelte:document use:shortcuts={[{ shortcut: { key: 'z' }, onShortcut: zoomToggle, preventDefault: true }]} />
```
Comment (meesfrensel) [inline web/src/lib/components/asset-viewer/photo-sphere-viewer-adapter.svelte:192]: Should `preventDefault` be true or false here? In the normal photo viewer, it's a mixed bag and the 'z' zoom shortcut is even listed twice 😅 :
https://github.com/immich-app/immich/blob/2d5ec528d5977407545b8a1bd21ea887dc8dd6e9/web/src/lib/components/asset-viewer/photo-viewer.svelte#L225-L233

Comment (danieldietzler) [reply web/src/lib/components/asset-viewer/photo-sphere-viewer-adapter.svelte:192]: `true` should be the right call here

File: web/src/lib/components/asset-viewer/photo-sphere-viewer-adapter.svelte [hunk 2]
```diff
@@ -93,6 +103,20 @@
     }
   });
 
+  // Reset zoom state just in case
+  photoZoomState.set({
+    ...$photoZoomState,
+    currentZoom: 1,
+  });
```
Comment (danieldietzler) [inline web/src/lib/components/asset-viewer/photo-sphere-viewer-adapter.svelte]: "just in case" as in you ran into bugs without it?

**Review by danieldietzler — COMMENTED** [review]
Tbh I don't really like the control flow here and how it's all entangled. But that's not on you though, and as a band-aid it's pretty good

File: web/src/lib/components/asset-viewer/photo-sphere-viewer-adapter.svelte (hunk 2 above)
Comment (meesfrensel) [reply web/src/lib/components/asset-viewer/photo-sphere-viewer-adapter.svelte]: Iirc, when zooming in on one panorama, zoomstate is set to >1. Esc to exit photo viewer, open another panorama; zoomstate is still >1 and this messes with the state of the toggle button (magnify-minus instead of magnify-plus, and clicking sets zoom to 1 which the panorama photo viewer already was).

Want me to update the comment?

**Comment by meesfrensel** [comment]
100% agree on the control flow. I'm working on tiling for large panoramas and have to refactor the viewer for that. I'll try to create a cleaner abstraction then, too.

File: web/src/lib/components/asset-viewer/photo-sphere-viewer-adapter.svelte (hunk 2 above)
Comment (danieldietzler) [reply web/src/lib/components/asset-viewer/photo-sphere-viewer-adapter.svelte]: Could this be a "cleanup" kinda step then you could in an `onDestroy`?

**Comment by danieldietzler** [comment]
@meesfrensel are you already on our discord? Before you dive into more significant refactors I'd like to discuss those, we already have a pretty clear idea of how we want most things to look like. Discussing that is easier on discord :)

**Comment by meesfrensel** [comment]
I am, and will do! :) It's just easier to formulate my ideas when I have some idea of how they can be implemented so I just got started on testing that out.

File: web/src/lib/components/asset-viewer/photo-sphere-viewer-adapter.svelte (hunk 2 above)
Comment (meesfrensel) [reply web/src/lib/components/asset-viewer/photo-sphere-viewer-adapter.svelte]: That's a good idea. Done & tested.

File: web/src/lib/components/asset-viewer/photo-sphere-viewer-adapter.svelte [hunk 3]
```diff
@@ -139,10 +157,16 @@
...
     const zoomHandler = ({ zoomLevel }: events.ZoomUpdatedEvent) => {
       // zoomLevel range: [0, 100]
-      if (Math.round(zoomLevel) >= 75) {
+      photoZoomState.set({
+        ...$photoZoomState,
+        currentZoom: zoomLevel / 50,
+      });
+
+      // resolutionPlugin.getResolution() returns 'default' while original is still loading;
+      // spamming setResolution aborts and restarts network request.
```
Comment (danieldietzler) [inline web/src/lib/components/asset-viewer/photo-sphere-viewer-adapter.svelte]:
```suggestion
```
IMO not necessary, it's pretty clear that we don't need to change the resolution again if it hasn't changed

File: web/src/lib/components/asset-viewer/photo-sphere-viewer-adapter.svelte [hunk 4]
```diff
@@ -158,7 +182,14 @@
       viewer.destroy();
     }
     boundingBoxesUnsubscribe();
+    // zoomHandler is not called on initial load. Viewer inital zoom is 1, but photoZoomState could be != 1.
+    // Clean up here to prevent mismatch between photoZoomState and photo sphere viewer.
```
Comment (danieldietzler) [inline web/src/lib/components/asset-viewer/photo-sphere-viewer-adapter.svelte]:
```suggestion
    // zoomHandler is not called on initial load. Viewer initial zoom is 1, but photoZoomState could be != 1.
```

**Review by danieldietzler — APPROVED** [review]
Code looks fine for now, especially if there are already plans to clean it up and bearing that web makes some things just annoying to implement at the moment.
I don't have a panorama asset to test at hand, but I trust you tested it properly. I did confirm that zooming of "normal" images still works and this doesn't introduce a regression.

Thank you! :)
