### PR TITLE
fix(server): adjust type of person.birthDate

### LINKED ISSUE #16216: [Bug] People: Birthdays are not showing
### The bug

Birthdays are a great idea, I like it when I look through old photos and see how old a person is in those photos.
But starting this year, one of the Immich updates stopped displaying entered dates of birth.
What happened to that?

### The OS that Immich Server is running on

TrueNAS-SCALE-24.10.2

### Version of Immich Server

v1.126.1

### Version of Immich Mobile App

v1.126.1

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
https://github.com/truenas/charts/tree/master/community/immich
```

### Your .env content

```Shell
https://github.com/truenas/charts/tree/master/community/immich
```

### Reproduction steps

1. Try to set date of birth of a person using Chrome, Firefox or Edge
2. Will see notification: "Date of birth saved successfully"
3. Try setting the same person' birthday again and you will see empty date

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ngc7293**
## Description

The API currently does not respect the documentation when returning a person's birthDate. The doc/swagger says it will be of "YYYY-MM-DD" format but the string is a full ISO8601-with-tz string. This causes issue #16216 because the <input> tag is strict about supported value formats.
    
I believe this was introduced by #15242 which switched some queries from TypeORM to Kysely for the person repository. TypeORM does not parse date, but our Kysely configuration does (explicitely).
    
This commits updates the types to represent both possibilities and ensure the API always returns the correct format.

Fixes #16216

## How Has This Been Tested?

- Ensured the following pages did not result errors
  - `person/:id/` (for a person with an age)
  - `photo/:id/` (for an asset with a face)
 - Ensured the birthdate could be read and edited

<details><summary><h2>Screenshots (if appropriate)</h2></summary>

Screenshot 2025-03-05 200300

</details>

## API Changes

 - `/person/:id/` now correctly returns `birthDate` as `YYYY-MM-DD` instead of full ISO8601-with-tz

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation if applicable
- [x] I have no unrelated changes in the PR.
- [x] I have confirmed that any new dependencies are strictly necessary.
- [x] I have written tests for new code (if applicable)
- [x] I have followed naming conventions/patterns in the surrounding code
- [x] All code in `src/services` uses repositories implementations for database calls, filesystem operations, etc.
- [x] All code in `src/repositories/` is pretty basic/simple and does not have any immich specific logic (that belongs in `src/services`)

### CODE REVIEW

File: server/src/db.d.ts
Comment (ngc7293) [inline server/src/db.d.ts:1]: I edited this file manually. Whenever I tried to update it automatically, it will generate a large diff unrelated to my changes, some of which will cause compilation errors. Is this a known issue?

**Review by jrasm91 — COMMENTED** [review]
We want it to parse dates automatically I think. It's a feature we've enabled on purpose. We also already have type mappings (like this) in the config.repository.ts file. I think the fix should be specifically in the person.dto mapper function

**Comment by ngc7293** [comment]
> We want it to parse dates automatically I think. It's a feature we've enabled on purpose. We also already have type mappings (like this) in the config.repository.ts file. I think the fix should be specifically in the person.dto mapper function

How did I miss those... I was going crazy to trying to figure out why the e2e tests were failing. Thanks for the info, I'll amend my PR.

File: server/src/dtos/person.dto.ts [hunk 1]
```diff
@@ -218,11 +218,13 @@ export class PeopleResponseDto {
   hasNextPage?: boolean;
 }
 
+const asDateString = (x: string | Date | null) => (x instanceof Date ? x.toISOString().split('T')[0] : x);
```
Comment (bo0tzz) [inline server/src/dtos/person.dto.ts:221]: Is this a dupe of the utils/date.ts below?

Comment (ngc7293) [reply server/src/dtos/person.dto.ts]: My bad, fixed

**Review by alextran1502 — APPROVED** [review]

**Review by jrasm91 — APPROVED** [review]
