### PR TITLE
fix(web): show download button correctly based on shared link permission

### LINKED ISSUE #8248: Shared albuns download of individual assets not working
### The bug

On shared albuns (with ability to download checked), the download of all assets works as expected, but if I open an individual asset, there is no option for downloading it. I think this behaviour was present before 🤔. 

Found a workaround by selecting one photo, but this doesn't work great when opening in a browser in mobile. For these cases tapping the day to select all, then de-selecting and selecting only the asset wanted seems the way to go, but not very practical..

### The OS that Immich Server is running on

Docker in openmediavault (debian)

### Version of Immich Server

v1.99.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - immich.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - immich.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - immich.env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - immich.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/redacted/

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=redacted

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Create sharable link on some photos / albuns
2. Tick option to be able to download from the shared link
3. Open link (probably on a different browser / incognito so it doesn't have the host session)
4. Open a photo and try to download only that photo (no option for it appears..)
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alextran1502**
fix #8248

### CODE REVIEW

**Review by danieldietzler — APPROVED** [review]

**Review by martabal — APPROVED** [review]

**Review by jrasm91 — CHANGES_REQUESTED** [review]
We can detect if it is a shared link without passing it down as a prop on all of those components.

**Comment by jrasm91** [comment]
https://github.com/immich-app/immich/blob/main/web%2Fsrc%2Flib%2Futils.ts#L141-L143

File: web/src/lib/components/asset-viewer/asset-viewer.svelte [hunk 1]
```diff
@@ -192,6 +193,10 @@
   }
 
   onMount(async () => {
+    if (isSharedLink()) {
+      sharedLink = await getMySharedLink({ key: getKey() });
```
Comment (jrasm91) [inline web/src/lib/components/asset-viewer/asset-viewer.svelte:197]: Will this load the shared link every time the component is opened? This might not be ideal. Another option would be to use the context api or a store for tracking state related to the shared link.

**Review by jrasm91 — APPROVED** [review]
