### PR TITLE
fix(web): compute hashes for uploads in chunks

### LINKED ISSUE #27549: Memory leak during hashing when uploading big files via web app on Firefox
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When I try to upload a big video file with the web app, it states that it is hashing the file, the memory usage keeps increasing and finally Firefox gets killed by the oom.

### The OS that Immich Server is running on

HAOS

### Version of Immich Server

v2.6.2

### Version of Immich Mobile App

dna

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Device make and model

Firefox 148.0.2 on CachyOS

### Your docker-compose.yml content

```YAML
dna
```

### Your .env content

```Shell
dna
```

### Reproduction steps

1. Have an immich server
2. Try to upload a big (>10 GB) video file in Firefox
3. Watch memory consumption explode during hashing until Firefox gets killed

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by fredfloydd**
## Description

This changes the hashing in the file uploader to work in chunks, rather than loading the entire file into memory. 

Unfortunately the native crypto in browsers [can't do this](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest), so this requires adding [@noble/hashes](https://www.npmjs.com/package/@noble/hashes) as a dependency to web.

This seems to be the most lightweight option, and is widely used.

Fixes #27549 

## How Has This Been Tested?

Tested that images still show as duplicates that were uploaded before this change (ie the end result hash is the same as from the current code on `main` which uses native crypto)

## Checklist:

- [x] I have carefully read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if applicable
- [x] I have no unrelated changes in the PR.
- [x] I have confirmed that any new dependencies are strictly necessary.
- [ ] I have written tests for new code (if applicable)
- [ ] I have followed naming conventions/patterns in the surrounding code
- [ ] All code in `src/services/` uses repositories implementations for database calls, filesystem operations, etc.
- [ ] All code in `src/repositories/` is pretty basic/simple and does not have any immich specific logic (that belongs in `src/services/`)

## Please describe to which degree, if any, an LLM was used in creating this pull request.

...

### CODE REVIEW

**Review by danieldietzler — APPROVED** [review]
This looks great to me, thanks!

**Review by jrasm91 — COMMENTED** [review]
Does this block the main thread? The subtle crypto API uses a native thread from what I can tell which allows updates to still happen in the website while hashing is happening.

**Comment by fredfloydd** [comment]
Hmm, ish - the fact that there's an async step in the hashing loop will help, but this will still run on the main thread. Will see if I can use a web worker to fully delegate this away

**Comment by fredfloydd** [comment]
Added a way of doing this with a web worker. This doesn't handle the case where workers aren't available in the browser, but seems they've been around easily long enough to not worry about backwards compat.

There are libraries that claim to make working with workers/threads easier, but given this is only one use-case, don't want to pull in a further dependency or overengineered.

Tested and verified that this is still working

File: web/src/lib/utils/file-uploader.ts [hunk 1]
```diff
@@ -127,6 +127,30 @@ function getDeviceAssetId(asset: File) {
   return 'web' + '-' + asset.name + '-' + asset.lastModified;
 }
 
+function hashFile(file: File): Promise<string> {
+  return new Promise<string>((resolve, reject) => {
+    const worker = new Worker(new URL('$lib/workers/hash-file.ts', import.meta.url), { type: 'module' });
```
Comment (jrasm91) [inline web/src/lib/utils/file-uploader.ts:132]: Does this URL work in a production build?

Comment (fredfloydd) [reply web/src/lib/utils/file-uploader.ts:132]: How do I test prod builds locally? `make prod`? Struggling to get that to work on my machine for either this branch or main

Comment (jrasm91) [reply web/src/lib/utils/file-uploader.ts:132]: Normally you can just do something like:
```
pnpm build
IMMICH_SERVER_URL=https://demo.immich.app/ pnpm run preview
```

But it looks like that's not working for some reason.

Comment (fredfloydd) [reply web/src/lib/utils/file-uploader.ts:132]: I'm struggling to get this working, but have verified that when building, vite transforms the path to the ts file into `new Worker(new URL(`/_app/immutable/workers/hash-file-V98gz4_b.js`,``+import.meta.url)`

The content of that file is some (minified) js which does pretty clearly correspond to our hashing stuff.

Whilst this isn't the same as it working on an actually running build, this does make be basically completely confident that vite has handled the url faithfully and it would work in prod.

Up to you whether you're happy with that, or want to see it actually running...

Comment (jrasm91) [reply web/src/lib/utils/file-uploader.ts:132]: Agreed. We can always merge it and fix it in the case it is broken

**Review by jrasm91 — APPROVED** [review]
