### PR TITLE
fix(mobile): inconsistent query for people

### LINKED ISSUE #22169: In the Android app, people whose photos have been made private still appear in the people list.
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

ISSUE: In the Android app, people whose photos have been made private still appear in the people list, while, correctly, in the web app, such people do not appear in the people list.

### The OS that Immich Server is running on

Debian 13

### Version of Immich Server

v 1.142.1

### Version of Immich Mobile App

v 1.142.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Device make and model

Motorola Edge 40 Neo

### Your docker-compose.yml content

```YAML
sure not relevant.
```

### Your .env content

```Shell
sure not relevant
```

### Reproduction steps

1. search for a subject, move all his photos in the private folder.

EFFECTS:
2. accessing to people page via browser, that subject (name and thumbnail) is not shown. This is RIGHT.
3. accessing to people page via Android app, that subject (name and thumbnail) is shown. This is WRONG.  And it's useless too, because tapping on him, zero photos will be shown (this is right, photos are private)

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by YarosMallorca**
## Description
The `drift` query for people in the mobile app was not consistent with the server, leading the mobile app to show people that should have been hidden.

Fixes #21222
Fixes #22169

_Note: the mobile version still doesn't fetch the `minimumFaceCount` from the server, so there still could be inconsistencies. This could be improved further._

### CODE REVIEW

File: mobile/lib/infrastructure/repositories/people.repository.dart [hunk 1]
```diff
@@ -21,10 +23,25 @@ class DriftPeopleRepository extends DriftDatabaseRepository {
   Future<List<DriftPerson>> getAllPeople() async {
     final query =
         _db.select(_db.personEntity).join([
-            leftOuterJoin(_db.assetFaceEntity, _db.assetFaceEntity.personId.equalsExp(_db.personEntity.id)),
+            innerJoin(_db.assetFaceEntity, _db.assetFaceEntity.personId.equalsExp(_db.personEntity.id)),
+            innerJoin(
+              _db.remoteAssetEntity,
+              _db.remoteAssetEntity.id.equalsExp(_db.assetFaceEntity.assetId) &
+                  _db.remoteAssetEntity.visibility.equals(
+                    $RemoteAssetEntityTable.$convertervisibility.toSql(AssetVisibility.timeline),
```
Comment (shenlong-tanwen) [inline mobile/lib/infrastructure/repositories/people.repository.dart]:
```suggestion
_db.remoteAssetEntity.visibility.equalsValue(AssetVisibility.timeline),
```
Also, it doesn't matter much with inner joins, but it'd be better if you move all the conditions to the where clause instead

File: mobile/lib/infrastructure/repositories/people.repository.dart [hunk 2]
```diff
@@ -21,10 +22,19 @@ class DriftPeopleRepository extends DriftDatabaseRepository {
...
           ..where(_db.personEntity.isHidden.equals(false))
-          ..groupBy([_db.personEntity.id], having: _db.assetFaceEntity.id.count().isBiggerOrEqualValue(3))
+          ..where(_db.remoteAssetEntity.deletedAt.isNull())
+          ..where(_db.remoteAssetEntity.visibility.equalsValue(AssetVisibility.timeline))
+          ..groupBy(
+            [_db.personEntity.id],
+            having: Expression.or([
+              _db.assetFaceEntity.id.count().isBiggerOrEqualValue(3),
+              _db.personEntity.name.equals('').not(),
+            ]),
```
Comment (shenlong-tanwen) [inline mobile/lib/infrastructure/repositories/people.repository.dart]: You can combine expressions using the `|` operator instead of using `Expression.or([])`. The same goes for the where conditions. Multiple where calls are implicitly joined using the `&` operator. But we can do so explicitly like:
```dart
...where(_db.personEntity.isHidden.equals(false) & _db.remoteAssetEntity.deletedAt.isNull() & _db.remoteAssetEntity.visibility.equalsValue(AssetVisibility.timeline))

File: mobile/lib/infrastructure/repositories/people.repository.dart [hunk 3]
```diff
@@ -19,19 +20,28 @@ class DriftPeopleRepository extends DriftDatabaseRepository {
...
     final query =
-        _db.select(_db.personEntity).join([
-            leftOuterJoin(_db.assetFaceEntity, _db.assetFaceEntity.personId.equalsExp(_db.personEntity.id)),
+        _db.select(people).join([
+            innerJoin(faces, faces.personId.equalsExp(people.id)),
+            innerJoin(assets, assets.id.equalsExp(faces.assetId)),
           ])
-          ..where(_db.personEntity.isHidden.equals(false))
-          ..groupBy([_db.personEntity.id], having: _db.assetFaceEntity.id.count().isBiggerOrEqualValue(3))
+          ..where(
```
Comment (shenlong-tanwen) [inline mobile/lib/infrastructure/repositories/people.repository.dart:32]: We might also need an ownerId condition on the people entity, right?

Comment (shenlong-tanwen) [reply mobile/lib/infrastructure/repositories/people.repository.dart:32]: On hindsight, this might not be necessary as the app would only be syncing accessible person and face data from the server

**Review by shenlong-tanwen — APPROVED** [review]
