### PR TITLE
fix(server): images with non-ascii names failing to load

### LINKED ISSUE #14503: [web] Thumbnails fail to load for videos that contain special characters in the filename
### The bug

With update (v1.122.0) thumbnails for many of my videos fail to load on the web ui. I get the message "error loading image" instead. The filenames for the failed videos contain Korean or Japanese characters. 

`docker logs` show the same error repeated

I have logged out and back in of the web ui and regenerated all thumnails on the server but the issue persists.  
The mobile app shows everything correctly although it has not updated to v1.122 yet.  

### The OS that Immich Server is running on

docker on debian

### Version of Immich Server

v1.122.0

### Version of Immich Mobile App

v1.122.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
na
```

### Your .env content

```Shell
na
```

### Reproduction steps

1. Open the timeline on the web
2. Thumbnails fail to load for videos that contain Korean or Japanese text in the filename. 

### Relevant log output

```shell
[Nest] 17  - 12/05/2024, 12:10:52 PM   ERROR [Api:LoggerRepository~48tzdcmb] Unable to send file: TypeError
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
    at ServerResponse.setHeader (node:_http_outgoing:702:3)
    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:794:10)
    at sendFile (/usr/src/app/dist/utils/file.js:48:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:58:9)
[Nest] 17  - 12/05/2024, 12:10:52 PM   ERROR [Api:GlobalExceptionFilter~48tzdcmb] Unknown error: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
    at ServerResponse.setHeader (node:_http_outgoing:702:3)
    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:794:10)
    at sendFile (/usr/src/app/dist/utils/file.js:48:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:58:9)
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mertalev**
## Description

Fixes #14503

### CODE REVIEW

File: server/src/utils/file.ts [hunk 1]
```diff
@@ -58,7 +58,7 @@ export const sendFile = async (
 
     res.header('Content-Type', file.contentType);
     if (file.fileName) {
-      res.header('Content-Disposition', `inline; filename="${file.fileName}"`);
+      res.header('Content-Disposition', `inline; filename*=UTF-8''${encodeURI(file.fileName)}`);
```
Comment (michelheusschen) [inline server/src/utils/file.ts:61]: Filenames containing a comma still fail in chrome, but this fixes it:

```suggestion
      res.header('Content-Disposition', `inline; filename*=UTF-8''${encodeURIComponent(file.fileName)}`);
```

Comment (mertalev) [reply server/src/utils/file.ts:61]: Nice catch!

**Review by danieldietzler — APPROVED** [review]
