### PR TITLE
fix(mobile): use cached thumbnail in full size image provider

### LINKED ISSUE #20392: [beta] Gestures to close asset does not work until asset is fully loaded.
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When opening an asset in the beta timeline, closing it with a swipe does not work until the asset is completely loaded. When viewing images while offline, such as on a plane, this means that the close gestures never work. Ideally, the close gestures should keep working even while the asset is not completely loaded.

### The OS that Immich Server is running on

-

### Version of Immich Server

v1.36.0

### Version of Immich Mobile App

v1.36.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

Turn off any networks on mobile. Open an asset that is not local, attempt to close it with a gesture. 

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mertalev**
## Description

This is a more minimal PR extracted from #19822 to improve hero animations and asset viewer gestures before the asset is fully loaded.

Fixes #20392

#20581 is a separate issue not addressed by this

## How Has This Been Tested?

Tested on the beta timeline on local and remote photos and local videos.

### CODE REVIEW

File: mobile/lib/presentation/widgets/images/one_frame_multi_image_stream_completer.dart [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+// MultiImageStreamCompleter to better suit one-frame image loading.
+// In particular, it allows providing an initial image to emit synchronously.
+
+import 'dart:async';
+
+import 'package:flutter/foundation.dart';
+import 'package:flutter/painting.dart';
+
+/// An ImageStreamCompleter with support for loading multiple images.
+class OneFramePlaceholderImageStreamCompleter extends ImageStreamCompleter {
```
Comment (shenlong-tanwen) [inline mobile/lib/presentation/widgets/images/one_frame_multi_image_stream_completer.dart:11]: Any reason to use the base this off of `MultiImageStreamCompleter`? Flutter already has a `OneFrameImageStreamCompleter` and could extend it to add the initialImage handling

File: mobile/lib/presentation/widgets/images/one_frame_multi_image_stream_completer.dart [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+  ImageInfo? _initialImage;
+
+  /// The constructor to create an OneFramePlaceholderImageStreamCompleter. The [image]
+  /// should be the primary image to display. The [initialImage] is an optional
+  /// image that will be emitted synchronously, useful as a thumbnail or placeholder.
+  OneFramePlaceholderImageStreamCompleter(
+    Stream<ImageInfo> image, {
```
Comment (shenlong-tanwen) [inline mobile/lib/presentation/widgets/images/one_frame_multi_image_stream_completer.dart]: If it is a single frame, does it have to be a Stream and not a Future?

File: mobile/lib/presentation/widgets/images/one_frame_multi_image_stream_completer.dart [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+        listener.onImage(initialImage.clone(), true);
+      } catch (exception, stack) {
+        reportError(
+          context: ErrorDescription('by a synchronously-called image listener'),
+          exception: exception,
+          stack: stack,
+        );
+      }
+    }
+    super.addListener(listener);
```
Comment (shenlong-tanwen) [inline mobile/lib/presentation/widgets/images/one_frame_multi_image_stream_completer.dart]: The actual implementation of the ImageStreamCompleter is that when an image is resolved, `setImage` is called to cache the `ImageInfo` into a private variable (`_currentImage`) and to notify all the listeners with the new image value. Then, when the next time `addListener` is called, the cached image can be either served immediately or skipped and the listener would be notified the next time `setImage` is called.

This however, seem to only check the `initialImage` in the `addListener` override. Shouldn't we be caching the `ImageInfo` of the actual image passed and use that first and if not, fall back to using the `initialImage`?

File: mobile/lib/presentation/widgets/images/one_frame_multi_image_stream_completer.dart (hunk 2 above)
Comment (mertalev) [reply mobile/lib/presentation/widgets/images/one_frame_multi_image_stream_completer.dart]: It can be multiple images for remote assets (display preview first, then full-res).

File: mobile/lib/presentation/widgets/images/one_frame_multi_image_stream_completer.dart (hunk 1 above)
Comment (mertalev) [reply mobile/lib/presentation/widgets/images/one_frame_multi_image_stream_completer.dart:11]: Unfortunately very little is exposed to subclasses, almost everything is private. That's why `MultiImageStreamCompleter` has a lot of double underscored variables that essentially replicate a lot of logic in the base ImageStreamCompleter. This is very stripped down but I haven't checked too deeply as to whether it can be simplified further (e.g. is the keepAlive method actually used?).

File: mobile/lib/presentation/widgets/images/one_frame_multi_image_stream_completer.dart (hunk 3 above)
Comment (mertalev) [reply mobile/lib/presentation/widgets/images/one_frame_multi_image_stream_completer.dart]: The current behavior in the PR is that `onImage` is called once with the initial image and again with the current image. I think I could change it to dispose the `_initialImage` after `setImage` is called.

File: mobile/lib/presentation/widgets/images/one_frame_multi_image_stream_completer.dart (hunk 1 above)
Comment (mertalev) [reply mobile/lib/presentation/widgets/images/one_frame_multi_image_stream_completer.dart:11]: It seems to work fine after some more simplifications.

File: mobile/lib/presentation/widgets/images/one_frame_multi_image_stream_completer.dart (hunk 3 above)
Comment (shenlong-tanwen) [reply mobile/lib/presentation/widgets/images/one_frame_multi_image_stream_completer.dart]: This looks good, Thanks!

**Review by shenlong-tanwen — APPROVED** [review]
