### PR TITLE
fix(mobile): fix flutter cache eviction on thumbnails   

### LINKED ISSUE #27679: [Mobile] Photo flickering when closing asset viewer after upgrading to v2.7.3
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Please see the video

https://github.com/user-attachments/assets/51267d27-a5a9-46d7-99f4-3d6ef03284ef

### The OS that Immich Server is running on

Ubuntu 24.04.4

### Version of Immich Server

v2.7.3

### Version of Immich Mobile App

v2.7.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Device make and model

iPhone 16

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

1. Click a photo one your phone, open asset viewer
2. Close asset viewer by dragging down the photo
3. Photo flickering

### Relevant log output

```shell
No relevant log found at the INFO level
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by LeLunZ**
## Description

In #27624 we fixed that requests get evicted from cache too late. When creating the PR I was too invested in checking that we don't do double evictions anywhere anymore and  forgot that the FullImageProvider isn't actually everything and especially not what we use for thumbnails. The flag is missing from thumbhash providers and "normal" ImageProviders (which we use for thumbnails). 
That currently results in the cache always being evicted for these images, after the corresponding widget is disposed, even if they are fully loaded.

Setting isFinished manually everywhere we need, is kind of a hassle and easily forgotten. (as noticed through this PR)
Thats why I made it part of the loadRequest methods, so it's part of the whole CancellableImageProviderMixin contract. And you actually have to opt out of setting the flag, which the "special" providers then have to do (eg. FullImageProvider). 
Which means ThumbhashProvider and "normal" image provider don't have to set the flag. 

@mertalev Sorry for the inconvenience.

Fixes #27679

## How Has This Been Tested?

- verified that the flag is now actually set to true (debugged this)

## Please describe to which degree, if any, an LLM was used in creating this pull request.
/

### CODE REVIEW

File: mobile/lib/presentation/widgets/images/image_provider.dart
Comment (mertalev) [inline mobile/lib/presentation/widgets/images/image_provider.dart]: Is this image disposed?

File: mobile/lib/presentation/widgets/images/image_provider.dart [hunk 1]
```diff
@@ -51,7 +51,12 @@ mixin CancellableImageProviderMixin<T extends Object> on CancellableImageProvide
     return null;
   }
 
-  Stream<ImageInfo> loadRequest(ImageRequest request, ImageDecoderCallback decode, {bool evictOnError = true}) async* {
+  Stream<ImageInfo> loadRequest(
+    ImageRequest request,
+    ImageDecoderCallback decode, {
+    bool evictOnError = true,
+    bool markFinished = true,
```
Comment (mertalev) [inline mobile/lib/presentation/widgets/images/image_provider.dart]: It should be a required parameter; setting or not setting it to finished should be an intentional decision. For that matter, it seems to effectively mean the same thing as `evictOnError`, i.e. "is this the final image". You might be able to merge the two into an `isFinal` parameter.

Comment (LeLunZ) [reply mobile/lib/presentation/widgets/images/image_provider.dart]: Ah thats a great idea!

File: mobile/lib/presentation/widgets/images/image_provider.dart
Comment (LeLunZ) [reply mobile/lib/presentation/widgets/images/image_provider.dart]: its gc'd but I guess we know it won't be used, so we can just dispose right there

File: mobile/lib/presentation/widgets/images/image_provider.dart [hunk 2]
```diff
@@ -60,20 +60,20 @@ mixin CancellableImageProviderMixin<T extends Object> on CancellableImageProvide
...
       if (isCancelled) {
+        image?.dispose();
         return;
       }
-      if (image == null && evictOnError) {
-        PaintingBinding.instance.imageCache.evict(this);
-        return;
-      } else if (image == null) {
+      if (image == null) {
+        if (isFinal) PaintingBinding.instance.imageCache.evict(this);
```
Comment (LeLunZ) [inline mobile/lib/presentation/widgets/images/image_provider.dart]: not sure if that case is even possible (as image == null usually means cancelled), but here we also need the isFinal flag, to not prematurely evict from cache.

File: mobile/lib/presentation/widgets/images/image_provider.dart [hunk 3]
```diff
@@ -65,21 +60,20 @@ mixin CancellableImageProviderMixin<T extends Object> on CancellableImageProvide
...
         return;
       }
-      if (markFinished) isFinished = true;
+      if (isFinal) isFinished = true;
```
Comment (mertalev) [inline mobile/lib/presentation/widgets/images/image_provider.dart]:
```suggestion
      isFinished = isFinal;
```

File: mobile/lib/presentation/widgets/images/image_provider.dart [hunk 4]
```diff
@@ -102,10 +96,10 @@ mixin CancellableImageProviderMixin<T extends Object> on CancellableImageProvide
         return null;
       }
       if (codec == null) {
-        PaintingBinding.instance.imageCache.evict(this);
+        if (isFinal) PaintingBinding.instance.imageCache.evict(this);
         return null;
       }
-      if (markFinished) isFinished = true;
+      if (isFinal) isFinished = true;
```
Comment (mertalev) [inline mobile/lib/presentation/widgets/images/image_provider.dart]:
```suggestion
      isFinished = isFinal;
```

File: mobile/lib/presentation/widgets/images/image_provider.dart (hunk 2 above)
Comment (mertalev) [reply mobile/lib/presentation/widgets/images/image_provider.dart]: It only returns null on cancel, and cancel means it was already evicted. Seems redundant

Comment (LeLunZ) [reply mobile/lib/presentation/widgets/images/image_provider.dart]: Okay will remove it

**Comment by LeLunZ** [comment]
bad rebase

File: mobile/lib/presentation/widgets/images/image_provider.dart (hunk 2 above)
Comment (LeLunZ) [reply mobile/lib/presentation/widgets/images/image_provider.dart]: The null check Is still needed for typing but I removed the whole cache eviction and just moved the check into the if above

**Comment by LeLunZ** [comment]
actually @mertalev in the iOS code we have this:
```
 if let error = error {
      if request.isCancelled || (error as NSError).code == NSURLErrorCancelled {
        return request.completion(ImageProcessing.cancelledResult)
      }
      return request.completion(.failure(error))
    }
```

So we also return null incase the request errors with NSURLErrorCancelled, but I don't really know if that only happens if `request.cancel` is invoked, or if the system can also can requests

**Comment by LeLunZ** [comment]
Actually returning a cancellation incase the error code is `NSURLErrorCancelled` while `isCancelled` is false, doesn't seem right. 
As this should still be an error, as we ourselves didn't invoke the cancellation

**Comment by mertalev** [comment]
There is no case where the request is cancelled but we didn't request it. It's a slightly redundant check.

**Comment by LeLunZ** [comment]
Yeah I guess then this is finished?

File: mobile/lib/presentation/widgets/images/image_provider.dart [hunk 5]
```diff
@@ -83,22 +79,19 @@ mixin CancellableImageProviderMixin<T extends Object> on CancellableImageProvide
     }
```
Comment (LeLunZ) [inline mobile/lib/presentation/widgets/images/image_provider.dart:80]: Ah, I guess we also want to set isFinished here, when the request fails?
Because if we didn't cancel yet, but the request failed, we later don't want to call evict in the cancel method when onLastListenerRemove triggers

Comment (LeLunZ) [reply mobile/lib/presentation/widgets/images/image_provider.dart:80]: Done

File: mobile/lib/presentation/widgets/images/image_provider.dart
Comment (LeLunZ) [inline mobile/lib/presentation/widgets/images/image_provider.dart:146]: @mertalev do you know if flutter can schedule events between calling request.cancel and imageCache.evict

If yes, we would have to move the cache eviction to the top of the function?

**Review by alextran1502 — APPROVED** [review]

File: mobile/lib/presentation/widgets/images/image_provider.dart
Comment (mertalev) [reply mobile/lib/presentation/widgets/images/image_provider.dart:146]: Nope, there can't be any events between the two.

**Review by mertalev — APPROVED** [review]
