### PR TITLE
fix(server): incorrect number of assets for a person

### LINKED ISSUE #7588: [WEB] The count of assets per person is incorrect
### The bug

The count of assets per person is incorrect.
I tried setting MIN RECOGNIZED FACES to 1 but it didn't help.

image

### The OS that Immich Server is running on

Demo

### Version of Immich Server

Demo site

### Version of Immich Mobile App

Demo site

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Demo
```

### Your .env content

```Shell
Demo
```

### Reproduction steps

```bash
1. Name the face
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by martabal**
fixes #7588

### CODE REVIEW

**Review by danieldietzler — APPROVED** [review]

File: server/src/infra/repositories/person.repository.ts [hunk 1]
```diff
@@ -171,16 +171,18 @@ export class PersonRepository implements IPersonRepository {
...
   async getStatistics(personId: string): Promise<PersonStatistics> {
+    const items = await this.assetFaceRepository
+      .createQueryBuilder('face')
+      .leftJoin('face.asset', 'asset')
+      .where('face.personId = :personId', { personId })
+      .andWhere('asset.isArchived = false')
+      .andWhere('asset.deletedAt IS NULL')
+      .andWhere('asset.livePhotoVideoId IS NULL')
+      .select('COUNT(DISTINCT(asset.id))', 'count')
+      .distinct(true)
```
Comment (mertalev) [inline server/src/infra/repositories/person.repository.ts:182]: I don't think we need this

**Review by mertalev — APPROVED** [review]

**Comment by jrasm91** [comment]
Can you add an e2e test for this scenario?

**Review by jrasm91 — APPROVED** [review]
