### PR TITLE
fix: shared link custom URL photo access authentication

### LINKED ISSUE #20505: Shared link with Custom URL not working - Page not found :/ Authentication required
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [ ] Yes

### The bug

I've created a shared link for an album with Custom URL and enabled password.

Use another browser to open the Custom URL and entered the correct password, able to see gallery view of the shared album. However when clicking into the each image shows me this error "Page not found :/ Authentication required"

Screenshot:
Image

I then removed the password to the shared link and it's still same behavior and error occured.

Without Custom URL (using long URL), the error is gone —— I can view individual photos.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.137.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

1. Create shared link of an album with Custom URL option
2. Navigate to the Custom URL
3. Click on any photo for enlarged view
4. Get error "Page not found :/ Authentication required"

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gaurav-yadav**
## Description

Users experienced 401 unauthorized errors when accessing individual photos via custom URL shared links (e.g., `/s/customURL/photos/photoId`), while the album page worked fine.

**Root Cause:** The `getAssetInfoFromParam` function was only passing the `key` parameter for authentication, but custom URL shared links use `slug` for authentication.

**Solution:** Updated `getAssetInfoFromParam` to use `authManager.params` (which includes both `key` and `slug`) to align with the pattern used everywhere else in the codebase.

Fixes #20505 and #20528

## How Has This Been Tested?

- [x] Code review - Updated function follows same pattern as other asset info calls
- [x] Verified function signature compatibility with all existing callers
- [ ] Manual testing with custom URL shared links (needs reviewer testing)
- [ ] Verify both album page (`/s/customURL/`) and individual photo access (`/s/customURL/photos/photoId`) work

**Test scenarios needed:**
1. Create shared album with custom URL
2. Access album page - should work
3. Click individual photos - should now work (was failing before)
4. Direct URL access to individual photos - should now work

<details><summary><h2>Screenshots (if appropriate)</h2></summary>

None needed - this is a backend authentication fix.

</details>

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation if applicable
- [x] I have no unrelated changes in the PR.
- [x] I have confirmed that any new dependencies are strictly necessary.
- [ ] I have written tests for new code (if applicable) 
- [x] I have followed naming conventions/patterns in the surrounding code
- [x] All code in `src/services/` uses repositories implementations for database calls, filesystem operations, etc.
- [x] All code in `src/repositories/` is pretty basic/simple and does not have any immich specific logic (that belongs in `src/services/`)

### CODE REVIEW

**Review by danieldietzler — APPROVED** [review]
Good catch, thanks!

File: web/src/lib/utils/shared-links.ts [hunk 1]
```diff
@@ -43,7 +43,7 @@ export const loadSharedLink = async ({ url, params }: { url: URL; params: { key?
       },
     };
   } catch (error) {
-    if (isHttpError(error) && error.data.message === 'Invalid password') {
+    if (isHttpError(error) && (error as any).data.message === 'Invalid password') {
```
Comment (danieldietzler) [inline web/src/lib/utils/shared-links.ts]: What's this?

**Review by jrasm91 — APPROVED** [review]

**Comment by tim-koehler** [comment]
Hey everyone,
when can we expect this fix to be released?
Thanks

**Comment by danieldietzler** [comment]
We don't do ETAs but soon(tm)
