### PR TITLE
fix(mobile): Fix back button closing the app from multiselection in Android

### LINKED ISSUE #1464: [BUG] Android back button exits the app when selecting multiple assets
**Describe the bug**
When in the multiselection view of the main timeline, e.g., tapping the back button in Android (iOS has no such functionality) exits the app. I would expect it to deselect all of your photos and hide the bottom sheet. In other words, I expect it take you back to a non-multiselection state, or just the normal browsing activity.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
1. Open the Android app
2. Hold down to select multiple assets
3. Tap the back button
4. Exit the app

**Expected behavior**
I would expect to remain in the app. My selection should be cleared and the bottom sheet should hide.

**Screenshots**

"Multiselect" view I was referencing above:
image

Hitting back exits the app.

**System**
- Phone OS [iOS, Android]: Android
- Server Version: 1.42.0
- Mobile App Version: 1.43.0 build.66

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by martyfuhry**
Closes #1464

### CODE REVIEW

File: mobile/lib/modules/album/views/album_viewer_page.dart [hunk 1]
```diff
@@ -248,32 +248,45 @@ class AlbumViewerPage extends HookConsumerWidget {
       );
     }
 
+    Future<bool> onWillPop() async {
+      final isMultiselectEnable = ref.read(assetSelectionProvider).selectedAssetsInAlbumViewer.isNotEmpty;
+      if (isMultiselectEnable) {
+        ref.watch(assetSelectionProvider.notifier).removeAll();
+        return Future.value(false);
```
Comment (alextran1502) [inline mobile/lib/modules/album/views/album_viewer_page.dart:255]: Just curious, if we return `false` here, would it be converted to a Future since it is indicated in the method signature already?

Comment (martyfuhry) [reply mobile/lib/modules/album/views/album_viewer_page.dart]: Yeah you can do that, but you have to add `async` to the function signature.

**Comment by martyfuhry** [comment]
Gah, swapped a "true/false" in the HomePage `onWillPop` I had in there from testing.

**Comment by alextran1502** [comment]
I've run into an error while trying to test 
image

**Comment by martyfuhry** [comment]
Oh yeah, that's definitely not a `FutureOr` it's just a `Future`.
