### PR TITLE
fix: suggest people

### LINKED ISSUE #4548: [BUG] Suggest people when typing a name not finding people
### The bug

When I am typing in a person's name, only some of the existing names are suggested (neither of them correct).

For example, if I type 'R' then two names that start with 'Ra' are suggested, but neither are the one that I'm looking for. If I then type 'i' then there are no suggestions shown.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

1.82.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    user: 1000:1001
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    user: 1000:1001
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - /disks/storage/immich/volumes/geocoding:/usr/src/app/.reverse-geocoding-dump
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    user: 1000:1001
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /disks/storage/immich/volumes/model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - /disks/storage/immich/volumes/tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    user: 1000:1001
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /disks/storage/immich/volumes/pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

PUID=1000
GUID=1001

# The location where your uploaded files are stored
UPLOAD_LOCATION=<...>

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=<...>
DB_PASSWORD=<...>

TZ=America/New_York

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Start typing a name
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by martabal**
## Changes made in this PR

This PR adds multiple improvements:

- Prioritize people with the most assets
- Suggest people whose last names start with the typed letters (for example if you typed "o", it will suggest you "barack obama" and "oscar" instead of only "oscar")
- When typing a name, only visible people are suggested; When clicking on the done button (or hitting enter), it suggests all people with the same name entered including hidden people.
- Add an asset count (#4024) (archived, deleted and live photo assets are not counted).
- Height for the edit name input is fixed so the asset grid does not move anymore when switching from the name presentation to the edit name input and vice/versa.
- Removed the reactive statement which caused a useless API request on page initialization.
- Improved the responsive design for the edit name input.  

## Screenshots

image

### CODE REVIEW

File: server/src/infra/repositories/person.repository.ts [hunk 1]
```diff
@@ -96,14 +96,20 @@ export class PersonRepository implements IPersonRepository {
     return this.personRepository.findOne({ where: { id: personId } });
   }
 
-  getByName(userId: string, personName: string): Promise<PersonEntity[]> {
-    return this.personRepository
+  getByName(userId: string, personName: string, withHidden: boolean): Promise<PersonEntity[]> {
```
Comment (alextran1502) [inline server/src/infra/repositories/person.repository.ts:99]: You can add default value to the function's arguments like so


```suggestion
  getByName(userId: string, personName: string, withHidden: boolean = false): Promise<PersonEntity[]> {
```

File: server/src/domain/search/search.service.ts [hunk 2]
```diff
@@ -160,7 +160,7 @@ export class SearchService {
   }
 
   async searchPerson(authUser: AuthUserDto, dto: SearchPeopleDto): Promise<PersonResponseDto[]> {
-    return await this.personRepository.getByName(authUser.id, dto.name);
+    return await this.personRepository.getByName(authUser.id, dto.name, dto.withHidden || false);
```
Comment (alextran1502) [inline server/src/domain/search/search.service.ts:163]: After the default argument for the function is added, you can omit the `||false`

```suggestion
    return await this.personRepository.getByName(authUser.id, dto.name, dto.withHidden);
```

File: server/src/infra/repositories/person.repository.ts [hunk 3]
```diff
@@ -96,14 +96,20 @@ export class PersonRepository implements IPersonRepository {
...
-      .andWhere('LOWER(person.name) LIKE :name', { name: `${personName.toLowerCase()}%` })
-      .limit(20)
-      .getMany();
+      .andWhere('LOWER(person.name) LIKE :name', { name: `%${personName.toLowerCase()}%` })
+      .groupBy('person.id')
+      .orderBy('COUNT(face.assetId)', 'DESC')
+      .limit(20);
+
+    if (!withHidden) {
+      queryBuilder.andWhere('person.isHidden = false');
```
Comment (jrasm91) [inline server/src/infra/repositories/person.repository.ts:110]: Do you not need to do `queryBuilder = queryBuilder.andWhere...`?

Comment (martabal) [reply server/src/infra/repositories/person.repository.ts:110]: No you don't have to, we use the same pattern in `getAllForUser`
https://github.com/immich-app/immich/blob/250f7fc55c5d118369f06343b0d27c0521cbe7e8/server/src/infra/repositories/person.repository.ts#L76-L82

File: server/src/infra/repositories/person.repository.ts (hunk 1 above)
Comment (martabal) [reply server/src/infra/repositories/person.repository.ts:99]: Indeed we don't need `|| false`, `withHidden` has already false as the default parameter

https://github.com/immich-app/immich/blob/48ad55a6e5c6c1538bbb90142219df729dfadec9/server/src/domain/search/dto/search.dto.ts#L89-L97

File: server/src/domain/person/person.service.ts [hunk 4]
```diff
@@ -84,6 +84,16 @@ export class PersonService {
     return this.findOrFail(id).then(mapPerson);
   }
 
+  async getPersonAssetsCount(authUser: AuthUserDto, id: string): Promise<number> {
+    await this.access.requirePermission(authUser, Permission.PERSON_READ, id);
+    const person = await this.repository.getById(id);
+    if (!person) {
+      throw new NotFoundException();
```
Comment (jrasm91) [inline server/src/domain/person/person.service.ts:91]: We're currently using bad requests for these situations right now. Also, just use `this.findOrFail()`. Actually, you don't even need this check, since the access check will fail if the person doesn't exist and you don't use the person for anything anyways.

File: server/src/infra/repositories/person.repository.ts [hunk 5]
```diff
@@ -96,14 +96,32 @@ export class PersonRepository implements IPersonRepository {
     return this.personRepository.findOne({ where: { id: personId } });
   }
 
-  getByName(userId: string, personName: string): Promise<PersonEntity[]> {
-    return this.personRepository
+  getByName(userId: string, personName: string, withHidden: boolean | undefined): Promise<PersonEntity[]> {
```
Comment (jrasm91) [inline server/src/infra/repositories/person.repository.ts:99]: This implementation has a lot of overlap with `getAllForUser`, can you see if it is possible to use the same repository method for both implementations? They both basically use the same sorting criteria, query, etc. The parts that different would turn into search options (limit, etc). I think something like `searchPeople(userId: string, options: SearchOptions): Promise<PersonEntity[]>;` would make sense instead of this additional variation.

File: server/src/infra/repositories/person.repository.ts [hunk 6]
```diff
@@ -96,14 +96,32 @@ export class PersonRepository implements IPersonRepository {
...
+  getPersonAssetsCount(personId: string): Promise<number> {
+    return this.assetFaceRepository
+      .createQueryBuilder('face')
+      .leftJoin('face.asset', 'asset')
+      .where('face.personId = :personId', { personId })
+      .andWhere('asset.isArchived = false')
+      .andWhere('asset.deletedAt IS NULL')
+      .andWhere('asset.livePhotoVideoId IS NULL')
+      .distinct(true)
+      .getCount();
```
Comment (jrasm91) [inline server/src/infra/repositories/person.repository.ts:124]: This is in the person repository, can we just call it `getAssetCount(personId: string)` instead? If we rename this stuff to statistics, we can use `getStatistics` instead.

File: server/src/immich/controllers/person.controller.ts [hunk 7]
```diff
@@ -38,6 +38,11 @@ export class PersonController {
     return this.service.updatePeople(authUser, dto);
   }
 
+  @Get(':id/count')
```
Comment (jrasm91) [inline server/src/immich/controllers/person.controller.ts:41]: Can we instead use something like this?

```
GET /:id/statistics
{
  assets: number
}
```

File: web/src/routes/(user)/people/[personId]/+page.svelte [hunk 8]
```diff
@@ -462,7 +473,7 @@
                   <div
                     class="flex {index === suggestedPeople.length - 1
                       ? 'rounded-b-lg'
-                      : 'border-b dark:border-immich-dark-gray'} place-items-center bg-gray-100 p-2 dark:bg-gray-700"
+                      : ''} border-t dark:border-immich-dark-gray place-items-center bg-gray-100 p-2 dark:bg-gray-700"
```
Comment (jrasm91) [inline web/src/routes/(user)/people/[personId]/+page.svelte:476]: Is this on purpose? You now always add the `border-t ...` classes regardless of the length.

Comment (jrasm91) [reply web/src/routes/(user)/people/[personId]/+page.svelte:476]: OK, sounds good. Maybe you can move these "always" classes to the beginning of the list instead then. (and the ternary stuff could instead be at the end.

**Review by jrasm91 — APPROVED** [review]
I think everything is working now. However, I'm just now seeing that the person search endpoint is in the search controller, which is a bit of an issue. Mostly because I believe that controller is going away with pgvector refactor. Also, the endpoint really should just be merged with `GET /person`. We need to standardize the interface for that method so it handles all "get people" variations, including search by name.
