### PR TITLE
fix(server): use hw decoding for rkmpp w/o OpenCL if possible

### LINKED ISSUE #13579: RKMPP not using hardware decoding when no OpenCL even when tone-mapping is not needed
### The bug

I'm using OrangePi 3B w/ 8G memory, which equipped with a Rk3566 CPU. mali driver is not installed

When turning on Hardware Acceleration by choosing API as RKMPP, and enabled Hardware decoding, the encoding part works fine, but ffmpeg is not using rkrga to resize the video, which result to high cpu usage and low speed.

here's the ffmpeg command immich is using (running command by hand in container, args from `ps aux|grep ffmpeg`):

```
/usr/bin/ffmpeg \
-i upload/library/some.mp4 \
-y -c:v h264_rkmpp -c:a copy -movflags faststart -fps_mode passthrough \
-map 0:0 -map 0:1 -strict unofficial -g 256 -v verbose \
-vf scale=-2:720,zscale=t=linear:npl=100,tonemap=hable:desat=0,zscale=p=709:t=709:m=709:range=pc,format=yuv420p \
-level 51 -rc_mode CQP -qp_init 23 /path/to/encoded-video/some.mp4
```
> frame=  716 fps=3.7 q=-0.0 Lsize=   25130KiB time=00:00:23.85 bitrate=8629.0kbits/s speed=0.122x 

here's what can be used: (running command by hand in container, args comes from [codebase](https://github.com/immich-app/immich/blob/b1149881bd7ff2f19cde39cf407512a2854196bc/server/src/services/media.service.spec.ts#L2067))

```
/usr/bin/ffmpeg \
> -hwaccel rkmpp -hwaccel_output_format drm_prime -afbc rga -noautorotate \
> -i upload/library/some.mp4 \
> -y -c:v h264_rkmpp -c:a copy -movflags faststart -fps_mode passthrough \
> -map 0:0 -map 0:1 -strict unofficial -g 256 -v verbose \
> -vf "scale_rkrga=-2:720:format=nv12:afbc=1" \
> -level 51 -rc_mode CQP -qp_init 23 /path/to/encoded-video/some.mp4
```
> frame=  716 fps=109 q=-0.0 Lsize=   19464KiB time=00:00:23.85 bitrate=6683.6kbits/s speed=3.63x 

a warping 30 times faster.

I know mali driver is not installed, and RK3566 doesn't support HW tone-mapping, but it still can handle hw decoding and rescaling non hdr videos quite well.

I think there might be some imperfect logic in determine which args ffmpeg shoud use in `server/src/services/media.service.spec.ts` and maybe `server/src/utils/media.ts`

### The OS that Immich Server is running on

Armbian Community v24.11 bookworm

### Version of Immich Server

v1.118.2

### Version of Immich Mobile App

not related

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    group_add:
      - video
    security_opt: # enables full access to /sys and /proc, still far better than privileged: true
      - apparmor=unconfined
      - systempaths=unconfined
    devices:
      - /dev/dri
      - /dev/dma_heap
      - /dev/rga
      - /dev/mpp_service
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 1m
      #start_interval: 30s
      #start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: unless-stopped

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/docker/immich/library
DB_DATA_LOCATION=/docker/immich/postgres
TZ=Asia/Shanghai
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Turn on hw accl and hw decoding on RK3566 cpu
image

2. That's it
3.
4.
...

### Relevant log output

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by zhujunsan**
Set hardware decoding options for rkmpp when hardware decoding is enabled with no OpenCL on non-HDR file

fix #13579

### CODE REVIEW

File: server/src/utils/media.ts [hunk 1]
```diff
@@ -1014,14 +1023,18 @@ export class RkmppHwDecodeConfig extends RkmppSwDecodeConfig {
...
+        return [
+          `scale_rkrga=${this.getScaling(videoStream)}:format=p010:afbc=1`,
+          'hwmap=derive_device=opencl:mode=read',
+          `tonemap_opencl=format=nv12:r=pc:p=${colors.primaries}:t=${colors.transfer}:m=${colors.matrix}:tonemap=${this.config.tonemap}:desat=0`,
+          'hwmap=derive_device=rkmpp:mode=write:reverse=1',
+          'format=drm_prime',
+        ];
+      } else {
+        return super.getFilterOptions(videoStream);
+      }
```
Comment (mertalev) [inline server/src/utils/media.ts:1037]:
```suggestion
      }
      return super.getFilterOptions(videoStream);
```
Nit: you don't need `else` here since the if block returns.

**Review by mertalev — DISMISSED** [review]
Thanks for working on this!

**Comment by mertalev** [comment]
When it needs to tone-map and OpenCL isn't available, the command won't work. This is because the HW config's input options will keep the frames in the GPU, but the SW config's filters assume they're on CPU.

The best option here is probably to do scaling on the GPU, then add `hwdownload` and the SW tonemap filters followed by `hwupload`. This will still do decoding and scaling on the GPU and only tone-mapping will be on CPU.

**Comment by zhujunsan** [comment]
Thank you for your suggestion, you are correct. I'm not very familiar with ffmpeg and video processing, let me dig into it.

File: server/src/utils/media.ts [hunk 2]
```diff
@@ -979,12 +988,21 @@ export class RkmppHwDecodeConfig extends RkmppSwDecodeConfig {
...
+          `tonemap_opencl=format=nv12:r=pc:p=${primaries}:t=${transfer}:m=${matrix}:tonemap=${this.config.tonemap}:desat=0:tonemap_mode=lum:peak=100`,
+          'hwmap=derive_device=rkmpp:mode=write:reverse=1',
+          'format=drm_prime',
+        ];
+      }
+      return [ // use RKMPP for scaling, CPU for tone mapping
+        `scale_rkrga=${this.getScaling(videoStream)}:format=nv12`,
+        'hwdownload',
+        'format=nv12',
+        `tonemapx=tonemap=${this.config.tonemap}:desat=0:p=${primaries}:t=${transfer}:m=${matrix}:r=pc:peak=100:format=nv12`,
```
Comment (zhujunsan) [inline server/src/utils/media.ts:1004]: I actually don't know why but only `nv12` format works.

tried:

all yuv420p
```
scale_rkrga=-2:720:format=yuv420p,
hwdownload,
format=yuv420p,
tonemapx=tonemap=hable:desat=0:p=bt709:t=bt709:m=bt709:r=pc:peak=100:format=yuv420p,
hwupload
```

nv12 in rkrga, convert to yuv420p in cpu
```
scale_rkrga=-2:720:format=nv12,
hwdownload,
format=nv12,
format=yuv420p,
tonemapx=tonemap=hable:desat=0:p=bt709:t=bt709:m=bt709:r=pc:peak=100:format=yuv420p,
hwupload
```

all with color strips in video like:
微信截图_20241101141726

Comment (mertalev) [reply server/src/utils/media.ts:1004]: That makes sense since the GPU doesn't understand yuv420p, only the (very similar) nv12.

File: server/src/utils/media.ts [hunk 3]
```diff
@@ -979,12 +988,21 @@ export class RkmppHwDecodeConfig extends RkmppSwDecodeConfig {
...
+          'hwmap=derive_device=opencl:mode=read',
+          `tonemap_opencl=format=nv12:r=pc:p=${primaries}:t=${transfer}:m=${matrix}:tonemap=${this.config.tonemap}:desat=0:tonemap_mode=lum:peak=100`,
+          'hwmap=derive_device=rkmpp:mode=write:reverse=1',
+          'format=drm_prime',
+        ];
+      }
+      return [ // use RKMPP for scaling, CPU for tone mapping
+        `scale_rkrga=${this.getScaling(videoStream)}:format=nv12`,
+        'hwdownload',
+        'format=nv12',
```
Comment (mertalev) [inline server/src/utils/media.ts:1003]: You can't set the format to nv12 before tone-mapping - it will alter the colors before tone-mapping has a chance to map them to SDR. Does it not work without setting a format here? If not, use yuv420p10le instead to keep it 10-bit.

File: server/src/utils/media.ts [hunk 4]
```diff
@@ -979,12 +988,21 @@ export class RkmppHwDecodeConfig extends RkmppSwDecodeConfig {
...
+        return [ // use RKMPP for scaling, OpenCL for tone mapping
+          `scale_rkrga=${this.getScaling(videoStream)}:format=p010:afbc=1`,
+          'hwmap=derive_device=opencl:mode=read',
+          `tonemap_opencl=format=nv12:r=pc:p=${primaries}:t=${transfer}:m=${matrix}:tonemap=${this.config.tonemap}:desat=0:tonemap_mode=lum:peak=100`,
+          'hwmap=derive_device=rkmpp:mode=write:reverse=1',
+          'format=drm_prime',
+        ];
+      }
+      return [ // use RKMPP for scaling, CPU for tone mapping
+        `scale_rkrga=${this.getScaling(videoStream)}:format=nv12`,
```
Comment (mertalev) [inline server/src/utils/media.ts:1001]: Set the format to p010 here.

Comment (zhujunsan) [reply server/src/utils/media.ts:1001]: Unfortunately, after some digging, I think my chip(RK3566)'s 2D graphics module doesn't support 10bit output, therefore `p010` format (and other 10-bit format like `nv15`) is not supported. a total sw decoding might be needed here at least for RK3566

Comment (mertalev) [reply server/src/utils/media.ts:1001]: Could you share the logs? It needs to support 10-bit decoding to even get to `scale_rkrga` since the decoding happens before this filter.

Comment (zhujunsan) [reply server/src/utils/media.ts:1001]: sure, here's the log

<details>
<summary>p010</summary>

```
root@178a1f2d2a09:/usr/src/app/upload/library# /usr/bin/ffmpeg \
> -hwaccel rkmpp -hwaccel_output_format drm_prime -noautorotate \
> -i hdr.mp4 \
> -y -c:a copy -movflags faststart -fps_mode passthrough \
> -map 0:0 -map 0:1 -strict unofficial -g 256 -v verbose \
> -vf "scale_rkrga=-2:720:format=p010,\
> hwdownload,\
> format=yuv420p10le,\
> tonemapx=tonemap=hable:desat=0:p=bt709:t=bt709:m=bt709:r=pc:peak=100:format=nv12,\
> hwupload" \
> -c:v h264_rkmpp -level 51 -rc_mode CQP -qp_init 23 output.mp4
ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=arm64 --cross-prefix=/usr/bin/aarch64-linux-gnu- --toolchain=hardened --enable-cross-compile --enable-rkmpp --enable-rkrga
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Routing option strict to both codec and muxer layer
Selecting decoder 'hevc_rkmpp' because of requested hwaccel method rkmpp
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'hdr.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf61.7.100
  Duration: 00:00:20.52, start: 0.000000, bitrate: 9795 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main 10), 1 reference frame (hev1 / 0x31766568), yuv420p10le(tv, bt2020nc/unknown/unknown, left), 2160x3840 [SAR 1:1 DAR 9:16], 9600 kb/s, 30 fps, 30 tbr, 16k tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.19.100 libx265
      Side data:
        Content Light Level Metadata, MaxCLL=2000, MaxFALL=100
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 194 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
[out#0/mp4 @ 0xaaaad5f89880] Adding streams from explicit maps...
[vost#0:0/h264_rkmpp @ 0xaaaad5f47a10] Created video stream from input stream 0:0
[tonemapx @ 0xaaaad5f2d2f0] Using CPU capability: NEON
[hevc_rkmpp @ 0xaaaad5f41640] Picked up an existing RKMPP hardware device
[aost#0:1/copy @ 0xaaaad5f96850] Created audio stream from input stream 0:1
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (hevc_rkmpp) -> h264 (h264_rkmpp))
  Stream #0:1 -> #0:1 (copy)
[vost#0:0/h264_rkmpp @ 0xaaaad5f47a10] Starting thread...
[vf#0:0 @ 0xaaaad5f3d600] Starting thread...
[vist#0:0/hevc @ 0xaaaad5f3e000] [dec:hevc_rkmpp @ 0xaaaad5f89d30] Starting thread...
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0xaaaad5f2a900] Starting thread...
Press [q] to stop, [?] for help
[hevc_rkmpp @ 0xaaaad5f41640] Noticed an info change
[hevc_rkmpp @ 0xaaaad5f41640] Configured with size: 2160x3840 | pix_fmt: drm_prime | sw_pix_fmt: nv15
[tonemapx @ 0xffff9c002d00] Using CPU capability: NEON
[graph 0 input from stream 0:0 @ 0xffff9c006840] w:2160 h:3840 pixfmt:drm_prime tb:1/16000 fr:30/1 sar:1/1 csp:bt2020nc range:tv
[auto_scale_0 @ 0xffff9c008970] w:iw h:ih flags:'' interl:0
[Parsed_tonemapx_3 @ 0xffff9c002c50] auto-inserting filter 'auto_scale_0' between the filter 'Parsed_format_2' and the filter 'Parsed_tonemapx_3'
rga_api version 1.10.1_[3]
[Parsed_scale_rkrga_0 @ 0xffff9c0025e0] 'p010le' is only supported by RGA3
[Parsed_scale_rkrga_0 @ 0xffff9c0025e0] Failed to configure output pad on Parsed_scale_rkrga_0
[vf#0:0 @ 0xaaaad5f3d600] Error reinitializing filters!
[vf#0:0 @ 0xaaaad5f3d600] Task finished with error code: -38 (Function not implemented)
[vost#0:0/h264_rkmpp @ 0xaaaad5f47a10] Encoder thread received EOF
[vost#0:0/h264_rkmpp @ 0xaaaad5f47a10] Could not open encoder before EOF
[vost#0:0/h264_rkmpp @ 0xaaaad5f47a10] Task finished with error code: -22 (Invalid argument)
[vost#0:0/h264_rkmpp @ 0xaaaad5f47a10] Terminating thread with return code -22 (Invalid argument)
[vf#0:0 @ 0xaaaad5f3d600] Terminating thread with return code -38 (Function not implemented)
[vist#0:0/hevc @ 0xaaaad5f3e000] [dec:hevc_rkmpp @ 0xaaaad5f89d30] Decoder returned EOF, finishing
[vist#0:0/hevc @ 0xaaaad5f3e000] [dec:hevc_rkmpp @ 0xaaaad5f89d30] Terminating thread with return code 0 (success)
[vist#0:0/hevc @ 0xaaaad5f3e000] All consumers of this stream are done
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0xaaaad5f2a900] EOF while reading input
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0xaaaad5f2a900] Terminating thread with return code 0 (success)
[out#0/mp4 @ 0xaaaad5f89880] Nothing was written into output file, because at least one of its streams received no packets.
frame=    0 fps=0.0 q=0.0 Lsize=       0KiB time=N/A bitrate=N/A speed=N/A    
[AVIOContext @ 0xaaaad5f973a0] Statistics: 0 bytes written, 0 seeks, 0 writeouts
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0xaaaad5f2a900] Input file #0 (hdr.mp4):
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0xaaaad5f2a900]   Input stream #0:0 (video): 17 packets read (762470 bytes); 2 frames decoded; 0 decode errors; 
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0xaaaad5f2a900]   Input stream #0:1 (audio): 961 packets read (497398 bytes); 
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0xaaaad5f2a900]   Total: 978 packets (1259868 bytes) demuxed
[AVIOContext @ 0xaaaad5f33020] Statistics: 25126543 bytes read, 0 seeks
Conversion failed!
```
</details>

it says `'p010le' is only supported by RGA3`

I don't know if it is the thing but according to [some documents](https://github.com/airockchip/librga/blob/fb5f019ea0191ec1c34f49ac8be447ac8921aadd/docs/Rockchip_Developer_Guide_RGA_EN.md#image-format-supported), RK3588 is the only chip that supports a 10 bit output. Other chip (like mine RK3566) can decode 10bit stream, but not output them.

and also, from [chip datasheet](https://www.boardcon.com/download/Rockchip_RK3566_Datasheet_V1.1.pdf):

image

Comment (mertalev) [reply server/src/utils/media.ts:1001]: Hmm, is it possible to not set the format in `scale_rkrga` and just have `hwdownload,format=yuv420p10le` (or possibly `hwmap=mode=read,format= yuv420p10le`) after it?

Comment (zhujunsan) [reply server/src/utils/media.ts:1001]: Tested these three:

```
/usr/bin/ffmpeg \
-hwaccel rkmpp -hwaccel_output_format drm_prime -noautorotate \
-i hdr.mp4 \
-y -c:a copy -movflags faststart -fps_mode passthrough \
-map 0:0 -map 0:1 -strict unofficial -g 256 -v verbose \
-vf "scale_rkrga=-2:720,\
hwdownload,\
format=yuv420p10le,\
tonemapx=tonemap=hable:desat=0:p=bt709:t=bt709:m=bt709:r=pc:peak=100:format=nv12,\
hwupload" \
-c:v h264_rkmpp -level 51 -rc_mode CQP -qp_init 23 output.mp4
```

```
/usr/bin/ffmpeg \
-hwaccel rkmpp -hwaccel_output_format drm_prime -noautorotate \
-i hdr.mp4 \
-y -c:a copy -movflags faststart -fps_mode passthrough \
-map 0:0 -map 0:1 -strict unofficial -g 256 -v verbose \
-vf "scale_rkrga=-2:720,\
hwmap=mode=read,\
hwdownload,\
format=yuv420p10le,\
tonemapx=tonemap=hable:desat=0:p=bt709:t=bt709:m=bt709:r=pc:peak=100:format=nv12,\
hwupload" \
-c:v h264_rkmpp -level 51 -rc_mode CQP -qp_init 23 output.mp4
```

```
/usr/bin/ffmpeg \
-hwaccel rkmpp -hwaccel_output_format drm_prime -noautorotate \
-i hdr.mp4 \
-y -c:a copy -movflags faststart -fps_mode passthrough \
-map 0:0 -map 0:1 -strict unofficial -g 256 -v verbose \
-vf "scale_rkrga=-2:720,\
hwmap=mode=read,\
format=yuv420p10le,\
tonemapx=tonemap=hable:desat=0:p=bt709:t=bt709:m=bt709:r=pc:peak=100:format=nv12,\
hwupload" \
-c:v h264_rkmpp -level 51 -rc_mode CQP -qp_init 23 output.mp4
```


all doesn't work. all report the same error: `'nv15' as output is not supported if RGA2 is requested`, where `nv15` is the original pixel format of the video. If no pixel format is defined, original video pixel format is used, but still, 10-bit output is not supported, so same error :(

**Comment by zhujunsan** [comment]
Am I doing this right? Any more advice? @mertalev , thanks

**Comment by mertalev** [comment]
Sorry, I haven't tested it yet. I might have time to take a look at it tomorrow.

**Comment by mertalev** [comment]
I had to change `format=yuv420p10le` to `format=p010` for the tone-mapping command without OpenCL to work, but it otherwise works pretty well. I also added `async_depth=4` to all the scaling commands as I found that it improves speed.

**Review by mertalev — APPROVED** [review]

**Comment by zhujunsan** [comment]
wow great!
