### PR TITLE
fix: clear temp cache on iOS before uploads

### LINKED ISSUE #22574: iOS app storage usage grows permanently when upload is interrupted
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When an asset upload gets interrupted (for example by closing the app midway) the “document and data” portion of the app’s storage permanently grows by that asset size. 

### The OS that Immich Server is running on

Not relevant

### Version of Immich Server

v2.0.0

### Version of Immich Mobile App

v2.0.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Device make and model

iPhone 15 Pro Max

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

1. Start a backup of an asset, preferably a decent size to see the effect.
2. While the backup is running, close the app.
3. Check the storage and notice that it increased by the asset size.

### Relevant log output

```shell
None of the logs seem relevant
```

### Additional information

I’m using the new timeline. 
Clicking the “clear file cache” button does not clear the storage used. 
I tested with a ~720MB video, and every time I interrupt the upload midway by closing the app, the app size will have permanently grown by ~720MB. This can be done repeatedly to infinitely balloon the storage usage.

Before performing bug:

Image

After performing the bug once:

Image

### PR DESCRIPTION
**Pull request by shenlong-tanwen**
## Description

Fixes #22574

The `background_downloader` library stores the multipart data under `/tmp` which isn't cleaned up properly when the uploads are interrupted. We now clean it as part of our routine calls before and after backups. Thanks @skatsubo for the analysis in https://github.com/immich-app/immich/issues/22574#issuecomment-3441429808

### CODE REVIEW

**Review by alextran1502 — APPROVED** [review]

File: mobile/lib/infrastructure/repositories/storage.repository.dart [hunk 1]
```diff
@@ -89,5 +90,17 @@ class StorageRepository {
...
       log.warning("Error clearing cache", error, stackTrace);
     }
+
+    if (!CurrentPlatform.isIOS) {
+      return;
+    }
+
+    try {
+      if (await Directory.systemTemp.exists()) {
+        await Directory.systemTemp.delete(recursive: true);
```
Comment (mertalev) [inline mobile/lib/infrastructure/repositories/storage.repository.dart:100]: Isn't a bit excessive to delete *everything* in system temp? That includes things unrelated to Immich, doesn't it?

Comment (shenlong-tanwen) [reply mobile/lib/infrastructure/repositories/storage.repository.dart:100]: On iOS / macOS, the directory is actually internal to the App's sandbox even though the static accessor says `systemTemp`
