### PR TITLE
fix(mobile): speed up RenderList creation for timeline

### LINKED ISSUE #3029: [BUG] loading timeline on mobile app needs optimization
### The bug

When I open the app it takes between 10-30 seconds to see my photos.
"Building the timeline" takes very long, I am not sure if it's only with my device but heard more people saying the same with Google pixel phones.

When I open it in a webpage it is instant.

I use a Google Pixel 7 Pro with Android 13

### The OS that Immich Server is running on

Truenas Scale, K3S, ghcr.io/imagegenius/immich:latest

### Version of Immich Server

v1.64.0

### Version of Immich Mobile App

v1.64.0 build.87

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_HOSTNAME=192.168.1.x
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=192.168.1.x
      - DISABLE_MACHINE_LEARNING=false #optional
      - DISABLE_TYPESENSE=false #optional
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - CUDA_ACCELERATION=false #optional
    volumes:
      - path_to_appdata:/config
      - path_to_photos:/photos
      - path_to_machine-learning:/config/machine-learning #optional
    ports:
      - 8080:8080
    restart: unless-stopped
# This container requires an external application to be run separately to be run separately.
# Redis:
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
# PostgreSQL 14:
  postgres14:
    image: postgres:14
    ports:
      - 5432:5432
    container_name: postgres14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - path_to_postgres:/var/lib/postgresql/data
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Download app
2. Add server
3. Login
4. Setup albums
5. Close app
6. Open app
7. Building timeline (10-30 seconds)...
8. See photos
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by fyfrey**
Creating the RenderList for the AssetGrid to show e.g. the timeline takes a few seconds for large (100,000 assets) collections. With this change, the time is reduced considerably to usually less than a second.

should fix #3029 (or at least significantly improve the situation)

### CODE REVIEW

File: mobile/lib/modules/home/ui/asset_grid/asset_grid_data_structure.dart [hunk 1]
```diff
@@ -261,41 +259,33 @@ class RenderList {
...
-          last = current;
-          current = d;
-          lastOffset = offset + i;
-          count = 0;
-        }
-        prevDate = date;
-        count++;
-        i++;
+    for (final date in dates) {
+      final d = DateTime(
```
Comment (alextran1502) [inline mobile/lib/modules/home/ui/asset_grid/asset_grid_data_structure.dart:271]: The same thing about naming variable applied here

**Review by alextran1502 — COMMENTED** [review]
Hello Fynn. Thank you for the continuous optimization of the app. I left a few comments. Please help me address them.

**Comment by fyfrey** [comment]
Thanks @alextran1502 for reviewing. I now took another route to optimize the performance: First, I simply increased the batch size for the RenderList creation algorithm. Second, I've changed the code to make use of database indices on userId instead of filtering the result. This has a large impact when partner sharing is active and your partner has a large collection. Previously the large partner collection would slow down the RenderList creation for a user with few assets..

**Review by alextran1502 — APPROVED** [review]
