### PR TITLE
fix(mobile): use immutable cache keys for local images

### LINKED ISSUE #10545: Broken thumbnails in asset view after deletion
### The bug

https://github.com/immich-app/immich/assets/10235198/33a44c23-896a-44e1-91c1-5f6c3fa1f7f9

It reproduces often, but not always. If I open a photo, then browse photos with a swipe gesture and delete some of them, eventually I end up with some of the photos showing like in the screenshot that I attached. It is usually I think like 1-3 photos next to each other. If I exit the asset view and try to open such photo again, it is still broken. What fixes it is restarting the app. This is quite annoying when trying to organize photos on the phone as removing them makes me unable to further properly look through other photos unless I restart the app.

I think it is similar to my old issue #6924, but then photos were blurred.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

v1.106.4

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /data/apps/immich:/data/apps/immich
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.ml.yml
      service: openvino
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    ports:
      - 5432:5432
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. Open a photo
2. Navigate between photos
3. Delete some photos
4. Keep doing 2-3
5. At some point preview breaks
```

### Relevant log output

```shell
2024-06-22 16:08:37.619349 | SEVERE   | ImmichErrorLogger    | FlutterError - Catch all | Instance of 'FlutterErrorDetails'
Exception: Null check operator used on a null value
Library: image resource service
Context: Instance of 'ErrorDescription' |
#0      ImageCache._checkCacheSize (package:flutter/src/painting/image_cache.dart:511)
#1      ImageCache._touch (package:flutter/src/painting/image_cache.dart:288)
#2      ImageCache.putIfAbsent.listener (package:flutter/src/painting/image_cache.dart:423)
#3      ImageStreamCompleter.setImage (package:flutter/src/painting/image_stream.dart:747)
#4      MultiFrameImageStreamCompleter._emitFrame (package:flutter/src/painting/image_stream.dart:1097)
#5      MultiImageStreamCompleter._decodeNextFrameAndSchedule (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:154)
<asynchronous suspension>
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by lukaszwawrzyk**
## Description

It get rids of this exception which happens when deleting photos and swiping around the gallery. The key is the whole asset, which is mutable and changes and breaks the hashmap access in flutter internals. The remote asset variants already used the assetId as the key rather than the whole object.

```
Exception: Null check operator used on a null value
Library: image resource service
Context: Instance of 'ErrorDescription' |
#0      ImageCache._checkCacheSize (package:flutter/src/painting/image_cache.dart:511)
#1      ImageCache._touch (package:flutter/src/painting/image_cache.dart:288)
#2      ImageCache.putIfAbsent.listener (package:flutter/src/painting/image_cache.dart:423)
#3      ImageStreamCompleter.setImage (package:flutter/src/painting/image_stream.dart:747)
#4      MultiFrameImageStreamCompleter._emitFrame (package:flutter/src/painting/image_stream.dart:1097)
#5      MultiImageStreamCompleter._decodeNextFrameAndSchedule (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:154)
```

I believe it fixes the most annoying issue that I have with Immich apart for large library performance.
Fixes #10545

## How Has This Been Tested?
I reproduced the issue from the ticket. After I updated the code, I didn't manage to reproduce anymore.

## Checklist:

- [V] I have performed a self-review of my own code
- [V] I have made corresponding changes to the documentation if applicable
- [V] I have no unrelated changes in the PR.
- [V] I have confirmed that any new dependencies are strictly necessary.
- [V] I have written tests for new code (if applicable)
- [V] I have followed naming conventions/patterns in the surrounding code
- [V] All code in `src/services/` uses repositories implementations for database calls, filesystem operations, etc.
- [V] All code in `src/repositories/` is pretty basic/simple and does not have any immich specific logic (that belongs in `src/services/`)

### CODE REVIEW

File: mobile/lib/providers/image/immich_local_thumbnail_provider.dart [hunk 1]
```diff
@@ -82,11 +82,14 @@ class ImmichLocalThumbnailProvider
 
   @override
   bool operator ==(Object other) {
-    if (other is! ImmichLocalThumbnailProvider) return false;
     if (identical(this, other)) return true;
-    return asset == other.asset;
+    if (other is ImmichLocalThumbnailProvider) {
```
Comment (lukaszwawrzyk) [inline mobile/lib/providers/image/immich_local_thumbnail_provider.dart:86]: Code changes here are bigger than strictly necessary, but I made the implementation consistent with `immich_local_image_provider.dart`

**Review by alextran1502 — APPROVED** [review]
Thank you, great find to an annoying issue!

**Comment by lukaszwawrzyk** [comment]
Credits to gpt-o3 :D I pasted 4 files for context and described issue, it was really amazing
