### PR TITLE
fix(web): normalize underscore locale codes in dynamic language selection

### LINKED ISSUE #27899: Web language selection falls back for underscore locale codes after dynamic-language update
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After `feat: dynamic languages` (#27869), the web language-selection flow no longer round-trips several valid underscore-based locale codes that already exist in `i18n/*.json`.

Representative affected codes:
- `de_CH`
- - `pt_BR`
- - - `sr_Cyrl`
- - - - `zh_Hant`
The current web code keeps underscore codes in `langs`, but compares the selected/stored language against a hyphen-normalized `langCodes` list. Because of that mismatch, `getClosestAvailableLocale([$lang], langCodes)` returns `undefined` for those stored values, and the selector falls back to English instead of resolving the supported locale.

### The OS that Immich Server is running on

Ubuntu 24.04 (local development checkout)

### Version of Immich Server

main (validated on current upstream/main on 2026-04-18)

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Device make and model

Desktop browser / local dev environment

### Your docker-compose.yml content

```YAML
Not applicable for this repro. The bug is in the web locale-selection logic and can be reproduced from a local checkout / unit test.
```

### Your .env content

```Shell
Not applicable for this repro.
```

### Reproduction steps

1.
2.
31. Use a web build that includes #27869.
32. 2. Set the stored language preference to an underscore-based locale that exists in `i18n/*.json`, for example `de_CH` or `zh_Hant`.
33. 3. Open the language settings / language selector.
34. 4. Observe that the selected language resolves to the English fallback instead of the stored locale.
Equivalent logic-level repro from current code:
1. `langs` stores values like `de_CH`.
2. 2. `langCodes` stores values like `de-CH`.
3. 3. `getClosestAvailableLocale(['de_CH'], langCodes)` returns `undefined`.
...

### Relevant log output

```shell
Focused local web regression test on current main:

FAIL  src/lib/i18n-locale-regression.autovalidation.spec.ts
AssertionError: expected undefined to be 'de_CH'
AssertionError: expected undefined to be 'pt_BR'
AssertionError: expected undefined to be 'sr_Cyrl'
AssertionError: expected undefined to be 'zh_Hant'
```

### Additional information

I validated this locally against the current `main` code path and reproduced the selector fallback effect with real locale files from the repo.

Representative result:
[
  {"stored_lang":"de_CH","closestLanguage":null,"selectedOptionValue":"en","falls_back_to_english":true},
  {"stored_lang":"pt_BR","closestLanguage":null,"selectedOptionValue":"en","falls_back_to_english":true},
  {"stored_lang":"sr_Cyrl","closestLanguage":null,"selectedOptionValue":"en","falls_back_to_english":true},
  {"stored_lang":"zh_Hant","closestLanguage":null,"selectedOptionValue":"en","falls_back_to_english":true}
]

This looks like a regression from #27869 / the broader #21337 work rather than an intended behavior change.

### PR DESCRIPTION
**Pull request by shaun0927**
## Description

Fixes #27899.

`feat: dynamic languages` (#27869) introduced a mismatch between the locale code format used for stored web preferences and the format used for matching against the generated language list.

Today:
- `langs` keeps filename-based locale codes such as `de_CH` and `zh_Hant`
- `langCodes` normalizes those codes to hyphenated forms such as `de-CH` and `zh-Hant`
- the settings page derives the selected option with `getClosestAvailableLocale([$lang], langCodes)`

Because of that, supported underscore-based locale values no longer resolve correctly and the selector falls back instead of preserving the stored language.

This PR keeps the fix scoped to the comparison path only:
- normalize locale codes while matching
- keep loader keys and stored preference values unchanged
- add regression coverage for representative underscore-based locales

## How Has This Been Tested?

- [x] `pnpm --filter @immich/sdk build`
- [x] `pnpm --filter immich-web exec vitest run src/lib/i18n.spec.ts`
- [x] `pnpm --filter immich-web run check:typescript`
- [x] Local logic-level repro for stored underscore locale codes (`de_CH`, `pt_BR`, `sr_Cyrl`, `zh_Hant`)

<details><summary><h2>Screenshots (if appropriate)</h2></summary>

No UI screenshots included. This is a small logic/regression-test fix.

</details>

## Checklist:

- [x] I have carefully read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if applicable
- [x] I have no unrelated changes in the PR.
- [x] I have confirmed that any new dependencies are strictly necessary.
- [x] I have written tests for new code (if applicable)
- [x] I have followed naming conventions/patterns in the surrounding code
- [ ] All code in `src/services/` uses repositories implementations for database calls, etc.
- [ ] All code in `src/repositories/` is pretty basic/simple and does not have any immich specific logic (that belongs in `src/services/`)

## Please describe to which degree, if any, an LLM was used in creating this pull request.

Manually reviewed and rewritten before submission.

### CODE REVIEW

File: web/src/lib/utils/i18n.ts [hunk 1]
```diff
@@ -19,20 +19,21 @@ const fileCodes = Object.keys(modules)
   .map((path) => path.match(/\/(\w+)\.json$/)?.[1])
   .filter(Boolean) as string[];
 
-const convertBCP47 = (code: string) => code.replace('_', '-');
+const normalizeLocaleCode = (code: string) => code.replaceAll('_', '-');
+const convertBCP47 = (code: string) => normalizeLocaleCode(code);
```
Comment (danieldietzler) [inline web/src/lib/utils/i18n.ts]: Why? Just use `convertBCP47`?

**Review by danieldietzler — APPROVED** [review]
