### PR TITLE
fix: delay settings apply for slideshow popup

### LINKED ISSUE #17791: Slideshow time is instantly active without final confirmation with DONE-Button - WEB UI
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Change of the showing time in the slideshow-menu is instantly active without confirmation by "Fertig"-Button. So deleting the value completely to enter e.g. 120s ends in a super fast slideshow and closing the menu. 
Not a big deal but I would expect the value to be active AFTER confirmation click on "Fertig" and not instantly without confirmation.

Image

Thanks for your work and that fantastic server! 💯 🥇 

### The OS that Immich Server is running on

Ubuntu 24.04.2 VM on Proxmox Server

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

v1.131.3

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

1. open slide-show settings
2. completely delete value for showing time 
3. whole slideshow is instantly running through in superspeed
4. obviously change of that value is instantly in place and not confirmed after button click
...

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dj0024javia**
## Description

1. Fixed onChange values applying by moving variables to temp variables.

Fixes #17791

## Checklist:

- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation if applicable
- [X] I have no unrelated changes in the PR.
- [X] I have confirmed that any new dependencies are strictly necessary.
- [X] I have written tests for new code (if applicable)
- [X] I have followed naming conventions/patterns in the surrounding code
- [X] All code in `src/services/` uses repositories implementations for database calls, filesystem operations, etc.
- [X] All code in `src/repositories/` is pretty basic/simple and does not have any immich specific logic (that belongs in `src/services/`)

### CODE REVIEW

**Comment by dj0024javia** [comment]
@bo0tzz could you please review?

**Comment by bo0tzz** [comment]
please have some patience; it's the weekend, and this PR has only been open for 2 days. Someone will get around to reviewing it soon enough.

**Comment by dj0024javia** [comment]
@bo0tzz apologies, forgot it was the weekend!

**Review by alextran1502 — APPROVED** [review]

**Comment by alextran1502** [comment]
Can you help fix the linter error?

**Comment by dj0024javia** [comment]
Updated the code. That should fix the linting errors

File: web/src/lib/components/slideshow-settings.svelte [hunk 1]
```diff
@@ -47,38 +55,47 @@
...
       description={$t('admin.slideshow_duration_description')}
       min={1}
-      bind:value={$slideshowDelay}
+      bind:value={tempSlideshowDelay}
     />
   </div>
 
   {#snippet stickyBottom()}
-    <Button fullwidth color="primary" onclick={(_) => onClose()}>{$t('done')}</Button>
+    <Button fullwidth color="primary" onclick={applyChanges}>{$t('done')}</Button>
```
Comment (jrasm91) [inline web/src/lib/components/slideshow-settings.svelte:99]: if we're not going to save these changes immediately, we should have a cancel button, like we do everywhere else. Would you mind adding that?

Comment (dj0024javia) [reply web/src/lib/components/slideshow-settings.svelte:99]: I think close button be same as the cancel button. As i am making changes, and i don't want to save, i can just close it?
Let me know if adding cancel would make more sense. will do that

Comment (jrasm91) [reply web/src/lib/components/slideshow-settings.svelte:99]: When you change the date, and on most other actions, it looks something like this:



Please make this change consistent with other modals.

Comment (dj0024javia) [reply web/src/lib/components/slideshow-settings.svelte:99]: ok added cancel button and changed text of done -> Confirm as well.
As cancel and done, doesn't seem to make sense, Cancel and Confirm makes more sense
Let me know if you think otherwise
