### PR TITLE
fix: preserve hidden people state across pagination

### LINKED ISSUE #17158: {BUG} Hidden people marked as "shown" in "Show & hide people"
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

In "Show & hide people", hidden faces should be grayed out with an barred-eye icon.
This does not happen if they are loaded after scrolling down.

### The OS that Immich Server is running on

Truenas 24.10

### Version of Immich Server

v1.130.1

### Version of Immich Mobile App

N.A.

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
default truenas app
```

### Your .env content

```Shell
default truenas app
```

### Reproduction steps

Setup:
1. Create more than 500 people (pagination for GET /people seems to be set at 500)
2. Hide some people.

See error:
1. Login to the website
2. Go to Explore -> People -> View all -> "Show & hide people"
3. Scroll down until page has to load new people
4 All newly loaded faces are marked as visible, even those that should be marked as hidden

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michelheusschen**
On the People -> "Show & hide people" page the hidden state isn't set when loading the next page, causing hidden people to appear as visible.

Fixes #17158 with the solution provided by @nicosemp

### CODE REVIEW

**Comment by jrasm91** [comment]
Mutating state via `$effect` is a bit of an [anti-pattern](https://svelte.dev/docs/svelte/$effect#When-not-to-use-$effect). 

Can we change `personIsHidden` to instead just be a just of pending changes or overrides? If you change this I think everything becomes a lot simpler.
```diff
-     {@const hidden = personIsHidden[person.id]}
+     {@const hidden = overrides[person.id] ?? personIsHidden[person.id]}
```

File: web/src/lib/components/faces-page/manage-people-visibility.svelte [hunk 1]
```diff
@@ -76,8 +70,12 @@
       }
 
       for (const person of people) {
-        person.isHidden = personIsHidden[person.id];
+        const isHidden = overrides.get(person.id);
+        if (isHidden !== undefined) {
+          person.isHidden = isHidden;
+        }
       }
+      overrides.clear();
```
Comment (jrasm91) [inline web/src/lib/components/faces-page/manage-people-visibility.svelte:79]: I think it might be better to just fire an event and close the component, instead of relying on deep reactivity. That would remove the weird hack on the parent page, which could just have something like `<OnEvents {onPeopleHiddenUpdate} />` instead. I think it's also fine to just refresh the whole people list when this closes.

**Review by jrasm91 — COMMENTED** [review]
This looks a lot better. Thanks!

File: web/src/lib/components/faces-page/manage-people-visibility.svelte (hunk 1 above)
Comment (michelheusschen) [reply web/src/lib/components/faces-page/manage-people-visibility.svelte:79]: I've changed it to `onUpdate(people)` instead of `bind:people`

**Review by jrasm91 — APPROVED** [review]
