### PR TITLE
fix(web): add checkerboard background for transparent images

### LINKED ISSUE #17757: Transparent PNG impossible to see
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I have a pattern which consists of pure black lines, and pure transparent pixels. The thumbnail generated is fine, showing the lines on a grey background but when I click into the image to view it in detail, it is displayed with a black background making the black lines impossible to see.

Image

Image

### The OS that Immich Server is running on

Truenas Electric Eel

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

did not use

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
I don't know how to get this from the truenas repo apps.
```

### Your .env content

```Shell
I don't know how to get this from the truenas repo apps.
```

### Reproduction steps

1. Installed server
2. Uploaded image
3. Viewed image

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by agent-steven**
## Description

When viewing transparent images (PNG, WebP, GIF) in the asset viewer, content on transparent backgrounds is invisible against the dark viewer background. This is especially problematic for images with black content on transparency.

This adds a standard checkerboard pattern (like Photoshop/GIMP) behind all images in the asset viewer. The pattern only shows through transparent areas, so non-transparent images are unaffected.

Fixes #17757

## How Has This Been Tested?

- [x] Verified locally that the checkerboard CSS pattern renders correctly
- [x] Confirmed non-transparent formats (JPEG, etc.) are visually unaffected
- [x] Always-on checkerboard per maintainer feedback (no format check needed)

### Before vs After
Before vs After — Transparent image visibility

**Before (left):** Dark content on transparent PNG is invisible against the black viewer background.
**After (right):** Checkerboard pattern makes transparent areas clearly visible, matching industry standard (Photoshop, Figma, GIMP).

### Implementation detail
The checkerboard uses `conic-gradient(#808080 25%, #b0b0b0 25% 50%, #808080 50% 75%, #b0b0b0 75%)` at `20px × 20px` tiles — CSS only, no additional assets.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation if applicable
- [x] I have no unrelated changes in the PR.
- [x] I have confirmed that any new dependencies are strictly necessary.
- [x] I have written tests for new code (if applicable)

### CODE REVIEW

**Comment by jrasm91** [comment]
I think the asset viewer should still be black everywhere. Behind the image itself we could use the `conic-gradient`, but that should not extend past the image itself.

**Comment by LeLunZ** [comment]
@jrasm91 do you know of any other way the frontend could decide if the image could have transparency. 

There are still other image types such as „AVIF, HEIC“ which support transparency, and if a new one comes up it has to be added here.

**Comment by jrasm91** [comment]
Maybe you can just always have the background then since it will only show through if the image is transparent

**Comment by agent-steven** [comment]
Good point! Updated to always apply the checkerboard background — it only shows through transparent areas anyway, so non-transparent images are unaffected.

File: web/src/lib/components/asset-viewer/photo-viewer.svelte [hunk 1]
```diff
@@ -49,6 +49,12 @@
   const { slideshowState, slideshowLook } = slideshowStore;
   const asset = $derived(cursor.current);
 
+  const isTransparent = $derived(
+    asset.originalMimeType === 'image/png' ||
+      asset.originalMimeType === 'image/webp' ||
+      asset.originalMimeType === 'image/gif',
+  );
+
```
Comment (danieldietzler) [inline web/src/lib/components/asset-viewer/photo-viewer.svelte]: You forgot to remove the variable
```suggestion
```

**Review by danieldietzler — APPROVED** [review]

**Comment by agent-steven** [comment]
Thanks @danieldietzler for applying the fix directly! The unused `isTransparent` variable is now removed.
