### PR TITLE
fix(web): multiple fixes for people

### LINKED ISSUE #9338: Not refreshing when merging faces together
### The bug

Bug Notice: In the /people section, when merging by clicking into a face to assign an existing person, a redirect occurs, but the "X assets" count at the top only reflects the source count and is not recalculated. No refresh is triggered in this scenario

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.102.3

### Version of Immich Mobile App

xxx

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
I don't think this is needed
```

### Your .env content

```Shell
I don't think this is needed
```

### Reproduction steps

```bash
1. Explore
2. People -> View All
3. Click on somebody you want to merge
4. Type the Name in the left upper corner
5. Get redirected and see the wrong number
```

### Relevant log output

_No response_

### Additional information

I know its small but maybe its unnoticed

### PR DESCRIPTION
**Pull request by martabal**
This PR includes multiple fixes for the webUI related to the people feature:
- fixes  #9338
- fixes and simplify the search for the merge modal
- on the /people page, show the number of people when searching for a person instead of the fixed number of people

### CODE REVIEW

**Comment by ledahosn** [comment]
@martabal wow you're fast :)

**Review by danieldietzler — APPROVED** [review]
Nice! :)

File: web/src/lib/components/faces-page/people-list.svelte [hunk 1]
```diff
@@ -6,8 +6,8 @@
 
   export let screenHeight: number;
   export let people: PersonResponseDto[];
-  export let peopleCopy: PersonResponseDto[];
-  export let unselectedPeople: PersonResponseDto[];
+  export let peopleToNotShow: PersonResponseDto[];
```
Comment (alextran1502) [inline web/src/lib/components/faces-page/people-list.svelte:9]: Is this `peopleToNotShow` are filtered out people from the search query?

Comment (martabal) [reply web/src/lib/components/faces-page/people-list.svelte:9]: Yep, on the `unmerge` and `merge` modals, there's people you don't to appear in the list, like the people already selected, the person to merge, to un-merge ...
