### PR TITLE
fix(server): Fix incorrect sorting with search

### LINKED ISSUE #5916: [BUG] Mobile: Wrong date sorting on metadata search result
### The bug

1.Click on the search button 
2.search any metadata using m:you-search-keyword
3.Check the date sorting (attached screenshoot in the additional information)

Results: 
The order is random 

Expected: 
The order should be the same as the other screens on the app. (From the newest to the oldest)

P.S: You can see this behaviour also by opening any place to see the assets. 

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.V

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1.Click on the search button 
2.search any metadata using m:you-search-keyword
3.Check the date sorting (attached screenshoot in the additional information)

Results: 
The order is random 

Expected: 
The order should be the same as the other screens on the app. (From the newest to the oldest)

P.S: You can see this behaviour also by opening any place to see the assets.
```

### Additional information

WhatsApp Image 2023-12-21 at 23 13 08

### PR DESCRIPTION
**Pull request by l0nax**
Fixes #5916

### CODE REVIEW

File: server/src/infra/repositories/smart-info.repository.ts [hunk 1]
```diff
@@ -61,6 +61,7 @@ export class SmartInfoRepository implements ISmartInfoRepository {
         .andWhere('a.fileCreatedAt < NOW()')
         .leftJoinAndSelect('a.exifInfo', 'e')
         .orderBy('s.embedding <=> :embedding')
+        .orderBy('a.fileCreatedAt DESC')
```
Comment (mertalev) [inline server/src/infra/repositories/smart-info.repository.ts:64]: I don't think this is a good idea. For one thing, this code doesn't work as expected because it replaces the previous order by instead of using `addOrderBy`. But it wouldn't work even if changed. This is because vector search does comparisons on float values that are very unlikely to be equal.

It's possible to make this query a CTE and order it by date in the second pass, but this is also not great. Instead of sorting by relevance, it can now show less relevant images first. Additionally, sorting by date would be a real headache once we add pagination for this query.

Comment (l0nax) [reply server/src/infra/repositories/smart-info.repository.ts]: You're right.
I removed it.

**Review by mertalev — APPROVED** [review]
LGTM
