### PR TITLE
fix(web): properly update activityManager when browsing assets

### LINKED ISSUE #18524: Activity buttons for shared album (comments, likes) broken
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I have an album with a bunch of photos. I've pressed like for some and wrote comments for some.
When displaying the whole album, it shows "♥︎ 💬 40". Then I click on a picture without any like or comment and it changes to "♡︎ 💬" but during the load, it flashes the previous variant and back. This happens every time. It usually ends up with the correct one.
Sometimes it doesn't and shows buttons for the whole album, which then display Activity for the whole album.
And maybe even more rarely, it displayed the correct button without comments and likes, but as soon as I clicked the heart, it changed to the buttons for the whole album and actually liked the whole album instead too...
I can't reproduce these consistently though.

### The OS that Immich Server is running on

Raspbian Bookworm

### Version of Immich Server

v1.133.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION_SLOW}/upload:/usr/src/app/upload
      - ${UPLOAD_LOCATION_FAST}/upload/thumbs:/usr/src/app/upload/thumbs
      - ${UPLOAD_LOCATION_FAST}/upload/upload:/usr/src/app/upload/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION_SLOW}/model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${UPLOAD_LOCATION_FAST}/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION_FAST=/storage-fast/immich
UPLOAD_LOCATION_SLOW=/storage/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=*****

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

TZ=Europe/Prague
```

### Reproduction steps

1. Open shared album with comments and likes
2. Click image

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by robinbrisa**
## Description

On web, the ActivityManager widget does not work properly.
It seems to jump randomly when changing photos, sometimes showing the comment count for the whole album instead of the current photo.
The only way to reliably like a photo is by refreshing the page before clicking the like button.
This was caused by the album ActivityManager being initialized to the album even when viewing assets, as well as the asset ActivityManager not being properly initialized when switching assets.

Fixes #18524

First time contributing here and first time doing some front-end dev! Hope this helped.

## How Has This Been Tested?

- [x] Browse through a shared album, like a few photos. Refresh the page and check they are properly liked.
- [x] Like the shared album to make sure there is no regression.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation if applicable
- [x] I have no unrelated changes in the PR.
- [x] I have confirmed that any new dependencies are strictly necessary.
- [x] I have written tests for new code (if applicable)
- [x] I have followed naming conventions/patterns in the surrounding code
- [x] All code in `src/services/` uses repositories implementations for database calls, filesystem operations, etc.
- [x] All code in `src/repositories/` is pretty basic/simple and does not have any immich specific logic (that belongs in `src/services/`)

### CODE REVIEW

File: web/src/routes/(user)/albums/[albumId=id]/[[photos=photos]]/[[assetId=id]]/+page.svelte [hunk 1]
```diff
@@ -159,6 +159,10 @@
   };
 
   const updateComments = async () => {
+    if ($showAssetViewer) {
+      return;
+    }
```
Comment (danieldietzler) [inline web/src/routes/(user)/albums/[albumId=id]/[[photos=photos]]/[[assetId=id]]/+page.svelte]: Why is this necessary?

File: web/src/lib/components/asset-viewer/asset-viewer.svelte [hunk 2]
```diff
@@ -140,6 +140,8 @@
 
   const updateComments = async () => {
     if (album) {
+      activityManager.reset();
+      activityManager.init(album.id, asset.id);
```
Comment (danieldietzler) [inline web/src/lib/components/asset-viewer/asset-viewer.svelte]: Resetting it for every update very much defeats the purpose of the store; caching counts when possible.

**Review by danieldietzler — DISMISSED** [review]
Hey, thanks! As is this isn't a proper fix for this issue. What you'd want is find the place where we don't reset the manager even though we should (stuff like unmounting, leaving a page, whatever), and only add a reset there.

File: web/src/lib/components/asset-viewer/asset-viewer.svelte (hunk 2 above)
Comment (robinbrisa) [reply web/src/lib/components/asset-viewer/asset-viewer.svelte:144]: Hey Daniel

Thanks for your feedback :)

I'm very new to all of this so maybe I misunderstood a few things

From what I can tell, the activityManager looks like a singleton class that needs to be initialized every time the currently displayed asset changes. The reset() method just resets the internal state to zero and isn’t strictly necessary, since refreshActivities() will override the values anyway when it's called afterward.

It would definitely be useful to use it for caching counts, but as far as I can see, it doesn’t currently support that. We’d likely need to store a map internally keyed by album/asset pairs to do that properly (which I agree would be a worthwhile improvement).

The buttons in the activityManager trigger actions based on the album/asset pair that was last initialized. That’s actually what my changes were aiming to address:
- Avoiding the call to init() with a missing assetId when browsing assets (which should only happen in the album gallery view).
- Making sure init() is called when a new asset is displayed, so the buttons are correctly bound to that asset.


That said, I’m sure there are better or more idiomatic ways to do this. I still need to learn more about how things are typically done in TypeScript and SvelteKit, since these are new technologies for me.

**Comment by robinbrisa** [comment]
Hey Daniel

Thanks for your feedback :)

I'm very new to all of this so maybe I misunderstood a few things

From what I can tell, the activityManager looks like a singleton class that needs to be initialized every time the currently displayed asset changes. The reset() method just resets the internal state to zero and isn’t strictly necessary, since refreshActivities() will override the values anyway when it's called afterward.

It would definitely be useful to use it for caching counts, but as far as I can see, it doesn’t currently support that. We’d likely need to store a map internally keyed by album/asset pairs to do that properly (which I agree would be a worthwhile improvement).

The buttons in the activityManager trigger actions based on the album/asset pair that was last initialized. That’s actually what my changes were aiming to address:

- Avoiding the call to init() with a missing assetId when browsing assets (which should only happen in the album gallery view).
- Making sure init() is called when a new asset is displayed, so the buttons are correctly bound to that asset.
- 
That said, I’m sure there are better or more idiomatic ways to do this. I still need to learn more about how things are typically done in TypeScript and SvelteKit, since these are new technologies for me.

**Comment by danieldietzler** [comment]
> that needs to be initialized every time the currently displayed asset changes

That is correct! However, in this PR you don't reset it when the asset changes. You reset it with every comment update, which is too excessive.

> It would definitely be useful to use it for caching counts, but as far as I can see, it doesn’t currently support that

It does for the current asset IIRC, and then lazily fetches the data again to make sure it's actually correct.

**Comment by robinbrisa** [comment]
Okay, so I made some changes, partly according to your feedback:
- added cache for activityManager (based on album/asset pair), storing activities, comment count, like count and current user like status. Cache for last initialized album/asset pair is invalidated when adding/deleting activity.
- removed the updateComments methods. Now replaced by simply calling init(), which in addition to properly initializing the buttons for further actions also now calls refreshActivities (which was updateComments doing), using cache if necessary. Still calling this in $effect in +page.svelte for albums and the $asset-viewer component.
- hide activityManager widget after init() until refreshActivities() has finished running
- reset() now only called when destroying album +page or asset-viewer component

It seems to be working fine to me and fixes the initial issue.

Only remaining issue I think is that it seems to make extra xhr queries for some reason, but that behavior was already happening before. However the addition of cache now prevents the queries from being dispatched. But it might be worth investigating

**Review by danieldietzler — COMMENTED** [review]
Thank you very much! The code looks good to me, will have to test it still though :)

**Review by danieldietzler — APPROVED** [review]

**Comment by zackpollard** [comment]
Hey, just got around to testing this. This is a significant improvement as the requests don't get hammered on every asset change. The only bug I noticed is that the album comment count and feed (comments & likes) are not updated when you comment on an asset then go back to the album view. When an asset is commented on we should either manually increment the album counters in the activity manager, or we should make a new request to update the counts from the server. I think overall this is an improvement so I would be happy for this to be merged as-is and a future PR fix these other small issues, but if you were willing to fix those in this PR that'd be great!

**Comment by robinbrisa** [comment]
> When an asset is commented on we should either manually increment the album counters in the activity manager, or we should make a new request to update the counts from the server.

Good point, this was an oversight, I just fixed it. Cheers

**Comment by zackpollard** [comment]
Those changes look mostly good, the only thing is that it seems to be doubling up all of the requests after navigating back to the album. The activities calls and activities/statistics calls all get doubled up seemingly, see here. 
image

**Comment by robinbrisa** [comment]
> Those changes look mostly good, the only thing is that it seems to be doubling up all of the requests after navigating back to the album. The activities calls and activities/statistics calls all get doubled up seemingly

Yeah, something causes the $effect hooks to be called multiple times. The cache key doesn't have the time to be created between calls so the XHR requests all go through.
I'm taking a look at this to finally fix all these duplicated calls. I just need a bit more knowledge on how svelte works :)

**Comment by robinbrisa** [comment]
Okay, the duplicate inits are now fixed, by preventing assetManager inits without assetId changes.
The $effect duplicate calls matter should still be investigated imo but that's a matter for another PR i suppose

**Comment by zackpollard** [comment]
I'm still seeing the same behavior as before, it's happening when I add a comment in an asset then return back to the album view

**Comment by robinbrisa** [comment]
Seems fine to me.
Did the same exact steps and I'm getting 3 xhr queries per asset as expected (activities / liked / statistics)
After unvalidating the album cache (by liking or commenting an asset) you get these 3 queries called twice when visiting the album front page but it's no big deal as the 2nd call is cached (HTTP 304)
Viewing subsequent assets after that does the expected behavior, 3 xhr or 0 if cached.

**Comment by zackpollard** [comment]
Yea, it was specifically navigating to the album page that I was talking about. It's fine, just unexpected behaviour. I am happy to merge this as-is if that's not something you want to fix right now :slightly_smiling_face:
