### PR TITLE
fix(web): statusbox re-rendering and nav bar when trashing assets

### LINKED ISSUE #6570: [BUG] web: selection still shown after trash delete
### The bug

There is still shown upper selection bar after all selected items are deleted from trash using Delete button.
It keeps showing everywhere, where selection bar is, e.g. Photos

obrazek

### The OS that Immich Server is running on

Fedora 39

### Version of Immich Server

v1.93.3

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not releavant
```

### Your .env content

```Shell
not releavant
```

### Reproduction steps

```bash
see above
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by martabal**
- fixes #6570 
- avoids unnecessary re-rendering of storage statistics in the `StatusBox` each time a page loads.

### CODE REVIEW

File: web/src/lib/components/shared-components/status-box.svelte [hunk 1]
```diff
@@ -36,18 +36,22 @@
...
-        api.userApi.getMyUserInfo().then(({ data }) => data),
-      ]);
+      if (!$serverInfoStore) {
+        const { data } = await api.serverInfoApi.getServerInfo();
+        $serverInfoStore = data;
+      }
+      if (!$user) {
+        const { data } = await api.userApi.getMyUserInfo();
+        $user = data;
+      }
```
Comment (danieldietzler) [inline web/src/lib/components/shared-components/status-box.svelte:54]: Shouldn't this be handled by the store?

Comment (martabal) [reply web/src/lib/components/shared-components/status-box.svelte:54]: Yep, that AIP request is useless, correct me if I'm wrong, but you're always authenticated when you have the side-bar and that store is already handled by `auth.ts`

**Comment by jrasm91** [comment]
This description stuff keeps popping up, can you keep it out of this PR, since it seems completely unrelated?

**Review by jrasm91 — APPROVED** [review]
