### PR TITLE
fix(web): prevent unrelated assets from appearing in tag view

### LINKED ISSUE #18392: Uploaded images appear in unrelated tag view
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I think we had a similar issue for albums in the past, but currently when on a tag page, all newly uploaded assets appear on that view.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

N/A

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

1. Navigate to a tag page
2. Upload an image to Immich in another tab
3. Image appears in Tag page, until reload

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michelheusschen**
Filter out assets that do not match the timeline tag filter to prevent unrelated assets from appearing in the tag view

Fixes #18392

### CODE REVIEW

File: web/src/lib/managers/timeline-manager/types.ts [hunk 1]
```diff
@@ -18,6 +18,7 @@ export type Direction = 'earlier' | 'later';
 export type TimelineAsset = {
   id: string;
   ownerId: string;
+  tags?: string[];
```
Comment (meesfrensel) [inline web/src/lib/managers/timeline-manager/types.ts:21]: tags can be undefined as defined here

File: web/src/lib/utils/timeline-util.ts [hunk 2]
```diff
@@ -170,6 +170,7 @@ export const toTimelineAsset = (unknownAsset: AssetResponseDto | TimelineAsset):
   return {
     id: assetResponse.id,
     ownerId: assetResponse.ownerId,
+    tags: assetResponse.tags?.map((tag) => tag.id) || [],
```
Comment (meesfrensel) [inline web/src/lib/utils/timeline-util.ts]: but you fall back to `[]` if `assetResponse.tags` is undefined. Is that intentional? Seems like either this should not be `|| []` or `TimelineAsset.tags` should not be possibly undefined.

Comment (michelheusschen) [reply web/src/lib/utils/timeline-util.ts]: Yeah it can be simplified to
```suggestion
    tags: assetResponse.tags?.map((tag) => tag.id),
```

**Review by danieldietzler — APPROVED** [review]
