### PR TITLE
fix(mobile): Updated formatting of server address in networking

### LINKED ISSUE #16467: “Current server address” not properly displayed on Networking tab
### I have searched the existing issues to make sure this is not a duplicate report.

- [x] Yes

### The bug

URL appears with /api suffix in iOS networking tab 

### Version of Immich Mobile App

v1.127.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Additional information

Image

No suffix in info dropdown, or on login page

 
Image

### PR DESCRIPTION
**Pull request by YarosMallorca**
## Description

Changed the server endpoint to use `getServerUrl` for consistent formatting.

Fixes #16467

### CODE REVIEW

File: mobile/lib/widgets/settings/networking_settings/networking_settings.dart [hunk 1]
```diff
@@ -102,7 +101,7 @@ class NetworkingSettings extends HookConsumerWidget {
           padding: const EdgeInsets.only(top: 8, left: 16, bottom: 8),
           child: NetworkPreferenceTitle(
             title: "current_server_address".tr().toUpperCase(),
-            icon: currentEndpoint.startsWith('https')
+            icon: currentEndpoint!.startsWith('https')
```
Comment (alextran1502) [inline mobile/lib/widgets/settings/networking_settings/networking_settings.dart:104]: You can still access this page before any server URL is specified from the login screen. If there is no `currentEndpoint`, we can just show it as `http` icon instead

**Review by alextran1502 — APPROVED** [review]
