### PR TITLE
fix(web): allow pasting PIN code from clipboard or password manager

### LINKED ISSUE #19613: Locked folder pin can not be pasted or inserted using a password manager
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

The KeepassXC browser integration is able to correctly identify the input for the locked folder pin, however when selecting the right entry to insert it fails because "Filled password is longer than field's allowed max length".
When I try to manually do this and paste the pin into the input, nothing is entered either.

### The OS that Immich Server is running on

NixOS

### Version of Immich Server

v1.135.3

### Version of Immich Mobile App

v1.135.3

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

1. Setup the locked folder
2. Open the locked folder
3. Paste the pin into the input

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by pressslav**
## Description

The `handleKeydown` in `PinCodeInput.svelte` calls `preventDefault()` on all non-numeric keys, which blocks Ctrl+V / Cmd+V. Password managers that simulate keypresses are affected the same way. There is also no `onpaste` handler to distribute a multi-digit string across the individual inputs.

This PR allows modifier key combinations through in `handleKeydown` and adds an `onpaste` handler that extracts digits from clipboard text and fills them across the pin inputs.

Fixes #19613

## How Has This Been Tested?

- [x] Copy a 6-digit PIN and paste into the locked folder prompt with Cmd+V
- [x] Paste a partial PIN (3 digits) starting from the first input — remaining fields stay empty
- [x] Paste text containing non-numeric characters — only digits are used
- [x] Right-click context menu paste works
- [x] Normal digit-by-digit input still works as before

<details><summary><h2>Screenshots (if appropriate)</h2></summary>

N/A — no visual changes, only input behavior fix.

</details>

## Checklist:

- [x] I have carefully read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation if applicable
- [x] I have no unrelated changes in the PR.
- [x] I have confirmed that any new dependencies are strictly necessary.
- [x] I have written tests for new code (if applicable)
- [x] I have followed naming conventions/patterns in the surrounding code
- [ ] All code in `src/services/` uses repositories implementations for database calls, filesystem operations, etc.
- [ ] All code in `src/repositories/` is pretty basic/simple and does not have any immich specific logic (that belongs in `src/services/`)

## Please describe to which degree, if any, an LLM was used in creating this pull request.

Not used.

### CODE REVIEW

File: web/src/lib/components/user-settings-page/PinCodeInput.svelte [hunk 1]
```diff
@@ -132,6 +156,7 @@
         bind:value={pinValues[index]}
         onkeydown={handleKeydown}
         oninput={(event) => handleInput(event, index)}
+        onpaste={(event) => handlePaste(event, index)}
```
Comment (michelheusschen) [inline web/src/lib/components/user-settings-page/PinCodeInput.svelte]: What do you think of this solution? 

Remove maxlength="1" so browsers and password managers can insert the full PIN into the focused field. Then have `handleInput` sanitize and update the full value at once, which means `handleKeydown` no longer needs event.preventDefault(). We also wouldn't need this onpaste event or the `handlePaste` handler.

Comment (pressslav) [reply web/src/lib/components/user-settings-page/PinCodeInput.svelte]: I like that actually, it's simpler and covers more edge cases, do you want me to make the edit?

Comment (michelheusschen) [reply web/src/lib/components/user-settings-page/PinCodeInput.svelte]: Yeah go for it

**Comment by pressslav** [comment]
edited as instructed, tested on dev and it works

**Review by michelheusschen — APPROVED** [review]
Thank you! I pushed a fix to keep the digit focus the same as before. Otherwise, everything looks good to me.

**Review by alextran1502 — APPROVED** [review]
