### PR TITLE
fix(server): regenerate missing person thumbnails

### LINKED ISSUE #3741: [BUG] People thumbnails are missing after storage migration
### The bug

I have migrated thumbnails location to my SSD, then re-generated thumbnails using the appropriate job. Photo thumbnails are fine, however, _People_ thumbnails in _Explore_ section are missing.

2023-08-17 13_24_50-Settings

The server logs complain about it:
```
[Nest] 7  - 08/17/2023, 11:24:47 AM   ERROR [ExceptionsHandler] ENOENT: no such file or directory, stat 'upload/thumbs/782f1162-281b-47f0-b6c2-daaa9315b374/3eceacc5-09ed-4d45-b292-0bf9c8c4ea75.jpeg'
Error: ENOENT: no such file or directory, stat 'upload/thumbs/782f1162-281b-47f0-b6c2-daaa9315b374/3eceacc5-09ed-4d45-b292-0bf9c8c4ea75.jpeg'
[Nest] 7  - 08/17/2023, 11:24:47 AM   ERROR [ExceptionsHandler] ENOENT: no such file or directory, stat 'upload/thumbs/782f1162-281b-47f0-b6c2-daaa9315b374/9d999555-a4cb-41d2-b1dc-60a457dd40f2.jpeg'
Error: ENOENT: no such file or directory, stat 'upload/thumbs/782f1162-281b-47f0-b6c2-daaa9315b374/9d999555-a4cb-41d2-b1dc-60a457dd40f2.jpeg'
```

If I go to the jobs section and click on the _Missing_ button, it does nothing.

2023-08-17 13_27_20-Job Status - Immich — Mozilla Firefox

What am I supposed to do? Seems a bug to me.
All of the photos are external / read-only gallery.

### The OS that Immich Server is running on

Debian 11 (OpenMediaVault 6)

### Version of Immich Server

1.73

### Version of Immich Mobile App

1.73

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - <personal path to read only gallery>:<personal path to read only gallery>:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: unless-stopped

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - <personal path to read only gallery>:<personal path to read only gallery>:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: unless-stopped

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - stack.env
    restart: unless-stopped

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - tsdata:/data
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}

    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: unless-stopped

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=<redacted>
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=<redacted>
TYPESENSE_API_KEY=<redacted>
REVERSE_GEOCODING_PRECISION=2
PUBLIC_LOGIN_PAGE_MESSAGE=<redacted>
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
THUMB_LOCATION=<redacted>
```

### Reproduction steps

```bash
1. Have Immich up and running
2. Migrate thumbs storage
3. Re-generate thumbnails
4. People thumbnails are missing
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by daniele-athome**
Fix #3741.

* Queue face thumbnail generation for person records with empty thumbnailPath (the "forced" version will queue jobs for all people)
* :warning: **Architectural change** :warning: Move face thumbnail generation from face recognition queue to thumbnail generation queue
* Renamed `IPersonRepository.getAll` to `IPersonRepository.getAllForUser` since I needed `getAll` for this PR (very opinionated, I would need guidance from the Immich team to address this change properly)
* Store the assetId used for extracting a person's face in `person.faceAssetId` (it will be reused when regenerating the person's thumbnail, otherwise a random asset will be used)

I moved the job to the thumbnail generation queue because it seemed more appropriate - also given where it's started from. Although the actual job implementation is still inside the facial recognition module.

Next steps would be checking if the thumbnail file is missing and force regeneration (for another PR maybe).

### Tests

- [x] automated tests
- [x] regenerate missing face thumbnails
- [x] regenerate all face thumbnails
- [x] no side effects of empty thumbnail path in explore page (no people showed)
- [x] no side effects of empty thumbnail path in people page (no people showed)
- [x] no side effects of empty thumbnail path in person page (blank missing avatar showed)
- [x] other possible side effects of empty thumbnail path?

### CODE REVIEW

File: server/src/infra/repositories/person.repository.ts [hunk 1]
```diff
@@ -50,7 +50,15 @@ export class PersonRepository implements IPersonRepository {
     return people.length;
   }
 
-  getAll(userId: string, options?: PersonSearchOptions): Promise<PersonEntity[]> {
+  getAll(): Promise<PersonEntity[]> {
+    return this.personRepository.find();
+  }
+
+  getAllWithoutThumbnail(): Promise<PersonEntity[]> {
+    return this.personRepository.createQueryBuilder('person').where('LENGTH(person.thumbnailPath) = 0').getMany();
```
Comment (bo0tzz) [inline server/src/infra/repositories/person.repository.ts:58]: Other places in the code, such as [asset.repository.ts](https://github.com/immich-app/immich/blob/main/server/src/infra/repositories/asset.repository.ts#L173-L180), use `IsNull()` for the WHERE rather than `LENGTH`.

Comment (jrasm91) [reply server/src/infra/repositories/person.repository.ts:58]: You can do = '' instead then

**Review by jrasm91 — COMMENTED** [review]
I'd prefer to start storing the asset id on the person. Would you consider making that change here as well?

**Comment by jrasm91** [comment]
> Done. I kept the random face part as fallback in case the original asset is deleted (and after the first upgrade since the column is new).

That seems fine, but you need `onDelete: 'SET NULL'`, otherwise deleting that asset will fail because of a key violation.

**Comment by daniele-athome** [comment]
> That seems fine, but you need `onDelete: 'SET NULL'`, otherwise deleting that asset will fail because of a key violation.

I didn't create a relation - because it's not used anywhere. I did set the cascade in the migration though.

**Comment by jrasm91** [comment]
> > That seems fine, but you need `onDelete: 'SET NULL'`, otherwise deleting that asset will fail because of a key violation.
> 
> I didn't create a relation - because it's not used anywhere. I did set the cascade in the migration though.

Oh I see. The migration looks good. We really want everything to be reflected in the code though. If you deleted all the migrations and started fresh, we should be able to generate the same database structure again by generating a new migration. Since you migration is now out of sync with the person entity, this is no longer the case. The foreign key constraint won't be automatically generated if there isn't a relation in the entity.

**Comment by daniele-athome** [comment]
I adjusted the existing tests and written some new ones, however the TypeORM check is not passing. I implemented the relation from PersonEntity to AssetEntity, am I missing something? Should I define also the inverse relation maybe?

**Comment by daniele-athome** [comment]
I have adjusted failing tests and added some new ones.

However there is still that TypeORM job failing... I did refactor the migration to make it more "compliant° with automatic generation (i.e. more granular), but it won't work.

**Comment by daniele-athome** [comment]
I can even reproduce it locally. It always generates this:

```typescript
import { MigrationInterface, QueryRunner } from "typeorm";

export class TestMigration1693856515281 implements MigrationInterface {
    name = 'TestMigration1693856515281'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "person" DROP CONSTRAINT "FK_ab768006fba24450b92ead70700"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "person" ADD CONSTRAINT "FK_ab768006fba24450b92ead70700" FOREIGN KEY ("faceAssetId") REFERENCES "assets"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
```

while the constraint is present in the database (all migrations were applied)!!

**Comment by daniele-athome** [comment]
Rebased on latest main, but the TypeORM problem remains. I don't know, maybe it's a TypeORM bug:

https://github.com/typeorm/typeorm/issues/5117
https://github.com/typeorm/typeorm/issues/9248
https://github.com/typeorm/typeorm/issues/9256

Or maybe I don't know it enough. Anyway that's it for today.

**Comment by alextran1502** [comment]
@daniele-athome The migration issue is because the migration from the code is different from what you have. I tried to run the migration from the `main`, and this is what gets generated. The foreign key relationship doesn't get applied. I suspect it might have to be applied on the other side of the relation.

```typescript
import { MigrationInterface, QueryRunner } from "typeorm";

export class AddPersonFaceAssetId1693871813999 implements MigrationInterface {
    name = 'AddPersonFaceAssetId1693871813999'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "person" ADD "faceAssetId" uuid`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "person" DROP COLUMN "faceAssetId"`);
    }

}

```

**Comment by daniele-athome** [comment]
I think I fixed it. Could you run the checks again please? There was some weird system error on GitHub Actions I believe.

**Comment by daniele-athome** [comment]
Nope.

```
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_ec943280-3bca-4ca7-b4f4-d73f7f741161/7e33188b-1840-4004-91e3-18a8fa46b7e4.tar.gz. return code: 2.
```

Maybe once more?  :sweat_smile:

**Comment by daniele-athome** [comment]
Finally! All done.

File: server/src/domain/media/media.service.ts [hunk 2]
```diff
@@ -49,6 +52,32 @@ export class MediaService {
       }
     }
 
+    const personList = force
```
Comment (jrasm91) [inline server/src/domain/media/media.service.ts:55]: Can we rename `personList` to `people`? That is what we use everywhere else.

File: server/src/domain/media/media.service.ts [hunk 3]
```diff
@@ -49,6 +52,32 @@ export class MediaService {
...
+      if (face) {
+        const jobData = {
+          imageWidth: face.imageWidth,
+          imageHeight: face.imageHeight,
+          boundingBox: {
+            x1: face.boundingBoxX1,
+            x2: face.boundingBoxX2,
+            y1: face.boundingBoxY1,
+            y2: face.boundingBoxY2,
+          } as BoundingBox,
```
Comment (jrasm91) [inline server/src/domain/media/media.service.ts:73]: Why is this cast necessary? Also, can you just inline the job data into the `queue` call instead?

File: server/src/infra/entities/person.entity.ts [hunk 4]
```diff
@@ -36,6 +37,12 @@ export class PersonEntity {
   @Column({ default: '' })
   thumbnailPath!: string;
 
+  @Column({ type: 'uuid', nullable: true })
+  faceAssetId!: string | null;
+
+  @ManyToOne(() => AssetEntity, { onDelete: 'SET NULL', nullable: true })
+  faceAsset!: AssetEntity | null;
+
```
Comment (jrasm91) [inline server/src/infra/entities/person.entity.ts:45]: I don't think you need nullable in both column decorators. Also, I don't think you need `type: 'uuid'` in the ID column either. Can you compare this with other relations and make it match?

File: server/src/infra/repositories/person.repository.ts [hunk 5]
```diff
@@ -50,7 +50,15 @@ export class PersonRepository implements IPersonRepository {
     return people.length;
   }
 
-  getAll(userId: string, options?: PersonSearchOptions): Promise<PersonEntity[]> {
+  getAll(): Promise<PersonEntity[]> {
+    return this.personRepository.find();
+  }
+
+  getAllWithoutThumbnail(): Promise<PersonEntity[]> {
+    return this.personRepository.createQueryBuilder('person').where("person.thumbnailPath = ''").getMany();
```
Comment (jrasm91) [inline server/src/infra/repositories/person.repository.ts:58]: I think this would work as well? We prefer to avoid the query builder where possible.

```suggestion
    return this.personRepository.findBy({ thumbnailPath: "''" });
```

File: server/src/infra/repositories/person.repository.ts [hunk 6]
```diff
@@ -118,4 +126,13 @@ export class PersonRepository implements IPersonRepository {
   async getFaceById({ personId, assetId }: AssetFaceId): Promise<AssetFaceEntity | null> {
     return this.assetFaceRepository.findOneBy({ assetId, personId });
   }
+
+  async getRandomFace(personId: string): Promise<AssetFaceEntity | null> {
+    return this.assetFaceRepository
+      .createQueryBuilder('assetFace')
+      .where('assetFace.personId = :personId', { personId: personId })
+      .orderBy('random()')
```
Comment (jrasm91) [inline server/src/infra/repositories/person.repository.ts:134]: Does this actually need to be random? Can we just grab the first face? It looks like using `random()` forces postgres to do a full table scan.

File: server/src/infra/repositories/person.repository.ts [hunk 7]
```diff
@@ -118,4 +126,13 @@ export class PersonRepository implements IPersonRepository {
   async getFaceById({ personId, assetId }: AssetFaceId): Promise<AssetFaceEntity | null> {
     return this.assetFaceRepository.findOneBy({ assetId, personId });
   }
+
+  async getRandomFace(personId: string): Promise<AssetFaceEntity | null> {
+    return this.assetFaceRepository
+      .createQueryBuilder('assetFace')
+      .where('assetFace.personId = :personId', { personId: personId })
```
Comment (jrasm91) [inline server/src/infra/repositories/person.repository.ts:133]:
```suggestion
      .where('assetFace.personId = :personId', { personId })
```

File: server/src/infra/repositories/person.repository.ts (hunk 6 above)
Comment (jrasm91) [reply server/src/infra/repositories/person.repository.ts:134]: This whole thing can probably be rewritten as just 


```typescript
return this.assetFaceRepository.findByOne( { personId });
```

Comment (jrasm91) [reply server/src/infra/repositories/person.repository.ts:134]: This whole thing can probably be rewritten as just 


```typescript
return this.assetFaceRepository.findByOne({ personId });
```

File: server/src/infra/entities/person.entity.ts (hunk 4 above)
Comment (daniele-athome) [reply server/src/infra/entities/person.entity.ts:45]: Nullable is set in the album entity:

```
@ManyToOne(() => AssetEntity, { nullable: true, onDelete: 'SET NULL', onUpdate: 'CASCADE' })
albumThumbnailAsset!: AssetEntity | null;

@Column({ comment: 'Asset ID to be used as thumbnail', nullable: true })
albumThumbnailAssetId!: string | null;
```

I set the `uuid` type because the server complained about something (sorry, I didn't keep the logs), but that doesn't seem to happen anymore.

Comment (jrasm91) [reply server/src/infra/entities/person.entity.ts]: Sounds good. Looks like that is the only other nullable relation we have. 

Right, typeorm would have defaulted to varchar before you added the relation, which obviously would conflict with the foreign key constraint.

File: server/src/domain/media/media.service.ts [hunk 8]
```diff
@@ -49,6 +52,32 @@ export class MediaService {
...
+            imageHeight: face.imageHeight,
+            boundingBox: {
+              x1: face.boundingBoxX1,
+              x2: face.boundingBoxX2,
+              y1: face.boundingBoxY1,
+              y2: face.boundingBoxY2,
+            },
+            assetId: face.assetId,
+            personId: person.id,
+          } as IFaceThumbnailJob,
```
Comment (jrasm91) [inline server/src/domain/media/media.service.ts:76]: this one as well

**Review by jrasm91 — APPROVED** [review]
Looks good!

File: server/src/domain/media/media.service.ts (hunk 8 above)
Comment (daniele-athome) [reply server/src/domain/media/media.service.ts]: You're right! I just saw that every combination of queue and parameters are typed.
