### PR TITLE
fix(server): remove mbtree files after transcoding

### LINKED ISSUE #2600: [BUG] Two-pass encoding `ffmpeg` log files persist
### The bug

Thanks for all the great updates in the past few weeks! This thing is really taking off 😀

This issue is nothing serious, but should be noted. I just messed with the two pass video encoding feature (I'm using h264, but suppose it is the same for other codecs) and found a `ffmpeg` 1st pass log file in the `encoded-video` folder after successful encoding. This file is not needed anymore and persists even when deleting the uploaded video.

grafik

### The OS that Immich Server is running on

Debian 11

### Version of Immich Server

v.1.58.0

### Version of Immich Mobile App

v.1.58.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. Enable two-pass encoding for videos.
2. Check `encoded-video` folder in server fs and find a second file with suffix `.mbtree` that is not needed anymore nor deleted when deleting the uploaded video.
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by brighteyed**
Fixes #2600.

The following trascoding settings result in the creation of the `mbtree` file by `ffmpeg`:
- h264 video codec
- 2-pass transcoding
- constrained quality (i.e. max bitrate != 0)
- veryfast or slower preset

That file remains on the disk after the video encoding is completed. This PR removes mbsync file after the successfull transcoding.

### CODE REVIEW

File: server/libs/infra/src/repositories/media.repository.ts [hunk 1]
```diff
@@ -117,6 +117,7 @@ export class MediaRepository implements IMediaRepository {
             .output(output)
             .on('error', reject)
             .on('end', () => fs.unlink(`${output}-0.log`))
+            .on('end', () => fs.rm(`${output}-0.log.mbtree`, { force: true }))
```
Comment (jrasm91) [inline server/libs/infra/src/repositories/media.repository.ts:120]: In general, whenever we write a file to a disk I think non-root users have to make changes for their app to continue to work, including kubernetes users. We should consider having a variable for temp locations, possible defaulted to `/tmp` where these files can be written to instead.

**Review by jrasm91 — APPROVED** [review]
