### PR TITLE
fix(web): fix badge value in queues page

### LINKED ISSUE #25145: “Waiting” Job Count Does Not Update While Jobs Are Completing in Graph
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When thumbnail generation jobs are running, the Jobs over time graph correctly shows jobs completing and the active count decreasing. However, the Waiting counter remains unchanged and does not update in real time. Even though the graph confirms progress and job completion, the waiting tag continues to display the original value until a refresh or job completion event finishes entirely. This causes a mismatch between the visual progress graph and the waiting job count.

### The OS that Immich Server is running on

Ubuntu 24 

### Version of Immich Server

v2.2.1

### Version of Immich Mobile App

v2.2.1

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Device make and model

_No response_

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

Run any job 
click on Graph
waiting tag is static 

Image

### Relevant log output

```shell

```

### Additional information

the whole graph is wrong pls make it good and relevant to data too

### PR DESCRIPTION
**Pull request by beinganukul**
Remove OnEvents component and manual queue updates, using queueManager for derived queue state instead. This reduces complexity and leverages centralized queue management.

## Description

Fixes #25145

## How Has This Been Tested?

- [x] Tested on firefox browser
- [x] Tested on fresh clone with minimal setup and on around 300 assets thumbnail generation

<details><summary><h2>Screenshots (if appropriate)</h2></summary>

image
image

</details>

## Please describe to which degree, if any, an LLM was used in creating this pull request.
used to generate commit message
...

### CODE REVIEW

File: web/src/routes/admin/queues/[name]/+page.svelte [hunk 1]
```diff
@@ -29,21 +27,15 @@
 
   const { data }: Props = $props();
 
-  let queue = $derived(data.queue);
+  let queue = $derived(queueManager.queues.find((q) => q.name === data.queue.name) || data.queue);
```
Comment (danieldietzler) [inline web/src/routes/admin/queues/[name]/+page.svelte]:
```suggestion
  const queue = $derived(queueManager.queues.find((q) => q.name === data.queue.name) ?? data.queue);
```

**Review by danieldietzler — APPROVED** [review]
Thanks!

**Comment by danieldietzler** [comment]
Hey @beinganukul would you mind fixing the formatting and implementing my small nit? :)

**Comment by beinganukul** [comment]
> Hey @beinganukul would you mind fixing the formatting and implementing my small nit? :)

sure did
