### PR TITLE
fix(web): use event for zooming out after opening face editor

### LINKED ISSUE #27734: Adding a face when zoomed in, zooms out the image but does not set the new state as zoomed out.
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

1. open a photo on immich web
2. zoom into the image
3. add a face
the image will zoom out and you have to manually zoom it out and back in again.

### The OS that Immich Server is running on

docker on windows

### Version of Immich Server

v2.7.4

### Version of Immich Mobile App

na

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Device make and model

windows

### Your docker-compose.yml content

```YAML
irrelevant
```

### Your .env content

```Shell
irrelevant
```

### Reproduction steps

1. open a photo on immich web
2. zoom into the image
3. add a face
the image will zoom out and you have to manually zoom it out and back in again.

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by meesfrensel**
## Description
Opening the face editor zooms out the image, but the animated zoom keeps updating the zoom state, so we got stuck in an $effect loop, zooming out ever slightly more but never to zoom level 1. I added a `FaceEditModeChange` event to the asset viewer manager which fires only once, and use that to start the (animated) zoom.

Fixes #27734

## How Has This Been Tested?
- Zoom in; start tagging a face; the image zooms out.
  - Notice that on main, the zoom is not cubic and the magnifying glass remains in its 'zoomed in' state.
  - On this branch, the zoom is cubic and the images is fully zoomed out
- Insert console.log statement in `assetViewerManager.animatedZoom` to check when it's triggered
  - On main, a seemingly infinite number of times
  - On this branch, only once

## Please describe to which degree, if any, an LLM was used in creating this pull request.
None

### CODE REVIEW

File: web/src/lib/components/asset-viewer/photo-viewer.svelte [hunk 1]
```diff
@@ -54,8 +54,17 @@
...
   });
 
+  const unsubscribe = assetViewerManager.on({
+    FaceEditModeChange: (isFaceEditMode) => {
+      if (isFaceEditMode && assetViewerManager.zoom > 1) {
+        onZoom();
+      }
+    },
+  });
+
```
Comment (jrasm91) [inline web/src/lib/components/asset-viewer/photo-viewer.svelte]: Can you update this to use `<AssetViewerEvents {onFaceEditModeChange} />` instead? It takes care of unsubscribing for you..

**Review by jrasm91 — COMMENTED** [review]
Nice, there's a utility component for stuff like this, otherwise looks good!

File: web/src/lib/components/asset-viewer/photo-viewer.svelte (hunk 1 above)
Comment (meesfrensel) [reply web/src/lib/components/asset-viewer/photo-viewer.svelte]: Nice, changed.

**Review by danieldietzler — APPROVED** [review]
