### PR TITLE
fix(web): clear unsaved asset description when changing asset

### LINKED ISSUE #15990: Photo description bugs
### The bug

1) Newly entered description stays there (only visually) while listing photos by left-right buttons until photo with another non-empty description comes. Additonally when that stucked description is entered on asset without a description, it's saved to it as well on exit
2) Panorama photos description imported from asset (attached) cannot be deleted, when it's deleted and saved as empty it appears again after asset is reloaded

https://github.com/user-attachments/assets/4ac29a34-cf9c-4dbc-9e97-4bfe9a719354

Image

### The OS that Immich Server is running on

Fedora 41

### Version of Immich Server

v1.125.7

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

above and attachements

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michelheusschen**
This fixes a detail panel bug where an unsaved description could leak into the next asset when navigating between assets with the same saved description (for example, both empty)

Should fix #15990

### CODE REVIEW

File: web/src/lib/components/asset-viewer/detail-panel-description.svelte [hunk 1]
```diff
@@ -14,7 +14,12 @@
   let { asset, isOwner }: Props = $props();
 
   let currentDescription = $derived(asset.exifInfo?.description ?? '');
-  let description = $derived(currentDescription);
+  let description = $state('');
+
+  $effect.pre(() => {
+    void asset.id;
+    description = currentDescription;
+  });
```
Comment (danieldietzler) [inline web/src/lib/components/asset-viewer/detail-panel-description.svelte]: Why does this even happen? Shouldn't `asset.exifInfo.description` update when navigating to the next asset, resulting in `currentDescription` and subsequently `description` to update as well?

Comment (michelheusschen) [reply web/src/lib/components/asset-viewer/detail-panel-description.svelte]: This issue only occurs when the asset you navigate to has the same initial description. In that case `currentDescription` doesn't change so the `description` derived also doesn't update and you end up with a stale value

Comment (danieldietzler) [reply web/src/lib/components/asset-viewer/detail-panel-description.svelte]: Oh, I see. Do we even need the indirection of `currentDescription`? Can't we just `let description = $derived(asset.exifInfo?.description ?? '')` and always work with that?

Comment (michelheusschen) [reply web/src/lib/components/asset-viewer/detail-panel-description.svelte]: That should work actually, I've pushed the change. This exposes a caching issue though when navigating back to the changed asset, but I'll open a separate PR for that.

**Review by danieldietzler — APPROVED** [review]
Thank you! :)
