### PR TITLE
fix(web): Handle duplicate library settings gracefully

### LINKED ISSUE #6694: Web UI handling of duplicate library import paths
### The bug

It's possible to add the same import path to a library twice (oops) and save it.

Once it's been saved, if you try and remove it via the edit modal -> Delete button the UI removes both copies of the path. I didn't click Save to find out what the UI/API actually does if you try and commit the delete.

### The OS that Immich Server is running on

debian stable

### Version of Immich Server

v1.93.3

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
see description
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by etnoy**
Don't allow adding duplicate import paths. Disable save button if input is empty or duplicate. Add error text if duplicate path.
image

Add text saying import paths are empty
image

Also, the same thing for exclusion patterns

### CODE REVIEW

File: web/src/lib/components/forms/library-import-path-form.svelte [hunk 1]
```diff
@@ -5,15 +5,27 @@
   import FullScreenModal from '../shared-components/full-screen-modal.svelte';
   import { mdiFolderSync } from '@mdi/js';
 
-  export let importPath: string;
+  import { onMount } from 'svelte';
```
Comment (jrasm91) [inline web/src/lib/components/forms/library-import-path-form.svelte:8]: can you not put new lines between import statements please?

**Review by jrasm91 — APPROVED** [review]
LGTM

File: web/src/lib/components/forms/library-import-path-form.svelte (hunk 1 above)
Comment (etnoy) [reply web/src/lib/components/forms/library-import-path-form.svelte:8]: Oh, my bad. Will fix

File: web/src/lib/components/forms/library-scan-settings-form.svelte [hunk 2]
```diff
@@ -48,13 +48,16 @@
     }
 
     try {
-      library.exclusionPatterns.push(exclusionPatternToAdd);
+      // Check so that exclusion pattern isn't duplicated
+      if (!library.exclusionPatterns.includes(exclusionPatternToAdd)) {
+        library.exclusionPatterns.push(exclusionPatternToAdd);
+        exclusionPatterns = library.exclusionPatterns;
+      }
```
Comment (danieldietzler) [inline web/src/lib/components/forms/library-scan-settings-form.svelte:55]: We're doing that check in 3 different places or so. Not sure if I'm a huge fan of this...

**Review by danieldietzler — APPROVED** [review]
Nice

File: web/src/lib/components/forms/library-scan-settings-form.svelte (hunk 2 above)
Comment (etnoy) [reply web/src/lib/components/forms/library-scan-settings-form.svelte:55]: We check both in the modal for add/edit and in the handle function. I think both are needed. I'll likely also add a check in the server to prevent duplicates submitted via API.

Comment (jrasm91) [reply web/src/lib/components/forms/library-scan-settings-form.svelte:55]: Another option is to not do anything client side and auto dedupe server side instead

Comment (etnoy) [reply web/src/lib/components/forms/library-scan-settings-form.svelte:55]: We still need to dedupe client side because of the client-side bugs in #6694. I'll address the server side in another PR
