### PR TITLE
fix(server): use thumbnail content type instead of application/octet-stream

### LINKED ISSUE #3018: thumbnails should be served with the correct content type
### The bug

Thumbnails are always server with the `application/octet-stream` content type, they shouldn't be.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.64.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mertalev**
## Description
Fixes a bug where all thumbnails would have the `application/octet-stream` mime type. This was caused by the content type not being set in `getAssetThumbnail`, which meant that the default for streams was used instead.

Fixes #3018

## How Has This Been Tested?

Thumbnails in the main gallery view now have `image/jpeg` or `image/webp` mime types as expected.

### CODE REVIEW

File: server/src/immich/api-v1/asset/asset.controller.ts [hunk 1]
```diff
@@ -122,6 +122,7 @@ export class AssetController {
   @SharedLinkRoute()
   @Get('/file/:id')
   @Header('Cache-Control', 'private, max-age=86400, no-transform')
+  @ApiOkResponse({ content: { 'application/octet-stream': { schema: { type: 'string', format: 'binary' } } } })
```
Comment (mertalev) [inline server/src/immich/api-v1/asset/asset.controller.ts]: I added this decorator back for `serveFile` since `application/octet-stream` is in the OpenAPI spec for it and there's too many possible content types to narrow it down.

File: server/src/immich/api-v1/asset/asset.service.ts [hunk 2]
```diff
@@ -260,7 +260,7 @@ export class AssetService {
 
     try {
       const thumbnailPath = this.getThumbnailPath(asset, query.format);
-      return this.streamFile(thumbnailPath, res, headers);
+      return this.streamFile(thumbnailPath, res, headers, `image/${query.format.toLowerCase()}`);
```
Comment (uhthomas) [inline server/src/immich/api-v1/asset/asset.service.ts:263]: We should be a bit more defensive than this. The actual implementation of `thumbnailPath` is questionable.

https://github.com/immich-app/immich/blob/d9e084706f3b7d2f7f38d945b98e6376b2778e95/server/src/immich/api-v1/asset/asset.service.ts#L573

From what I can see, a format of `xyz` will actually return a jpeg, and so serving a jpeg file with `image/xyz` is not great. It also seems that if the webp thumbnail doesn't exist, then the jpeg will be used. Again, serving a jpeg with `image/webp` isn't great. `getThumbnailPath` should probably be changed to not do that.

**Review by uhthomas — CHANGES_REQUESTED** [review]

File: server/src/immich/api-v1/asset/asset.service.ts (hunk 2 above)
Comment (jrasm91) [reply server/src/immich/api-v1/asset/asset.service.ts:263]: Can we have get thumbnail path return a path _and_ content type, which can be used in stream file? We can hardcore the content type for jpeg or webp depending on which path is used.

Comment (mertalev) [reply server/src/immich/api-v1/asset/asset.service.ts:264]: I changed it so `getThumbnailPath` throws an error if the requested format isn't available (I could also add validation in `getAssetThumbnail` if requested). If there's anything that relies on the current behavior of falling back to JPEG, then @jrasm91's suggestion works too. 

We could possibly combine the two by making `getThumbnailPath`'s `format` parameter optional: fail if an unavailable format is specified, else try to find *something*.

File: server/src/immich/api-v1/asset/asset.service.ts [hunk 3]
```diff
@@ -573,16 +574,18 @@ export class AssetService {
...
+        return asset.webpPath;
 
       case GetAssetThumbnailFormatEnum.JPEG:
-      default:
         if (!asset.resizePath) {
-          throw new NotFoundException('resizePath not set');
+          throw new NotFoundException(`No ${format} thumbnail found for asset ${asset.id}`);
         }
         return asset.resizePath;
+      default:
```
Comment (uhthomas) [inline server/src/immich/api-v1/asset/asset.service.ts:587]: Does anything rely on this behaviour?

Comment (mertalev) [reply server/src/immich/api-v1/asset/asset.service.ts:587]: From what I can tell, the main instance where the fallback would come up is in the narrow window where the jpeg thumbnail is generated but the webp thumbnail is still queued.

Comment (jrasm91) [reply server/src/immich/api-v1/asset/asset.service.ts:587]: For a large list of assets jpeg could be generated and then webp gets added to the end of the queue and might take awhile before it is processed. If you have 10k photos queued the jpeg is generated and the webp becomes task 10,001. The mobile app gets a notification after the jpeg is generated so it might try to access some form of thumbnail after that. Not sure if it asks for webp or not. Would be worth checking.

File: server/src/immich/api-v1/asset/asset.service.ts (hunk 2 above)
Comment (jrasm91) [reply server/src/immich/api-v1/asset/asset.service.ts:264]: It's just tricky changing the behavior of the code, especially when it is so fundamental like serving thumbnails, which is crucial to the main timeline both on the web and mobile app.

I'd probably prefer to see a bug fix to add the content type header without changing any other behavior, personally.

Or, if you do want to change it you need to do some thorough testing of the new behavior to make sure it works on mobile, web, and during a large CLI upload.

File: server/src/immich/api-v1/asset/asset.service.ts (hunk 3 above)
Comment (mertalev) [reply server/src/immich/api-v1/asset/asset.service.ts:587]: Every usage of this endpoint queries it with `format` omitted (defaulting to webp). Would it make sense to switch the order of those jobs in that case so webp is generated first?

Comment (jrasm91) [reply server/src/immich/api-v1/asset/asset.service.ts:587]: Webp is generated from the jpeg right now...

Comment (jrasm91) [reply server/src/immich/api-v1/asset/asset.service.ts:587]: This is just a rabbit hole imo requiring bigger changes which we could avoid by _only_ fixing content type header without changing any other behavior.

Comment (mertalev) [reply server/src/immich/api-v1/asset/asset.service.ts:587]: Fair enough, I'll have it validate that it's a valid enum value but keep the fallback to jpeg.

File: server/src/immich/api-v1/asset/asset.service.ts [hunk 4]
```diff
@@ -571,18 +572,25 @@ export class AssetService {
...
+    if (!Object.values(GetAssetThumbnailFormatEnum).includes(format)) {
+      throw new UnsupportedMediaTypeException(`Unsupported thumbnail format requested: ${format}`);
+    }
+
     switch (format) {
       case GetAssetThumbnailFormatEnum.WEBP:
-        if (asset.webpPath && asset.webpPath.length > 0) {
-          return asset.webpPath;
+        if (asset.webpPath) {
+          return [asset.webpPath, GetAssetThumbnailFormatEnum.WEBP];
```
Comment (jrasm91) [inline server/src/immich/api-v1/asset/asset.service.ts:582]: Can we just pass a valid content type here? No need to get fancy I think. Just return `image/webp`

Comment (mertalev) [reply server/src/immich/api-v1/asset/asset.service.ts]: Sure thing

File: server/src/immich/api-v1/asset/asset.service.ts [hunk 5]
```diff
@@ -571,18 +572,25 @@ export class AssetService {
   }
 
   private getThumbnailPath(asset: AssetEntity, format: GetAssetThumbnailFormatEnum) {
+    if (!Object.values(GetAssetThumbnailFormatEnum).includes(format)) {
+      throw new UnsupportedMediaTypeException(`Unsupported thumbnail format requested: ${format}`);
+    }
+
```
Comment (jrasm91) [inline server/src/immich/api-v1/asset/asset.service.ts:578]: We should be able to replace this with class validation in the dto directly btw. Maybe that is for a separate PR though.

**Review by jrasm91 — APPROVED** [review]

File: server/src/immich/api-v1/asset/asset.service.ts (hunk 5 above)
Comment (mertalev) [reply server/src/immich/api-v1/asset/asset.service.ts]: Good idea! Done

File: server/src/immich/api-v1/asset/asset.service.ts [hunk 6]
```diff
@@ -573,16 +573,19 @@ export class AssetService {
...
 
       case GetAssetThumbnailFormatEnum.JPEG:
       default:
         if (!asset.resizePath) {
-          throw new NotFoundException('resizePath not set');
+          throw new NotFoundException(`No thumbnail found for asset ${asset.id}`);
         }
-        return asset.resizePath;
+        if (format != GetAssetThumbnailFormatEnum.JPEG) {
+          this.logger.warn(`${format} thumbnail requested but not found for asset ${asset.id}, falling back to JPEG`);
```
Comment (jrasm91) [inline server/src/immich/api-v1/asset/asset.service.ts:586]: You can log this without the if statement if you move it up a few lines 😛

Comment (mertalev) [reply server/src/immich/api-v1/asset/asset.service.ts]: You have a point there...
