### PR TITLE
fix(web): prevent resetting date input when entering 0

### LINKED ISSUE #5673: [BUG] Editing timestamp with leading 0 clears the timestamp
### The bug

If I am editing the timestamp of a photo, entering a 0 as the first character for an hour clears the whole timestamp.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.90.2

### Version of Immich Mobile App

v1.90.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Open a photo
2. Edit date and time
3. Click on the hour field
4. Enter a 0
```

### Additional information

_No response_

### LINKED ISSUE #6621: Change Date/Datetime - Bad Usabillity
### The bug

Hey!

I imported some photos from my Google Photos into Immich.
Many photos have correct metadata, but some do not. You can see from my example that the photo originally comes from Whatsapp (%-WA%). It also has the correct location (not in all cases), but the wrong date. The import date is there.

If I change the date (to catalog everything correctly), I click on the pencil and enter the date. After the day is entered, the month appears, and when I enter the month, the day is set to "dd" again. 

I have attached a video to visualize the topic. 

https://github.com/immich-app/immich/assets/47820557/56c170e4-ad33-4e33-a447-8904d45dd3a3

### The OS that Immich Server is running on

Docker (Debian 12 Bookworm - Proxmox) 

### Version of Immich Server

v.1.93.3

### Version of Immich Mobile App

v.1.93.2 build.119

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
0. Show Video :D
1. Open Photo
2. Click Edit Button
3. Enter Date/Time
...
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by michelheusschen**
The date input field will reset completely when a 0 is entered anywhere. The date is considered invalid in that case and the value will be set to an empty string, causing the input to be reset. Fixed by filtering for an empty string and only setting that when focus on the input is lost.

Fixes #6621 and fixes #5673

### CODE REVIEW

**Review by mertalev — APPROVED** [review]
LGTM

File: web/src/lib/components/elements/date-input.svelte [hunk 1]
```diff
@@ -0,0 +1,24 @@
+<script lang="ts">
+  import type { HTMLInputAttributes } from 'svelte/elements';
+
+  interface $$Props extends HTMLInputAttributes {
+    type: 'date' | 'datetime-local';
+  }
+
+  export let value: $$Props['value'] = undefined;
```
Comment (danieldietzler) [inline web/src/lib/components/elements/date-input.svelte:8]: This is cool! Didn't know you could do this in svelte 4 already - I was excited for this in svelte 5 though haha

**Review by danieldietzler — APPROVED** [review]

**Comment by alextran1502** [comment]
Hi Michel, can you help resolve the conflict?
