### PR TITLE
fix(web): Reset asset selection when refreshing and changing folder

### LINKED ISSUE #15177: [Bug] Selection does not get reset when navigating folders
### The bug

After selecting all assets in a folder and adding them to an album, the assets should be deselected

(It's my fault lol #15049 )

### The OS that Immich Server is running on

-

### Version of Immich Server

v1.124.0

### Version of Immich Mobile App

-

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

1. Select all assets in a folder
2. Add them to an album

### Relevant log output

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by arnolicious**
Fixes #15177 

Asset selection in folder view now gets cleared when:
- Assets are updated
- Assets are added to Albums
- navigating to other folder

### CODE REVIEW

File: web/src/routes/(user)/folders/[[photos=photos]]/[[assetId=id]]/+page.svelte [hunk 1]
```diff
@@ -66,9 +64,18 @@
     return url.href;
   };
 
+  $effect(() => {
+    // Clear the asset selection when the path changes
+    // Reference the currentPath to trigger the effect
+    // eslint-disable-next-line @typescript-eslint/no-unused-expressions
+    currentPath;
```
Comment (alextran1502) [inline web/src/routes/(user)/folders/[[photos=photos]]/[[assetId=id]]/+page.svelte:71]: @benmccann Is there a better way to implement the same mechanism in Svelte 5 than this?

Comment (benmccann) [reply web/src/routes/(user)/folders/[[photos=photos]]/[[assetId=id]]/+page.svelte:71]: how about something like this?
```
  afterNavigate(() => {
    // Clear the asset selection when the path changes
    cancelMultiselect(assetInteraction);
  });
```

https://svelte.dev/docs/kit/$app-navigation#afterNavigate

Comment (arnolicious) [reply web/src/routes/(user)/folders/[[photos=photos]]/[[assetId=id]]/+page.svelte:71]: oh yeah, that would be cleaner

**Review by alextran1502 — APPROVED** [review]
Thank you
