### PR TITLE
fix(server): Fix delay with multiple ml servers

### LINKED ISSUE #16269: Multiple ML servers causes 10s search delays if primary is not available
### The bug

The current implementation of multiple ML servers just tries each server in order without any status caching; this means that any servers that are not available will cause a delay of ~10s (whatever the timeout value is) before trying the next server.

For a standard 2-server setup (desktop PC with good GPU and NAS/NUC for general use) where the main server is off/disabled, all searches wait ~10s before resolving. In the worst case this will multiply to the number of offline servers.

Relevant code is at https://github.com/immich-app/immich/blob/ec58e1065fafc34ab675d8403cc2635566f5d912/server/src/repositories/machine-learning.repository.ts#L64

At a minimum, Immich should probably store a status for all known servers so that it can always send search requests to servers that are known to be available.

It could do this by just updating status when a server is used; or it could run status checks in the background (probably preferred). Additionally, might be good to run requests semi-asynchronously, eg:

1. Send request to server 1
2. If request isn't fulfilled within in 2s, send request to server 2 (but let the existing request keep running in case it takes longer than this)
3. Repeat for each server until fulfilled
4. Optionally cancel/halt unfulfilled requests

I could take a look at this, but I'm not familiar with the backend codebase and am very time poor... :)

### The OS that Immich Server is running on

Alpine

### Version of Immich Server

1.126.1

### Version of Immich Mobile App

1.126.1

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

1. Setup 2 or more ML server URLs
2. Turn off the first server
3. Do a search and observe 10s delay before results arrive
4. Delete the first server from settings to observe results instantly

### Relevant log output

```shell
Machine learning request to "http://192.168.xxx.xxx:3003" failed: fetch failed
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Tyris**
## Description

Adds a ping and backoff mechanism to ML servers to avoid sending requests to known offline servers. This significantly improves search speed (10s per server) when multiple URL's are configured of which some are offline.

Fixes #16269 

## How Has This Been Tested?

Configure multiple servers and try turning them on and off. Observe search responsiveness over time.

- [x] Test with single URL (no change)
- [x] Test with single URL, try disabling/re-enabling server - server is marked offline but not skipped (since it's the only server)
- [x] Test with multiple URLs, try disabling/re-enabling servers - servers are marked offline, non-final server is skipped if it's offline (after first failure - which takes ~10s), server recovers and receives requests after coming back online (next request goes to secondary server, subsequent requests go to primary)

<details><summary>Logs</h2></summary>
<pre>
[Nest] 17  - 02/24/2025, 3:33:01 PM    WARN [Api:MachineLearningRepository~s6hjuet9] Machine learning request to "http://192.168.xxx.xxx:3003" failed: fetch failed
[Nest] 17  - 02/24/2025, 3:33:01 PM     LOG [Api:MachineLearningRepository~s6hjuet9] Setting http://192.168.xxx.xxx:3003 ML server to inactive.
[Nest] 17  - 02/24/2025, 3:33:02 PM     LOG [Api:MachineLearningRepository~s6hjuet9] Setting http://immich-machine-learning:3003 ML server to active.
[Nest] 17  - 02/24/2025, 3:33:37 PM     LOG [Api:MachineLearningRepository~b8fbaawa] Setting http://192.168.xxx.xxx:3003 ML server to active.
[Nest] 17  - 02/24/2025, 3:34:13 PM    WARN [Api:MachineLearningRepository~nt4fi2qe] Machine learning request to "http://192.168.xxx.xxx:3003" failed: fetch failed
[Nest] 17  - 02/24/2025, 3:34:13 PM     LOG [Api:MachineLearningRepository~nt4fi2qe] Setting http://192.168.xxx.xxx:3003 ML server to inactive.
[Nest] 17  - 02/24/2025, 3:35:38 PM     LOG [Api:MachineLearningRepository~ay7y9rbu] Setting http://192.168.xxx.xxx:3003 ML server to active.
[Nest] 17  - 02/24/2025, 3:36:40 PM    WARN [Api:MachineLearningRepository~hq80o96f] Machine learning request to "http://192.168.xxx.xxx:3003" failed: fetch failed
[Nest] 17  - 02/24/2025, 3:36:40 PM     LOG [Api:MachineLearningRepository~hq80o96f] Setting http://192.168.xxx.xxx:3003 ML server to inactive.
[Nest] 17  - 02/24/2025, 3:36:40 PM    WARN [Api:MachineLearningRepository~hq80o96f] Machine learning request to "http://immich-machine-learning:3003" failed: fetch failed
[Nest] 17  - 02/24/2025, 3:36:40 PM     LOG [Api:MachineLearningRepository~hq80o96f] Setting http://immich-machine-learning:3003 ML server to inactive.
[Nest] 17  - 02/24/2025, 3:36:40 PM   ERROR [Api:ErrorInterceptor~hq80o96f] Unknown error: Error: Machine learning request '{"clip":{"textual":{"modelName":"ViT-L-16-SigLIP-384__webli"}}}' failed for all URLs
Error: Machine learning request '{"clip":{"textual":{"modelName":"ViT-L-16-SigLIP-384__webli"}}}' failed for all URLs
    at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:89:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MachineLearningRepository.encodeText (/usr/src/app/dist/repositories/machine-learning.repository.js:112:26)
    at async SearchService.searchSmart (/usr/src/app/dist/services/search.service.js:62:27)
[Nest] 17  - 02/24/2025, 3:37:07 PM     LOG [Api:MachineLearningRepository~vsfkmudg] Setting http://immich-machine-learning:3003 ML server to active.
[Nest] 17  - 02/24/2025, 3:37:37 PM     LOG [Api:MachineLearningRepository~ykubnump] Setting http://192.168.xxx.xxx:3003 ML server to active.
</pre>
</details>

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation if applicable
- [x] I have no unrelated changes in the PR.
- [x] I have confirmed that any new dependencies are strictly necessary.
- [x] I have written tests for new code (if applicable)
- [x] I have followed naming conventions/patterns in the surrounding code
- [x] All code in `src/services` uses repositories implementations for database calls, filesystem operations, etc.
- [x] All code in `src/repositories/` is pretty basic/simple and does not have any immich specific logic (that belongs in `src/services`)

Feedback please (particularly on un-checked items above).

Should we make the 2s (ping timeout) and 30s (backoff time) values configurable?

### CODE REVIEW

**Comment by mertalev** [comment]
> Should we make the 2s (ping timeout) and 30s (backoff time) values configurable?

I'm fine with making them environmental variables. It's cleaner and no overhead compared to fetching the config JSON in this case.

**Comment by Tyris** [comment]
@mertalev, I suggest this is labelled bugfix; since it's a pretty major issue for anyone with multi-ml server configured (which I assume is moderately common).

File: server/src/repositories/machine-learning.repository.ts [hunk 1]
```diff
@@ -55,16 +56,75 @@ export type MachineLearningRequest = ClipVisualRequest | ClipTextualRequest | Fa
...
+    this.setUrlAvailability(url, active);
+    return active;
   }
 
   private async predict<T>(urls: string[], payload: ModelPayload, config: MachineLearningRequest): Promise<T> {
     const formData = await this.getFormData(payload, config);
+    let iterations = urls.length;
     for (const url of urls) {
+      // Skip availability logic for the last (or only) URL
+      if (--iterations > 0) {
```
Comment (alextran1502) [inline server/src/repositories/machine-learning.repository.ts:104]: I find this code block is not straightforward to understand. Is there any way to make the flow more straightforward to read?

**Comment by alextran1502** [comment]
Can you help run `npm run format:fix` from the `docs` directory?

File: server/src/repositories/machine-learning.repository.ts (hunk 1 above)
Comment (Tyris) [reply server/src/repositories/machine-learning.repository.ts:104]:
```
    let counter = 0;
    for (const url of urls) {
      counter++;
      // Only use availability logic if this is not the last (or only) url
      if (counter <= urls.length) {
        const availability = this.urlAvailability[url];
```

Is this clearer?

The intent is that if there's only a single URL (or we're on the last one) that it should skip the logic and just send the request to it (better than to try and fail than just give up prematurely).

File: server/src/constants.ts [hunk 2]
```diff
@@ -38,6 +38,11 @@ export const ONE_HOUR = Duration.fromObject({ hours: 1 });
 
 export const APP_MEDIA_LOCATION = process.env.IMMICH_MEDIA_LOCATION || './upload';
 
+export const MACHINE_LEARNING_PING_TIMEOUT = Number(process.env.MACHINE_LEARNING_PING_TIMEOUT || 2000);
+export const MACHINE_LEARNING_AVAILABILITY_BACKOFF_TIME = Number(
+  process.env.MACHINE_LEARNING_AVAILABILITY_BACKOFF_TIME || 30_000,
+);
```
Comment (danieldietzler) [inline server/src/constants.ts:44]: Those should go to the config repository (https://github.com/immich-app/immich/blob/main/server/src/repositories/config.repository.ts)

File: server/src/repositories/machine-learning.repository.ts [hunk 3]
```diff
@@ -55,16 +56,76 @@ export type MachineLearningRequest = ClipVisualRequest | ClipTextualRequest | Fa
...
+  // Note that deleted URL's are not removed from this map (ie: they're leaked)
+  // Cleaning them up is low priority since there should be very few over a
+  // typical server uptime cycle
+  private urlAvailability: {
+    [url: string]:
+      | {
+          active: boolean;
+          lastChecked: number;
+        }
+      | undefined;
```
Comment (danieldietzler) [inline server/src/repositories/machine-learning.repository.ts:68]: Shouldn't `[url: string]?: {...}` work?

File: server/src/repositories/machine-learning.repository.ts [hunk 4]
```diff
@@ -55,16 +56,76 @@ export type MachineLearningRequest = ClipVisualRequest | ClipTextualRequest | Fa
...
   constructor(private logger: LoggingRepository) {
     this.logger.setContext(MachineLearningRepository.name);
+    this.urlAvailability = {};
+  }
+
+  private setUrlAvailability(url: string, active: boolean) {
+    const current = this.urlAvailability[url];
+    if (current?.active !== active) {
+      this.logger.log(`Setting ${url} ML server to ${active ? 'active' : 'inactive'}.`);
+    }
```
Comment (danieldietzler) [inline server/src/repositories/machine-learning.repository.ts:80]: This is just for logging. I don't think that's necessary.

File: server/src/repositories/machine-learning.repository.ts [hunk 5]
```diff
@@ -55,16 +56,76 @@ export type MachineLearningRequest = ClipVisualRequest | ClipTextualRequest | Fa
...
+    this.setUrlAvailability(url, active);
+    return active;
   }
 
   private async predict<T>(urls: string[], payload: ModelPayload, config: MachineLearningRequest): Promise<T> {
     const formData = await this.getFormData(payload, config);
+    let urlCounter = 0;
     for (const url of urls) {
+      urlCounter++;
+      // Only use availability logic if this is not the last (or only) url
```
Comment (danieldietzler) [inline server/src/repositories/machine-learning.repository.ts:104]: Why shouldn't we try to reach the endpoint if it's the last one? Also, it would help a lot for readability if you would invert it; `if (urlCounter >= urls.length) { continue; }`

File: server/src/repositories/machine-learning.repository.ts [hunk 6]
```diff
@@ -55,16 +56,76 @@ export type MachineLearningRequest = ClipVisualRequest | ClipTextualRequest | Fa
...
+      if (urlCounter < urls.length) {
+        const availability = this.urlAvailability[url];
+        if (availability === undefined) {
+          // If this is a new endpoint, then check inline and skip if it fails
+          if (!(await this.checkAvailability(url))) {
+            continue;
+          }
```
Comment (danieldietzler) [inline server/src/repositories/machine-learning.repository.ts:111]: What is this if for? Given everything below is an else if, running into the continue or not running into it has the same effect.

File: server/src/repositories/machine-learning.repository.ts [hunk 7]
```diff
@@ -55,16 +56,76 @@ export type MachineLearningRequest = ClipVisualRequest | ClipTextualRequest | Fa
...
+        } else if (
```
Comment (danieldietzler) [inline server/src/repositories/machine-learning.repository.ts:112]: Speaking of `else if`s, in the gist of early returns I'd prefer simple `if (...) { continue; }` here instead of this else if branching. That makes it harder to read.

File: server/src/repositories/machine-learning.repository.ts [hunk 8]
```diff
@@ -55,16 +56,76 @@ export type MachineLearningRequest = ClipVisualRequest | ClipTextualRequest | Fa
...
+          availability.active === false &&
```
Comment (danieldietzler) [inline server/src/repositories/machine-learning.repository.ts:113]:
```suggestion
          !availability.active&&
```

File: server/src/repositories/machine-learning.repository.ts (hunk 5 above)
Comment (mertalev) [reply server/src/repositories/machine-learning.repository.ts:104]: If it's the only URL (which is the most common case), the availability check is pointless. I don't have a preference for whether the last (of multiple) servers is skipped.

Comment (danieldietzler) [reply server/src/repositories/machine-learning.repository.ts:104]: Yeah I get the argument if it's the only URL, which is why I specifically asked for the last one. If we only want to treat it differently if it's the only URL we could move it out of the loop, making things simpler

File: server/src/constants.ts (hunk 2 above)
Comment (Tyris) [reply server/src/constants.ts:44]: I wasn't sure how to inject the config repository - there didn't seem to be any other examples of repos consuming repos. Can you give me a pointer? Also, why is the `IMMICH_MEDIA_LOCATION` loaded in this way but not other constants?

File: server/src/repositories/machine-learning.repository.ts (hunk 4 above)
Comment (Tyris) [reply server/src/repositories/machine-learning.repository.ts:80]: My view is that it's useful for anyone trying to understand when/why a certain ML was used, but Immich seems very light on logging by default - could we change it to verbose level?

File: server/src/repositories/machine-learning.repository.ts (hunk 5 above)
Comment (Tyris) [reply server/src/repositories/machine-learning.repository.ts:104]: The "availability" logic will **skip** the server if it is known to be offline. It will additionally ping the endpoint (to determine if it's back online for future requests, but not the current one).

For this reason, we don't want to skip the last server even if it was previously offline since a timeout in that case is probably better than a silent immediate failure (especially with no logging!!). Basically the last entry is always tried even we think its offline.

I agree that the logic is not necessarily obvious; but in the absence of a better suggestion, I do believe it's optimal.

> Why shouldn't we try to reach the endpoint if it's the last one? Also, it would help a lot for readability if you would invert it; `if (urlCounter >= urls.length) { continue; }`

Not exactly, but I can rework it slightly with that in mind.

File: server/src/repositories/machine-learning.repository.ts (hunk 6 above)
Comment (Tyris) [reply server/src/repositories/machine-learning.repository.ts:111]: The `else if` is for the parent `if`. The `continue` alters the flow of the `for` loop - effectively skipping new (previously unknown) servers if they're detected as offline (noting that we **do** await in this case).

File: server/src/repositories/machine-learning.repository.ts (hunk 7 above)
Comment (Tyris) [reply server/src/repositories/machine-learning.repository.ts:112]: See above.

File: server/src/repositories/machine-learning.repository.ts (hunk 8 above)
Comment (Tyris) [reply server/src/repositories/machine-learning.repository.ts:113]: This works, but wouldn't if I removed the `else` since it would then need to be `availability?.active === false` to catch the falsey case (which I think is how I had it previously).

Will ammend.

File: server/src/constants.ts (hunk 2 above)
Comment (danieldietzler) [reply server/src/constants.ts:44]: Oh sorry I didn't pay close enough attention and didn't realize it's in an repository. Then it's fine this way. The alternative would be passing it to the function wherever it gets called in a service, but that could be annoying.

File: server/src/repositories/machine-learning.repository.ts (hunk 6 above)
Comment (danieldietzler) [reply server/src/repositories/machine-learning.repository.ts:112]: Oh I got the brackets wrong, apologies. Prime example why huge `if` blocks are hard to read/follow :P

File: server/src/repositories/machine-learning.repository.ts (hunk 7 above)
Comment (danieldietzler) [reply server/src/repositories/machine-learning.repository.ts:113]: We could extract this into its own method and then potentially make use of early returns, right?

Comment (Tyris) [reply server/src/repositories/machine-learning.repository.ts:113]: Have extracted, but adjusting if/else structure much makes it more complicated to read.

File: server/src/repositories/machine-learning.repository.ts [hunk 9]
```diff
@@ -55,16 +56,84 @@ export type MachineLearningRequest = ClipVisualRequest | ClipTextualRequest | Fa
...
+      const response = await fetch(new URL('/ping', url), {
+        signal: AbortSignal.timeout(MACHINE_LEARNING_PING_TIMEOUT),
+      });
+      active = response.ok;
+    } catch {}
+    this.setUrlAvailability(url, active);
+    return active;
+  }
+
+  private async shouldSkipUrl(url: string, isLast: boolean) {
```
Comment (mertalev) [inline server/src/repositories/machine-learning.repository.ts:99]: `isLast` is awkward; it's a boolean parameter that can already be the answer to the question "should this URL be skipped". I'd prefer if it were removed and you adjust the if condition of the call site to only call this function if `isLast` is false.

**Review by mertalev — APPROVED** [review]
