### PR TITLE
fix: timeline scroll after navigate

### LINKED ISSUE #23547: [Web] Click on "Photos" menu does not take back to top
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Clicking on the "Photos" on the sidebar menu, when you're already in the "Photos" page, does not reset scroll position to top as it was before.
So, you have to manually scroll to top of the page or change page and then select "Photos" again.

### The OS that Immich Server is running on

Docker on Synology

### Version of Immich Server

v2.2.1

### Version of Immich Mobile App

v2.2.1

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Device make and model

_No response_

### Your docker-compose.yml content

```YAML
Not meaningful
```

### Your .env content

```Shell
Not meaningful
```

### Reproduction steps

1. Open the Web interface
2. Go to "Photos" page
3. Scroll down
4. Click on "Photos" on left menu
5. Nothing happens
...

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by danieldietzler**
Fixes #23547

### CODE REVIEW

File: web/src/lib/components/timeline/Timeline.svelte [hunk 1]
```diff
@@ -245,11 +247,7 @@
         initialLoadWasAssetViewer = isAssetViewerPage && !hasNavigatedToOrFromAssetViewer;
       }
 
-      const isDirectTimelineLoad = isDirectNavigation && !isAssetViewerPage;
-      const isNavigatingFromAssetViewer = !isDirectNavigation && hasNavigatedToOrFromAssetViewer;
-      const scrollToAssetQueryParam = isDirectTimelineLoad || isNavigatingFromAssetViewer;
-
-      void scrollAfterNavigate({ scrollToAssetQueryParam });
```
Comment (danieldietzler) [inline web/src/lib/components/timeline/Timeline.svelte:252]: @midzelis this is quite invasive. I couldn't find any scenario where we don't want to scroll. Could you explain in which case we don't want to scroll?

**Review by alextran1502 — APPROVED** [review]
Tested and worked well

File: web/src/lib/components/timeline/Timeline.svelte (hunk 1 above)
Comment (midzelis) [reply web/src/lib/components/timeline/Timeline.svelte:252]: I'm fine always attempting to scroll to query param for all timeline/asset-viewer routes if it works and solves the problem. 

This is less important since #22838 was merged. Previously, if you had scrolled when reloading the timeline due to a browser back or asset-viewer back-arrow, and the asset you were viewing was mid-viewport, if you had scrolled again to that asset, it would always move the asset to the top/left of the viewport, moving it away from its current mid-viewport position. 

However, there is still one place where you don't really want to scroll - and thats on direct loads of asset-viewer. (i.e. `/photos/<id>?at=<id>`) - that may be a bit contrived, because you'd never really want to specify an `?at=` param on the asset-viewer routes, but because the asset-viewer loads literally on top of the timeline components, this might have caused issues. 

The bigger problem is the fact that several timebucket API calls, memories API calls, etc are called on asset-viewer routes - which are completely invisible behind the asset-viewer. But thats a task for another day.

Comment (danieldietzler) [reply web/src/lib/components/timeline/Timeline.svelte:252]: Oh got it that makes sense. Then I'd like to go with this solution for now. And yeah, the asset viewer only being a full screen overlay makes a lot of things kind of annoying; definitely warrants a larger discussion eventually
