### PR TITLE
fix(web): Sort timezones in assets settings by offset

### LINKED ISSUE #10695: Timezones on web are sorted alphabetically
When changing an asset's timezone on the web, the list is sorted alphabetically. It should be sorted by offset instead.

image

### PR DESCRIPTION
**Pull request by WazWazMan**
fixes #10695

### CODE REVIEW

File: web/src/lib/components/shared-components/change-date.svelte [hunk 1]
```diff
@@ -24,10 +24,20 @@
...
-    value: 'UTC' + DateTime.local({ zone }).toFormat('ZZ'),
-  }));
+  const timezones: ZoneOption[] = Intl.supportedValuesOf('timeZone')
+    .map((zone: string) => ({
+      label: zone + ` (${DateTime.local({ zone }).toFormat('ZZ')})`,
+      value: 'UTC' + DateTime.local({ zone }).toFormat('ZZ'),
+    }))
+    .sort((zoneA, zoneB) => {
+      let numericallyCorrect =
+        Number(zoneA.value.slice(3).replace(':', '.')) - Number(zoneB.value.slice(3).replace(':', '.'));
```
Comment (michelheusschen) [inline web/src/lib/components/shared-components/change-date.svelte:34]: `DateTime` also has `offset` property, maybe we can use that instead?

Comment (WazWazTheDeveloper) [reply web/src/lib/components/shared-components/change-date.svelte]: Sure! I wasn't aware of this property.
I have changed it to use `offset` property instead now

File: web/src/lib/components/shared-components/change-date.svelte [hunk 2]
```diff
@@ -24,10 +24,19 @@
     value: string;
   };
 
-  const timezones: ZoneOption[] = Intl.supportedValuesOf('timeZone').map((zone: string) => ({
-    label: zone + ` (${DateTime.local({ zone }).toFormat('ZZ')})`,
-    value: 'UTC' + DateTime.local({ zone }).toFormat('ZZ'),
-  }));
+  const timezones: ZoneOption[] = Intl.supportedValuesOf('timeZone')
+    .sort((zoneA, zoneB) => {
+      let numericallyCorrect = DateTime.local({ zone: zoneA }).offset - DateTime.local({ zone: zoneB }).offset;
```
Comment (bo0tzz) [inline web/src/lib/components/shared-components/change-date.svelte:29]: You could do something like this so you're only calling `DateTime.local()` once:
```typescript
  const timezones: ZoneOption[] = Intl.supportedValuesOf('timeZone')
  	.map((zone) => DateTime.local(zone))
    .sort((zoneA, zoneB) => {
      let numericallyCorrect = zoneA.offset - zoneB.offset;
      ...etc
```

**Review by bo0tzz — APPROVED** [review]
One unnecessary nitpick, but looks good. Thanks!

File: web/src/lib/components/shared-components/change-date.svelte (hunk 2 above)
Comment (WazWazTheDeveloper) [reply web/src/lib/components/shared-components/change-date.svelte:29]: But you will have to pass the zone string for the creation of the list items in the last .map
so it will be something more like this
```ts
  const timezones: ZoneOption[] = Intl.supportedValuesOf('timeZone')
    .map((zone) => ({
      datatime: DateTime.local({ zone }),
      string: zone,
    }))
    .sort((zoneA, zoneB) => {
      let numericallyCorrect = zoneA.datatime.offset - zoneB.datatime.offset;
      if (numericallyCorrect != 0) {
        return numericallyCorrect;
      }
      const alphabeticallyCorrect = zoneA.string.localeCompare(zoneB.string, undefined, { sensitivity: 'base' });
      return alphabeticallyCorrect;
    })
    .map((zone) => ({
      label: zone.string + ` (${DateTime.local({ zone: zone.string }).toFormat('ZZ')})`,
      value: 'UTC' + DateTime.local({ zone: zone.string }).toFormat('ZZ'),
    }));
```

Comment (michelheusschen) [reply web/src/lib/components/shared-components/change-date.svelte:29]: `DateTime.zoneName` can be used:

```ts
const timezones: ZoneOption[] = Intl.supportedValuesOf('timeZone')
  .map((zone) => DateTime.local({ zone }))
  .sort((a, b) => a.offset - b.offset || a.zoneName.localeCompare(b.zoneName, undefined, { sensitivity: 'base' }))
  .map((date) => {
    const offset = date.toFormat('ZZ');
    return {
      label: `${date.zoneName} (${offset})`,
      value: 'UTC' + offset,
    };
  });
```

**Comment by alextran1502** [comment]
Hello, can you add a unit test for this mechanism? Thank you for the contribution!
